### ISSUE TITLE
Type imports broken in TypeScript's NodeNext mode (ESM support)

### ISSUE THREAD

**Issue by nickluger** [ueberdosis/tiptap#3488] opened 2022-12-04 18:16 UTC
### What’s the bug you are facing?

This used to work in `beta.199`:

```ts
import type { JSONContent } from "@tiptap/core";
```

Now (`beta.204`) it shows the `Module has no exported member` error.

This could be due to this [TS issue](https://github.com/microsoft/TypeScript/issues/50482), meaning the `index.d.ts` exported by tiptap is using expressions like `export * from './CommandManager';`, while it should be `export * from './CommandManager.js';`.

I'm using:
-  ESM, i.e. `"type": "module"` in my `package.json`.
- TS version `4.9.3`.
- TS `NodeNext` mode, as supposed to be used for ESM projects.

### Which browser was this experienced in? Are any special extensions installed?

This happens in TS.

### How can we reproduce the bug on our side?

1. Create an ESM TS project with `"type": "module"` in your `package.json` and `"module": "NodeNext"` in your `tsconfig.json`.
2. Write `import type { JSONContent } from "@tiptap/core";`
3. Run `tsc`
4. See the error.

### Can you provide a CodeSandbox?

No, that's in TS.

### What did you expect to happen?

TS should resolve the type.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by benasher44** [comment] 2023-01-06 16:24
Any chance that 2023 is the year of nodenext support in tiptap? 🙏

**Comment by dziraf** [comment] 2023-03-03 07:34
Any idea if it is possible to resolve this temporarily without creating patch packages as it seems to be an issue with every subpackage?

**Comment by nickluger** [comment] 2023-03-03 08:23
> Any idea if it is possible to resolve this temporarily without creating patch packages as it seems to be an issue with every subpackage?

We just copied the types we needed (for now).... 😅

**Comment by dziraf** [comment] 2023-03-27 14:58
@bdbch I prepared a repository which should allow you to reproduce the problem, I also added some additional info/context to it's README: https://github.com/dziraf/tiptap-types-issue

**Comment by bdbch** [comment] 2023-03-27 15:23
Thanks @dziraf, I started to work on a fix for this but I'd like to postpone it for the next version since I can't make sure my changes won't break other build processes right now. Need to test it a bit more. But I'll keep it on focus!

**Comment by benasher44** [comment] 2023-04-19 02:57
Just saw there's an RC. Any chance this will still make 2.1.0?

**Comment by bdbch** [comment] 2023-04-19 05:06
Potentially yes. Since this brings a lot of changes on how imports are made I just want to make sure the change to file extensions doesn't break the existing builds. in general if someone wants to pick up this issue to work on it feel free. Right now I'm a bit loaded with other things.

**Comment by benasher44** [comment] 2023-04-29 02:01
With a hint, I could take a crack at it. My issue right now is I'm not super familiar with how people are using rollup to do this, and that seems to be the core build tool being used here.

**Comment by benasher44** [comment] 2023-04-30 19:09
Actually it looks like just adding file endings to the imports fixes it. This should be harmless to add even for CJS users, since omitting them there is mostly stylistic (and maybe as a negative leans on the behavior of the resolver to choose the final path)

**Comment by benasher44** [comment] 2023-04-30 20:16
I put up a #4001 — went with using eslint to enforce it.

**Closed** 2023-06-30 19:03 UTC
Labels: Type: Bug
