### ISSUE TITLE
Enter not adding line break sometimes

### ISSUE THREAD

**Issue by janpeterka** [ueberdosis/tiptap#2620] opened 2022-03-14 11:25 UTC
### What’s the bug you are facing?

When testing tiptap via CDN, I came to following error:

- when i press Enter with cursor at the end of line, it does nothing and generates following errors:
![Screenshot from 2022-03-14 12-23-55](https://user-images.githubusercontent.com/6343648/158162584-d85844d2-05e9-4e84-9311-599efaa55bcd.png)

no problem when in other part of line.

### How can we reproduce the bug on our side?

Using CDN:
```
<script type="module">
	    import { Editor } from 'https://cdn.skypack.dev/@tiptap/core?min'
	    import StarterKit from 'https://cdn.skypack.dev/@tiptap/starter-kit?min'

	    const editor = new Editor({
			element: document.querySelector("#editor"),
			extensions: [
		          StarterKit
			],
  			content: '<p>write here...</p>',
	    })

  	</script>
```

### What did you expect to happen?

Line break, no errors

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2022-03-25 09:31
Duplicate of https://github.com/ueberdosis/tiptap/issues/1537
See: https://github.com/ueberdosis/tiptap/issues/1537#issuecomment-985533260

**Closed by philippkuehn** 2022-03-25 09:31 UTC
Labels: bug
