### ISSUE TITLE
Vue JSON v-model Example

### ISSUE THREAD

**Issue by patrickcorrigan** [ueberdosis/tiptap#1944] opened 2021-09-27 10:33 UTC
https://github.com/ueberdosis/tiptap/blob/main/demos/src/GuideGettingStarted/VModel/Vue/Editor.vue

Line 33

Should this be JSON.stringify instead of .toString()? 

When doing the comparison you just get [object object] otherwise?

**Comment by hanspagel** [comment] 2021-09-27 11:05
Thanks! Seems to be a duplicate of #1736. ✌️

**Closed by hanspagel** 2021-09-27 11:05 UTC
Labels: v2, documentation
