### ISSUE TITLE
AlpineJS v3 - Range Error: Applying a mismatched transaction

### ISSUE THREAD

**Issue by reefki** [ueberdosis/tiptap#1515] opened 2021-06-27 04:39 UTC
**Description**
I got `Range Error: Applying a mismatched transaction` when clicking on a menu button with AlpineJS v3.

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:
https://codesandbox.io/s/tiptap-v2-alpinejs-v3-s5x2o

**Comment by jelib3an** [comment] 2021-07-01 04:09
Hi, I think this is an Alpine issue. Downgrading to Alpine 2.8.2 works. It might have something to do with the fact that `this.editor` is a Proxy object - though it's just a theory. 

I don't know if the `getUnobservedData()` still works, but you could try to use it to get access to the actual editor object. https://codewithhugo.com/alpinejs-inspect-component-data-from-js/

Hope this info helps :smile:

**Comment by 0l1v3r5** [comment] 2021-07-02 03:37
Thanks but `getUnobservedData()` is no longer available.

**Comment by 0l1v3r5** [comment] 2021-07-02 03:38
@reefki did you find a way?

**Comment by jelib3an** [comment] 2021-07-02 06:25
It appears to be definitely a proxy issue. I sort of got something working here by storing the editor object in a closure. 
https://codesandbox.io/s/tiptap-v2-alpinejs-v3-forked-7rn6o?file=/index.js

You lose the reactivity with this approach though but it's a start and maybe this can point you in the right direction.

**Comment by 0l1v3r5** [comment] 2021-07-02 10:01
@jelib3an Thanks a lot.

**Comment by KevinBatdorf** [comment] 2021-07-02 16:53
If you add Alpine to the window scope you can use `Alpine.raw(editor)` to unwrap the proxy and it should work.

**Comment by robertdrakedennis** [comment] 2021-07-06 13:01
@KevinBatdorf apologies with pinging you, can you explain your solution more? I'm a bit of a novice when it comes down further into the technical stuff and would really like to understand how to alleviate this issue with your solution. Thanks!

**Comment by jelib3an** [comment] 2021-07-06 15:34
@KevinBatdorf Thanks for the suggestion! I never knew about `Alpine.raw()`

@robertdrakedennis Here's an example with the mentioned solution. 
https://codesandbox.io/s/tiptap-v2-alpinejs-v3-forked-2bbw8?file=/index.js

However, `Alpine.raw()` doesn't appear to be bindable for reactivity. I also am Alpine novice. Would be interested to know if anyone has any good suggestions as it would be kind of a hassle to create a separate attribute for every button we want to check activeness on.

**Comment by hanspagel** [comment] 2021-07-11 22:22
Just wanted to say that I have no experience with Alpine, but I’d love to update the docs when we found a solution. ✌️ Thanks for everyone helping out.

**Comment by KevinBatdorf** [comment] 2021-08-11 03:47
Using the demos above as a reference, instead of using `this.editor`, just use `window.editor = new Editor` (or name it however you like) and access it the same way. There's no need to make it a reactive property, and that seems to be what's breaking things here.

That's probably the more logical approach than my previous suggestion to unwrap the reactive parts on demand.

**Comment by EasterPeanut** [comment] 2021-08-21 10:21
Wanted to share my solution for having the editor not reactive, but still have a reactive menu for Tiptap/Alpine v3: https://codesandbox.io/s/tiptap-with-alpine-js-v3-q4qbp

**Comment by haubie** [comment] 2021-08-29 03:37
Thanks @EasterPeanut your codesandbox and also phoenix project were very helpful in migrating to Alpine 3!

**Comment by Mushr0000m** [comment] 2021-10-05 18:29
Yes thanks @EasterPeanut it helped ! Would be nice to have a solution without changing the variable scope like in VueJs and other though…

**Comment by francois-soapbox** [comment] 2021-11-08 10:45
@aspyropoulos Thanks!

**Comment by Atem18** [comment] 2022-01-27 23:04
Maybe docs should be edited no ?

**Comment by galaczi** [comment] 2022-01-30 17:31
Wow I didn't expect to go down this rabbit hole when I opened the Tiptap setup page. Honestly it looks much easier to just use vanilla JS. It's like a five liner.

**Comment by hanspagel** [comment] 2022-01-30 21:42
Maybe we can build an alpine plugin? 

As I said, I have nearly zero experience. If someone could send a PR with improvements to the doc page, that would be amazing!

**Comment by RobertCordes** [comment] 2022-05-08 14:32
Did anybody find a solution yet? I’m in the middle of upgrading a huge app to Alpine v3 and this is the only thing that’s holding me back. I've been working on this for days but I just can't figure out how to solve this issue. Maybe @calebporzio can give us a hint? 😇 Using Tiptap with Alpine v2 and Livewire is working flawlessly.

**Comment by gmlewis** [comment] 2022-05-29 16:25
I'm using my own custom EmitterProvider (based loosely on `y-websocket.js`) to talk to [emitter.io](https://emitter.io) and am not using AlpineJS at all, but also get this error when upgrading from `@tiptap/vue3@2.0.0-beta.2` to `@tiptap/vue3@2.0.0-beta.91`:

```
Uncaught RangeError: Applying a mismatched transaction
    at EditorState.applyInner (index.es.js:863:33)
    at EditorState.applyTransaction (index.es.js:831:1)
    at EditorState.apply (index.es.js:807:1)
    at Editor.dispatchTransaction (tiptap-core.esm.js:3457:1)
    at EditorView.dispatch (index.es.js:5285:29)
    at sync-plugin.js:401:1
    at ProsemirrorBinding.mux (mutex.js:35:1)
    at ProsemirrorBinding._typeChanged (sync-plugin.js:384:1)
    at Module.callAll (function.js:19:1)
    at callEventHandlerListeners (yjs.mjs:1863:12)
```

I just wanted to add another data point here while I keep trying to debug it in case others run into the same issue.

**Comment by azarai** [comment] 2022-06-03 06:39
Related to this error, I'm also experiencing a "Alpine Expression Error: editor is not defined" caused by a "Uncaught ReferenceError: editor is not defined".

Test project: I followed the instructions in the doc and set up the example with Alpine 3. The basic editor worked BUT as soon as I added BubbleMenu or FloatingMenu it breaks again and Alpine can't find the reference to the "editor" field anymore.

The placeholder extension worked though.

2 workarounds I found:

1. Downgraden Alpine to v2 (2.8.2) and it worked again. Code stayed the same.
2. Initialize the Editor outside of Alpine and set it as _window.editor_ and never add a reference as an Alpine field/data. Then in an Alpine triggered method, using _window.editor_ and calling methods on the editor worked just fine.

**Comment by francoism90** [comment] 2022-06-17 10:26
@azarai Could you please share your (full) solution? :)

**Comment by bdbch** [comment] 2022-06-25 14:29
As some people described already this is a Proxy issue with Alpine. Alpine is using Proxy to have reactive objects - which is why this error is occuring.

![image](https://user-images.githubusercontent.com/6538827/175778024-95d995bd-58a1-4c62-ac92-cd1ab110ae33.png)

Here you can see that a Proxy is sent to `applyTransaction` - since this is not the correct way to apply a transaction prosemirror is throwing this error.

Don't know a solution for now, just so people know more about why and where this is happening.

**Comment by samwillis** [comment] 2022-07-05 08:21
Just spotted this, and can hopefully point in the right direction, Alpine.js uses the reactive engine from Vue.js 3. Fixing it will be a very similar to what I did to get Vue3 working way back last year... https://github.com/ueberdosis/tiptap/issues/1166

From memory the trick with Vue was to use a [ShallowRef()](https://vuejs.org/api/reactivity-advanced.html#shallowref) to hold the Editor object, this stops the reactive engine from trying to track all properties and methods within TipTap. (we then did a bunch of stuff to make the toolbars reactive but my memory gives up at that point)

It doesn't look like Alpine exposes the `ShallowRef()` api, but that will defiantly be the starting point to getting it working while having the `Editor` be in your `x-data`.

(as others have mentioned having your editor object outside of `x-data` is a good workaround, but obviously not ideal)

**Comment by creativiii** [comment] 2022-07-17 16:05
I'm not 100% this is a solution but it seems to work in my case? (I need to do more testing).

So you define your editor outside Alpine:
```
window.editor = null;
```

Then, within the main x-data function we initialise the editor:
```
const data= (content: Content = '') => {
    async init(element: Element) {
      window.editor = new Editor({
            // stuff in here obviously
      });
}
```

Then we create a new function so we can access the editor from within our data function:
```
const data= (content: Content = '') => {
    async init(element: Element) {
      window.editor = new Editor({
            // stuff in here obviously
      });
    },
    editor: () => {
      return window.editor;
    },
}
```

Then from your html you can call this:
```
              <button
                data-text="Bold"
                @click="editor().chain().toggleBold().focus().run()"
                :class="{ 'is-active': editor().isActive('bold') }"
              >
                Bold
              </button>
```
The difference with the above is that instead of calling editor.chain() we call editor().chain().

As far as I can tell almost everything here works except for `:class="{ 'is-active': editor().isActive('bold') }"`.

**Comment by reefki** [comment] 2022-07-17 16:17
@creativiii yes, exactly what I did https://github.com/ueberdosis/tiptap/issues/1515#issuecomment-937327322 but you might want to put the editor in a collection instead so you access multiple editor instances in case you have multiple editors in a single page.

**Comment by creativiii** [comment] 2022-07-17 16:40
> @creativiii yes, exactly what I did [#1515 (comment)](https://github.com/ueberdosis/tiptap/issues/1515#issuecomment-937327322) but you might want to put the editor in a collection instead so you access multiple editor instances in case you have multiple editors in a single page.

Sorry! I must've completely skipped over your comment 😂
Did you figure out a solution to checking if a button `isActive`?

**Comment by reefki** [comment] 2022-07-17 17:04
> > @creativiii yes, exactly what I did [#1515 (comment)](https://github.com/ueberdosis/tiptap/issues/1515#issuecomment-937327322) but you might want to put the editor in a collection instead so you access multiple editor instances in case you have multiple editors in a single page.
> 
> Sorry! I must've completely skipped over your comment 😂 Did you figure out a solution to checking if a button `isActive`?

I have `buttons` attribute in my Alpine components. With this attribute, not only I can give a different set of buttons for each editors but also I can use this to hold the buttons state and update the state by listening to `onUpdate` and `onTrandaction` events.

In the html you can just loop the button collection and access the active state like:

```
<template x-for="button in buttons" :key="button.name" hidden>
    <button type="button" :class="{ 'bg-gray-50': button.active }" x-on:click.prevent="clickButton(button.name)">
        <span x-text="button.label"></span>
    </button>
</template>
````

**Comment by creativiii** [comment] 2022-07-17 17:12
> > Sorry! I must've completely skipped over your comment 😂 Did you figure out a solution to checking if a button `isActive`?
> 
> I have `buttons` attribute in my Alpine component. With this attribute, not only I can give a different set of buttons for each editors but also I can use this to hold the buttons state and update the state by listening to `onUpdate` and `onTransaction` events.
> 
> In the html you can just loop the button collection and access the active state like:
> 
> ```
> <template x-for="button in buttons" :key="button.name" hidden>
>     <button type="button" :class="{ 'bg-gray-50': button.active }" x-on:click.prevent="clickButton(button.name)">
>         <span x-text="button.label"></span>
>     </button>
> </template>
> ```

That's really smart! I'll give it a shot.

**Comment by GregT2207** [comment] 2022-08-09 09:43
Simple solution that worked for me was to just store and reference it in the window.

window.editor = null;
// first thing, outside of setupEditor method

window.editor = new Editor({...
// save it into the window

@click="window.editor.chain().focus()...
// refer to the editor object in the window

**Comment by bdbch** [comment] 2023-02-24 14:14
Since @peterfox added a good note about this to our PHP documentation for Alpine I'd close this issue for now. Hope everyone is happy with that decision. Feel free to reopen if there is still something open to discuss.

**Closed by bdbch** 2023-02-24 14:14 UTC
Labels: bug

**Comment by dipeshmurmu2005** [comment] 2024-06-19 08:09
You can get the easiest integration of tip with laravel livewire you can view blog:
[https://medium.com/@cypercoder/effortless-integration-harnessing-tiptap-editor-with-laravel-livewire-b0fc9fe4d5f1](url)
