### ISSUE TITLE
[Bug]: cannot change style of text from list to block quote

### ISSUE THREAD

**Issue by ajdinproho** [ueberdosis/tiptap#4284] opened 2023-08-03 11:10 UTC
### Which packages did you experience the bug in?

List Item, Tasks

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

If your text is in bullet list, number list or checklist you cannot convert it into block qoute.
The bug is happening in Chrome, Firefox, Edge and Safari.

![ezgif-2-a6cdd984c0](https://github.com/ueberdosis/tiptap/assets/40147450/18923884-4041-4e4f-88c5-0cf2817added)

### What browser are you using?

Chrome

### What did you expect to happen?

The expected behaviour is that the text should be in block quote.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by Slapbox** [comment] 2023-08-04 18:43
Duplicate of #3743

**Closed** 2023-08-04 20:41 UTC
Labels: Type: Bug, Status: New, Category: Pro
