### ISSUE TITLE
[Bug]: TextSelection warning of HorizontalRule extension

### ISSUE THREAD

**Issue by Pareder** [ueberdosis/tiptap#3997] opened 2023-04-30 11:19 UTC
### Which packages did you experience the bug in?

@tiptap/extension-horizontal-rule

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

Actually it is a copy of this issue https://github.com/ueberdosis/tiptap/issues/2846, but it was closed and the issue was not fixed, so I decided to recreate this issue. Try to click on button and open console, there will be a TextSelection warning. It is needed to refactor these lines of HorizontalRule extenstion
- https://github.com/ueberdosis/tiptap/blob/develop/packages/extension-horizontal-rule/src/horizontal-rule.ts#L52
- https://github.com/ueberdosis/tiptap/blob/develop/packages/extension-horizontal-rule/src/horizontal-rule.ts#L59

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/focused-blackburn-7rl1q8?file=/src/App.js

### What did you expect to happen?

No warning is displayed.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by sjdemartini** [comment] 2023-07-18 23:06
This seems to be a duplicate of https://github.com/ueberdosis/tiptap/issues/3003, which is still open.

**Comment by svenadlung** [comment] 2023-08-04 13:12
Duplicate of #3003

**Closed** 2023-08-04 13:12 UTC
Labels: Type: Bug, Status: New, Category: Open Source
