### ISSUE TITLE
getWords() doesnt work when two instances

### ISSUE THREAD

**Issue by rezaffm** [ueberdosis/tiptap#2769] opened 2022-05-09 11:39 UTC
### What’s the bug you are facing?

When I have two instances in vue like:

```vue
<editor v-model="form.content" :shortcut="false"></editor>
<editor  v-model="form.content" :shortcut="false"></editor>
```

Then getWords() doesnt work anymore

### Which browser was this experienced in? Are any special extensions installed?

No no special extensions.

### How can we reproduce the bug on our side?

Load the editor twice and it will stop working

### What did you expect to happen?

Well, that the words would be counted...

### Anything to add? (optional)

Not really, I tried to "key" the instance with some random keys, but that didn't solve the problem.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by rezaffm** [comment] 2022-05-09 18:23
Okay, I got a bit curious and had another look at the situation, I hope you don't mind, if I didn't set up a sandbox, but basically, I just copied your example from here: https://tiptap.dev/api/extensions/character-count

Very simply...I then just add two instances. I tried to "key" them with a uuid, but no luck.

And actually, it is not like the words are not updating at all. Only the second instance updates the first.

```vue
<template>
  <div id="legals-view" class="container">
    {{ content }}
    <h1>Editor</h1>
    <editor
      id="8d51222f-cca7-4d30-8d94-a5643df50849"
      v-model="content"
      key="8d51222f-cca7-4d30-8d94-a5643df50849"
    ></editor>
    {{ content_2 }}
    <editor
      id="8d51222f-cca7-4d30-8d94-a5643df50850"
      v-model="content_2"
      key="8d51222f-cca7-4d30-8d94-a5643df50850"
    ></editor>
  </div>
</template>
<script>
  import { mapGetters } from 'vuex'
  import Editor from '@/admin/test_editor/Editor'

  export default {
    metaInfo: {
      title: 'Legals',
    },
    components: {
      Editor
    },
    data() {
      return {
        content: '',
        content_2: '',
      }
    },
    computed: {
      ...mapGetters([
        'sites'
      ])
    },
    mounted() {
      //
    }
  }
</script>
```

```vue
<template>
  <div v-if="editor">
    <editor-content :editor="editor" :key="uuid" />
    <div class="character-count">
      <br>
      {{ editor.storage.characterCount.words() }} words
    </div>
  </div>
</template>

<script>
  import { Editor, EditorContent } from '@tiptap/vue-2'
  import Document from '@tiptap/extension-document'
  import Paragraph from '@tiptap/extension-paragraph'
  import Text from '@tiptap/extension-text'
  import CharacterCount from '@tiptap/extension-character-count'
  import { v4 as uuidv4 } from 'uuid';

  export default {
    components: {
      EditorContent,
    },
    props: {
      value: {
        type: String,
        default: '',
      },
    },
    data() {
      return {
        editor: null,
        uuid: ''
      }
    },
    watch: {
      value(value) {
        const isSame = this.editor.getHTML() === value

        if (isSame) {
          return
        }

        this.editor.commands.setContent(this.value, false)
      }
    },
    methods: {
      uuidv4: function() {
        return uuidv4()
      }
    },
    mounted() {
      this.uuid = this.uuidv4()
      this.editor = new Editor({
        extensions: [
          Document,
          Paragraph,
          Text,
          CharacterCount
        ],
        content: this.value,
        onUpdate: () => {
          this.$emit('input', this.editor.getHTML())
        }
      })
      console.log(this.editor)
    },
    beforeUnmount() {
      this.editor.destroy()
    },
  }
</script>

<style lang="scss">
/* Basic editor styles */
.ProseMirror {
  > * + * {
    margin-top: 0.75em;
  }
}
.character-count {
  margin-top: 1rem;
  color: #868e96;
}
</style>
```

**Comment by bdbch** [comment] 2022-05-13 23:05
This sounds similar to what https://github.com/ueberdosis/tiptap/issues/2694 describes.

Can you try adding the extension like this:

```js
CharacterCount.configure()
```

**Comment by bdbch** [comment] 2022-05-20 18:50
I'll close this ticket as it seem to be a duplicate of #2694

**Closed by bdbch** 2022-05-20 18:50 UTC

**Comment by rezaffm** [comment] 2022-05-29 10:58
Hi, I can confirm that this "fixed" it. Would have appreciated a comment or so in the documentation but anyhow, thanks for helping me out and keep going, good job!
