### ISSUE TITLE
[Bug]: Mod-z Not Blocked When editor.isEditable Is False

### ISSUE THREAD

**Issue by jan-schweiger** [ueberdosis/tiptap#5547] opened 2024-08-24 08:56 UTC
### Affected Packages

core, react, @tiptap/extension-history

### Version(s)

2.6.6

### Bug Description
1. Edit the content
2. Run editor.setEditable(false)
3. Press CTRL + Z
4. The undo operation is performed

However, this only happens for Undo but not for Redo.

### Reproduce
I was also able to reproduce it by slightly adjusting the minimal setup: https://tiptap.dev/docs/examples/basics/minimal-setup

```
import Document from '@tiptap/extension-document'
import Paragraph from '@tiptap/extension-paragraph'
import Text from '@tiptap/extension-text'
import { EditorContent, useEditor } from '@tiptap/react'
import React from 'react'
import History from '@tiptap/extension-history'

function App() {
  const editor = useEditor({
    extensions: [
      Document,
      Paragraph,
      Text,
      History  // <-- Added History
    ],
    content: "<p>Tiptap content</p>",
  })

  return (
    <div className="App">
      <EditorContent editor={editor} />

      <button onClick={() => editor.setEditable(!editor.isEditable)}>
        Toggle isEdit
      </button>
    </div>
  );
}

export default App;
```

You just need to edit some content and click the button to experience the bug for yourself.

Thank you very much in advance for your help!

### Browser Used

Chrome

### Expected Behavior

Mod + Z shouldn't change the content when the editor is read-only.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by jan-schweiger** [comment] 2024-08-24 08:58
I also tried the following quickfix. But strangely the Mod-z function is only called when the isEditable is true.

```
     History.extend({
        addKeyboardShortcuts() {
          return {
            'Mod-z': () => {
              console.log('Mod-z', this.editor.isEditable);
              return this.editor.isEditable ? this.editor.commands.undo() : false;
            },
            'Mod-Shift-z': () => {
              return this.editor.isEditable ? this.editor.commands.redo() : false;
            },
          };
        },
      }),
```

**Comment by tanja-kovakic** [comment] 2024-08-24 09:00
I can also reproduce the bug. Just tried it out in my application. Can anyone have a look on this one?

**Comment by nperez0111** [comment] 2024-08-26 14:39
Maybe this is a browser default behavior? I wonder if the element is still a contenteditable when editable=false

**Comment by rosenbauerwillbacker** [comment] 2024-08-27 21:32
I can also reproduce the bug.

@nperez0111 In my case, the content is initially set to editable=false. I however change the content programmatically. In this case the everything works fine. CTRL + Z doesn't change the content back. Only, when I make the content editable and then make it read-only again, the bug occurs.

I tried to pinpoint the cause, but my knowledge of the inner workings of tiptap is unfortunately limited. Could maybe someone investigate this issue? This is unfortunately a severe problem for my application. Thank you!

**Comment by jan-schweiger** [comment] 2024-08-30 08:51
Any updates on this one?

**Comment by nperez0111** [comment] 2024-08-30 14:39
Feel free to look into it and contribute a PR fixing it.

**Comment by jan-schweiger** [comment] 2024-08-30 21:58
Thank you @nperez0111. I have already looked into the potential causes but haven't found a solution yet. I will give it another try over the weekend.

**Comment by jan-schweiger** [comment] 2024-09-02 15:08
Unfortunately, I was unable to identify the root cause. As a temporary "fix" you can use the following code to clear the history whenever you programmatically set the editor to read-only again. This is definitely not the best solution, rather a dirty quickfix for production applications.

```
import { history } from '@tiptap/pm/history';

// clear history:
editor.unregisterPlugin('history');
editor.registerPlugin(history());
```

**Comment by Nantris** [comment] 2024-09-28 22:40
I'm finding nothing is blocked since TipTap 2.5.9 when `setEditable(false)` is used

I'm not sure if some particular configuration is required for this to manifest `2.5.8` works and anything above lets all document-modifying events right through. Determined by `git bisect` and confirmed manually - but haven't had time to make a repro yet.

**Comment by Nantris** [comment] 2024-10-02 00:16
@nperez0111 I believe the root cause of this is that a `useEditor` change considers the initial options, but that includes `editable` and if editable is initially `true` but later `setEditable(false)` is called, the `useEditor` setting takes precedence.

Repro: https://codesandbox.io/p/sandbox/tiptap-react-qidlsv

Suspected problem commit: https://github.com/ueberdosis/tiptap/commit/7c8889a2a61c7bc05bac7f0d54ecac1d40e87d94#diff-2e5eb93343b2ec03e98abdd0c8612de5492886ae9a7ddb6b1cdd22d222bb483cR10

**Comment by nperez0111** [comment] 2024-10-02 10:22
Good intuition @Nantris, so `editor.setEditable` is just mutating the options object: https://github.com/ueberdosis/tiptap/blob/33e1305c20699e68cce654ab8d8ee5f36a608374/packages/core/src/Editor.ts#L191

Which in React, will recreate & reapply whenever it needs to switch editor instances like you found (which I firmly believe is the correct behavior and in-line with React's model of completely re-rendering things from scratch).

The tricky thing is that in the case of React recreating the instance, it is unclear when it should actually enforce the value. Like even in your example, you have `editable: true`, should that always apply (and you have to change it from there) or should `setEditable` takes precedence?


So, what I think is probably needed here is that the `editable` option should be copied to an instance variable and `setEditable` can modify that (and [the editable extension can read from that instead](https://github.com/ueberdosis/tiptap/blob/e97630c63927b3c05e75882975ea12c4d364acd3/packages/core/src/extensions/editable.ts#L13)). If `editable` is specified in the `useEditor` options, it will always be respected over the dynamic `setEditable`, but if it is not specified, then `setEditable` would persist somehow (likely needs to be copied from the old editor to the new editor, but I haven't thought this through completely).

Any opinions here? Different approaches?

**Comment by nperez0111** [comment] 2024-10-02 10:24
As for history specifically, I think that all that may be needed is a check here: https://github.com/ueberdosis/tiptap/blob/b941eea6daba09d48a5d18ccc1b9a1d84b2249dd/packages/extension-history/src/history.ts#L58-L63

Which would early exit with false if the editor is not editable. Would be happy to take a PR to fix that, since that is simpler than the issue that @Nantris brought up

**Comment by Nantris** [comment] 2024-10-02 23:04
@nperez0111 thanks for your reply! I'm not sure what the best way would be really, but I can at least share what I believe might  be most intuitive.

In my mind, I guess I was expecting the `editable` in `useEditor` to use the initially set value and then never update again unless `editor.setEditable` is called with a new value. This thinking might be biased by how `useEditor` used to work in older versions of TipTap v2, but I think there's some merit to it. Take a case where maybe a developer want sto call `setEditable` from inside of an extension, or might want to temporarily set it from the terminal for debugging. Then they'd have to entirely avoid setting `editable` in `useEditor`, and I guess this could be achieved by exclusively managing this via calling `editor.setEditable` inside of a `useEffect` but it seems a tad hacky.

Is it possible/reasonable to store the original `editable` value in a ref or something so that it could persist even as the editor is recreated and treat that ref as the single source of truth for the editable state? Any changes to the editable state would then need to be managed via `editor.setEditable`.

Thanks again for the great work @nperez0111 - really appreciate you!

**Comment by Nantris** [comment] 2024-10-16 00:46
Created #5731 to address the original issue here.

**Comment by Nantris** [comment] 2024-10-21 18:53
@guarmo great work! I can't test at the moment, but are we certain that `historyUndo` and `historyRedo` fire consistently on all platforms?

There's some more discussion on this topic here: https://discuss.prosemirror.net/t/native-undo-history/1823/20

**Comment by nperez0111** [comment] 2024-10-22 13:31
@guarmo's change is released with v2.9.0

**Comment by Nantris** [comment] 2024-10-23 02:04
@nperez0111 is there a plan to incorporate [@guarmo's plugin](https://github.com/ueberdosis/tiptap/issues/5547#issuecomment-2426911508) into Tiptap to fix the originally reported issue?

**Comment by Nantris** [comment] 2024-10-23 02:10
Confirming [this aspect of the issue](https://github.com/ueberdosis/tiptap/issues/5547#issuecomment-2387303949) is resolved:  by #5745. Undo still goes through though.

**Comment by nperez0111** [comment] 2024-10-23 08:48
@Nantris between @guarmo and I we decided that it was a little too hacky to incorporate into Tiptap itself. The bug has been there for a long time.

@guarmo was going to open an issue with prosemirror-history to see if we can get this resolved upstream since we identified it to be a 1 line fix in that package

**Comment by Nantris** [comment] 2024-10-23 20:51
Sounds like a good approach.

@guarmo were you planning to make a PR to `prosemirror-history` or just open an issue on the wider `prosemirror` repo? I could open such an issue, but I'm not certain what the PR code would need to look like so I can't do that.

**Comment by guarmo** [comment] 2024-10-24 08:45
@Nantris thanks for the reminder. I have just created a [PR](https://github.com/ProseMirror/prosemirror-history/pull/10) that aims to fix the issue.

**Comment by guarmo** [comment] 2024-10-24 13:03
Alright [PR](https://github.com/ProseMirror/prosemirror-history/pull/10) is merged. You'd need to update `prosemirror-history` to see the changes. Closing this one.

**Closed by guarmo** 2024-10-24 13:03 UTC
Labels: Type: Bug, Category: Open Source

**Comment by jan-schweiger** [comment] 2024-10-27 17:08
Amazing!! Thank you @nperez0111 and @guarmo.
