### ISSUE TITLE
Suggestions demo only works with items with spaces

### ISSUE THREAD

**Issue by klaasgeldof** [ueberdosis/tiptap#932] opened 2021-01-10 16:57 UTC
**Describe the bug**
The 'suggestions' demo does not work with items that do not contain any spaces.

**Steps to Reproduce / Codesandbox Example**
1. Go to the source code of the demo: https://github.com/ueberdosis/tiptap/blob/main/examples/Components/Routes/Suggestions/index.vue
2. Use the exact same code, but remove the space in one of the suggestions, for example change 'Sven Adlung' to 'SvenAdlung'.
3. Type '@' in the editor and choose the item without spaces
4. See the error in the console: 'TypeError: Cannot read property 'nodeType' of undefined'

Fork this or create a new Codesandbox replicating your error
https://codesandbox.io/s/vue-issue-template-forked-s1i2u => type @ and choose the first item (other items work without a problem)

**Expected behavior**
Same behavior as the items with spaces, obviously 😉

**Screenshots**
<img width="466" alt="CleanShot 2021-01-10 at 17 44 27@2x" src="https://user-images.githubusercontent.com/35819/104129614-e8120300-536c-11eb-8483-84c6102fb8d3.png">

**Environment**
 - OS: macOS
 - Browser: Chrome
 - Version: 87
 - Mobile / Desktop: Desktop

**Comment by andreasvirkus** [comment] 2021-01-20 13:32
@Priestch could it be something that's caused by the `getTextBetween` method in the `Suggestions` plugin? That's the latest change for Mentions https://github.com/ueberdosis/tiptap/commit/046babfd3a94222128f08cef653859ab66eaf3cd

**Comment by philippkuehn** [comment] 2021-01-20 13:59
BTW: Today I finished the implementation of the suggestions plugin for tiptap 2. I found a different solution than used in #860. I added a custom `clipboardTextSerializer` so that you can override the text content of nodes. (This is probably only useful for atom nodes like mentions).

So this is definitely fixed in tiptap 2 🙌

**Comment by Priestch** [comment] 2021-01-21 01:12
@andreasvirkus This issue only happens after commit 046babf, and I can not figure out the reason , it seems the doc content is broken after select some user.

**Comment by rosnaib11** [comment] 2021-02-15 14:00
+1

**Comment by scriptcoded** [comment] 2021-03-22 14:09
I can confirm this very odd behavior. @rosnaib11's workaround kind of worked for me, but for some reason I had to prepend the space.
```js
this.insertMention({
  range: this.suggestionRange,
  attrs: {
    id: user.id,
    label: ' ' + user.name
  }
})
```

**Comment by ivy-derm** [comment] 2021-03-22 15:55
One minor caveat with the space fix -- adding spaces anywhere in the suggestions breaks the delete key on my Pixel android phone running Chrome - makes it impossible to delete a suggestion. I haven't investigated further and could just be my phone though. But works fine on iOS.

**Comment by philippkuehn** [comment] 2021-05-05 08:07
this is fixed in v2

**Closed by philippkuehn** 2021-05-05 08:07 UTC
Labels: bug, v1
