### ISSUE TITLE
Vue 3 collaboration is broken, including in Tiptap's own demo

### ISSUE THREAD

**Issue by gustavotoyota** [ueberdosis/tiptap#2891] opened 2022-06-16 18:59 UTC
### What’s the bug you are facing?

Unable to type in editor on Tiptap + Vue 3 + Collaboration.
This error is displayed in the console:
```
Uncaught RangeError: Applying a mismatched transaction
at EditorState.applyInner (index.js:830:19)
at EditorState.applyTransaction (index.js:794:45)
at EditorState.apply (index.js:770:21)
at Editor2.dispatchTransaction (Editor.ts:337:30)
at EditorView.dispatch (index.js:5176:33)
at readDOMChange (index.js:4659:10)
at DOMObserver.handleDOMChange (index.js:4832:81)
at DOMObserver.flush (index.js:4336:18)
at DOMObserver.observer (index.js:4215:26)
```

### Which browser was this experienced in? Are any special extensions installed?

Chrome (PC and Android), Firefox, Edge. No extensions.

### How can we reproduce the bug on our side?

Go to https://tiptap.dev/examples/collaborative-editing and try to type on Vue editor.

Or just follow these steps https://tiptap.dev/installation/vue3 then these https://tiptap.dev/guide/collaborative-editing

### Can you provide a CodeSandbox?

https://codesandbox.io/s/amazing-mclean-wypecq?file=/src/App.vue

Strangely enough it works correctly on Codesandbox. But as soon as I export and run it locally it stops working.
It may give a clue as to why this is happening.

### What did you expect to happen?

Expected to be able to type and collaborate in editor.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment] 2022-06-17 03:10
I'm closing this as it is a duplicate of #2879 

Thanks for your codesandbox and your examples provided. I was able to find the issue - I'll update you in #2879.

**Closed by bdbch** 2022-06-17 03:10 UTC
Labels: bug
