### ISSUE TITLE
Change the prompt of mention to #, which will conflict with Heading later

### ISSUE THREAD

**Issue by Cuimc** [ueberdosis/tiptap#2872] opened 2022-06-11 09:42 UTC
### What’s the bug you are facing?

First of all thank you very much for your tiptap
Sorry, I have a question that I have been dealing with for a long time but can't get it
I changed the prompt of the mention extension to #, but it conflicts with the extension of Heading
I've been investigating myself for a while
so...
I found that enter also triggers the syntax of Markdown，and modify it in this way
That is, I commented this code
`/packages/core/src/InputRule.ts`
![image](https://user-images.githubusercontent.com/64002336/173182343-e35f8a83-df95-4d37-af78-ba3bbeed6c23.png)
Although it works, I don't know how to re-customize this method in my project
so i want to ask for help

i tried：
1. Modify the priority of extensions

### Which browser was this experienced in? Are any special extensions installed?

Google  
no extension installed

### How can we reproduce the bug on our side?

1. Introduce the Heading and mentions extensions
2. then enter # on the first line

### Can you provide a CodeSandbox?

After deleting all the content, enter # and press Enter

https://codesandbox.io/s/wizardly-wiles-od132h?file=/src/components/editor.vue

### What did you expect to happen?

Resolve the conflict between mention and Heading

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by rfgamaral** [comment] 2022-06-13 11:35
This is a duplicate of: https://github.com/ueberdosis/tiptap/issues/2570 (there's a better workaround in there)

**Comment by Cuimc** [comment] 2022-06-13 14:53
But [#2570](https://github.com/ueberdosis/tiptap/issues/2570) doesn't work for me, so I can only find some other solutions to try.
really frustrating

**Comment by rfgamaral** [comment] 2022-06-13 14:59
@Cuimc I'm pretty sure you're missing something. The concept around the workaround is simple: change the mention plugin priority so that is loaded before everything else (including the input rules plugin).

Either way, opening a new issue **with the same problem** doesn't help anyone. This is clearly a duplicate of that same issue, there's no point in having 2 opened. But I'm not a maintainer of this project, so I can't close this anyway.

**Comment by bdbch** [comment] 2022-06-24 12:05
I'm closing this issue as it's a duplicate of #2570

As @rfgamaral suggested you can check out the solutions from the other issue or participate in further discussion there. I'll hop in there as soon as I find time.

**Closed by bdbch** 2022-06-24 12:05 UTC
Labels: bug
