### ISSUE TITLE
(React) Content of nested NodeViews will not render until focus

### ISSUE THREAD

**Issue by WilliamIPark** [ueberdosis/tiptap#1747] opened 2021-08-18 16:13 UTC
**Description**
When nesting NodeViews, the content of the deeper node view will not render until the editor gains focus.

**Steps to reproduce the bug**
1. Go to https://codesandbox.io/s/tiptap-v2-beta-rendering-bug-yfftj
2. Notice no text content in the blue box (field node)
3. Click into the blue box.
4. Content will appear.

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:
* React: https://codesandbox.io/s/tiptap-v2-beta-rendering-bug-yfftj

**Expected behavior**
The text content should be visible on load.

**Environment?**
 - operating system: MacOS
 - browser: Chrome / FireFox / Safari all reproduce the issue.
 - tiptap version: 2.0.0-beta.99

**Comment by WilliamIPark** [comment] 2021-08-18 16:15
Some additional details here, including how I worked around the issue in certain cases, but I've run into a case where the workaround won't suit:
https://github.com/ueberdosis/tiptap/discussions/1675

**Comment by philippkuehn** [comment] 2021-08-24 16:25
I can confirm this issue. It seems to be fixed with this [PR](https://github.com/ueberdosis/tiptap/pull/1470). But since that would be a breaking change, I'll have to take another look.

**Closed** 2021-08-24 20:13 UTC
Labels: bug, v2

**Comment by philippkuehn** [comment] 2021-08-24 20:16
It’s fixed in the latest version of `@tiptap/react`.
