### ISSUE TITLE
Parse nested lists from html

### ISSUE THREAD

**Issue by TNick** [ueberdosis/tiptap#1731] opened 2021-08-15 07:53 UTC
**Description**
Parsing nested html lists results in wrong content.

**Steps to reproduce the bug**
1. Create a nested list in html.
2. Feed it to content parameter.
3. See the result in editor.

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

[![Edit tiptap2-react (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tiptap2-react-forked-d9bl8?fontsize=14&hidenavigation=1&module=%2Fsrc%2FTiptap.jsx&theme=dark)

**Expected behavior**
Nested lists should look like the input data.

**Environment?**
 - operating system: Windows 10
 - browser:chrome, firefox
 - mobile/desktop:desktop
 - tiptap version:2.0.0-beta

**Additional context**
```
<p>Paragraph 1 </p>
<ul>
  <li>list item 1</li>
  <li>
    <ul>
      <li>nested list item 1</li>
      <li>nested list item 2</li>
    </ul>
  </li>
</ul>
```
gets converted into this:
```
{
  "doc": {
    "type": "doc",
    "content": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "Paragraph 1"
          }
        ]
      },
      {
        "type": "bulletList",
        "content": [
          {
            "type": "listItem",
            "content": [
              {
                "type": "paragraph",
                "content": [
                  {
                    "type": "text",
                    "text": "list item 1"
                  }
                ]
              }
            ]
          },
          {
            "type": "listItem",
            "content": [
              {
                "type": "paragraph",
                "content": [
                  {
                    "type": "text",
                    "text": "nested list item 1"
                  }
                ]
              },
              {
                "type": "bulletList",
                "content": [
                  {
                    "type": "listItem",
                    "content": [
                      {
                        "type": "paragraph",
                        "content": [
                          {
                            "type": "text",
                            "text": "nested list item 2"
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
}
```

**Comment by philippkuehn** [comment] 2021-08-15 08:34
duplicate of #118

**Comment by philippkuehn** [comment] 2021-08-15 08:37
oh sorry, didn't see that wrong json. have to look at this later.

**Comment by philippkuehn** [comment] 2021-08-15 09:57
Ok, this is because we define the content for list items as `paragraph block*`. [ProseMirror suggests that](https://github.com/ProseMirror/prosemirror-schema-list/blob/ed6fe6eac112d6e4ecfd92429231cc4f70ee5ffe/src/schema-list.js#L50-L55).

ProseMirror expects a list structure like this:
```html
<p>Paragraph 1 </p>
<ul>
  <li>list item 1</li>
  <li>list item 2
    <ul>
      <li>nested list item 1</li>
      <li>nested list item 2</li>
    </ul>
  </li>
</ul>
```


You can overwrite the content option for list items with `block*` which will fix the parsing of your HTML but after that, some commands like lifting and sinking lists doesn’t work as expected.

Since this is the suggested way of ProseMirror I’ll mark that as *wontfix* for now.

**Closed by philippkuehn** 2021-08-15 09:57 UTC
Labels: bug, v2
