### ISSUE TITLE
Stop using experimental MJS files?

### ISSUE THREAD

**Issue by swilgosz** [ueberdosis/tiptap#597] opened 2020-02-02 17:30 UTC
**Is your feature request related to a problem? Please describe.**

I'm trying to deploy the application with TipTap integrated to Now.sh - but it does not work, because it uses the MJS files which is still an experimental feature.

Related: https://github.com/zeit/now/issues/3337

I feel like this issue is a problem not only for me but for anyone trying to use TipTap in Now.sh - which is probably the best hosting solution for Vue.js/Nuxt.js applications.

**Describe the solution you'd like**

Is there a way (or could be in the near future) - to have a version of the editor which does not use this experimental feature, so I could deploy the app in the same ecosystem I use for all the others?

**Describe alternatives you've considered**

Without that, I'm considering:
- trying to find different hosting solutions for nuxt applications (which is not great, as zeit just rocks)
- trying to find an alternative for TipTap (which is hard, as I need an open-source solution)
- trying to fork the editor and replace named modules... - which is not really an option, as I have not enough knowledge in Vue to do that.

**Additional context**

See the related issues on Zeit/now project:

- https://github.com/zeit/now/issues/3337
- https://github.com/zeit/node-file-trace/issues/80

**Comment by hanspagel** [comment] 2021-01-05 23:46
Is this still an issue? I’m wondering because there doesn’t seem to be much interest here.

I’m closing this for now. If someone is still interested in a solution, please share exact steps to reproduce it and what’s the exception then. That would help me to take a closer look. 🙌

**Comment by swilgosz** [comment] 2021-01-07 08:58
Well, yes. I'm still interested in solving this. I needed to switch to different editor because of that issue.

**Closed** 2021-09-22 22:17 UTC
Labels: feature request, v1
