### ISSUE TITLE
Unexpected behavior when custom inline element moves to/places on begin of line

### ISSUE THREAD

**Issue by Seo-Rii** [ueberdosis/tiptap#2789] opened 2022-05-15 17:08 UTC
### What’s the bug you are facing?

Custom element(created with custom extension) not working correctly if element is inline.
There are two bugs with this.

The first one is that unexpected ```<br>``` tag inserted when I erase all text on line before custom element. After ```<br>``` tag inserted, I cannot insert anything before custom element.

The second one is that cursor place(size) is not correct at begin of the line if first element of line is custom element.

### Which browser was this experienced in? Are any special extensions installed?

Lastest chrome(stable)

### How can we reproduce the bug on our side?

Bug 1 : Place cursor between "abc" and black box.
Press 4 backspaces at there.
Then enter any text. There will be unexpected line break between text and component.

Bug 2 : Place cursor after "abc" and press right arrow.
Then, place cursor before "def" and compare with it.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/dreamy-cookies-0gi61i?file=/src/App.js (Bug 1)
https://codesandbox.io/s/friendly-grothendieck-v41112?file=/src/App.js (Bug 2)

### What did you expect to happen?

Bug 1 : No unexpected ```<br>``` tag inserted.
Bug 2 : Cursor places lower place of line.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment] 2022-06-26 08:22
Hey @Seo-Rii - I think that unexpected `<br />` is coming from a very special edgecase. It happens, whenever you delete a line and the paragraph before is empty with a `<br />` tag inside. When you remove the line your react component is on and move it up one line, the <br /> from before will be prepended to your react node (this is actually expected).

The thing that is not expected is, that you can't really get your cursor back after the <br /> and your custom node. I'll take a look into this to see what is happening.

**Comment by bdbch** [comment] 2022-06-26 08:28
No actually I tried it again and it works as expected. That `<br />` is not caused by Prosemirror but is included in the actual content. Lets say your html looks like this:

```html
<h1>Hello world</h1>
<p><br /></p>
<p><br /></p>
<p>abc<react-component></react-component>def</p>
```

When I now remove the abc and remove the paragraph wrapper by pressing backspace again, the following will happen:

```html
<h1>Hello world</h1>
<p><br /></p>
<p><br /><react-component></react-component>def</p>
```

This is as expected as the `<br />` was already placed there before. Now whenever you do another backspace, or move your cursor one to the left and press DEL, it will look correct again.

See this video:

https://user-images.githubusercontent.com/6538827/175806139-c01e55a9-f847-4621-aecc-dfae4166792e.mp4


Because of the cursor "issue":
I think this is expected cursor placement of html / css and could be solved via CSS. When there is no text in front of the react component, the editor doesn't have a baseline for the cursor, so it's just placing the cursor at the top of the react node - when you then have text around the cursor, the browser will know the text baseline and put the cursor at this baseline.

I'll close this issue for now as it's not a bug but intended HTML.

**Closed by bdbch** 2022-06-26 08:28 UTC
Labels: bug
