### ISSUE TITLE
Custom node view with editable field is not showing content if editor is disabled (not editable).

### ISSUE THREAD

**Issue by dkrusenstrahle** [ueberdosis/tiptap#1320] opened 2021-05-14 21:41 UTC
**Description**
I am using a custom node with editable field and it works fine when editor is enabled but when I disable the editor the content is not shown until I click on the div that should contain the content.

**Steps to reproduce the bug**
1. Add a node that is using editable field
2. Add content to the field
3. Switch editor to disabled (not editable)
4. See if the content shows

**Expected behavior**
Output should be shown when the editor is disabled

**Environment?**
 - operating system: MacOS
 - browser: Chrome, Safari, Edge and Firefox
 - mobile/desktop: Both
 - tiptap version: 2.00-beta 60

**Additional context**
If possible disable editor in demo.

**Comment by sibiraj-s** [comment] 2021-05-17 03:41
I believe this is the same issue as https://github.com/sibiraj-s/ngx-tiptap/issues/7. It is fixed in 1.4.1. You can close this issue if that works.

**Comment by sibiraj-s** [comment] 2021-05-17 03:44
I am not sure if it is a core bug and what I added could a workaround. I tested the same with `@tiptap/react` It seems to be working fine when editable is set to false https://stackblitz.com/edit/react-tiptap-editable. Hence assuming this is an issue with `ngx-tiptap`. I didn't dive too deep, Maintainers can comment.

**Comment by philippkuehn** [comment] 2021-05-17 06:07
Not sure what is going on here. If the issue still exists it would be nice to have a codesandbox reproducing the error.

**Comment by sibiraj-s** [comment] 2021-05-17 07:30
Here it is https://codesandbox.io/s/smoosh-thunder-3srju?file=/src/app/app.component.ts. If the editable field is set as `false`, the `contents` inside the editable component is not rendered until clicking on it. If editable is set as `true`, everything works fine.

**Comment by philippkuehn** [comment] 2021-05-17 09:34
@sibiraj-s I can’t reproduce this for `@tiptap/vue-2` and `@tiptap/react`. So this seems to be a bug in `ngx-tiptap`. Since I don’t have any experience with angular I don’t think I can help here.

**Comment by sibiraj-s** [comment] 2021-05-17 09:41
> So this seems to be a bug in ngx-tiptap

Yeah. I have rolled out a fix few hours back. let's see.

**Closed** 2021-05-20 14:56 UTC
Labels: bug, sponsor 💖, v2
