### ISSUE TITLE
CharacterCount config limit doesn't work correctly

### ISSUE THREAD

**Issue by minhlt-fa** [ueberdosis/tiptap#2245] opened 2021-12-07 11:08 UTC
### What’s the bug you are facing?

I have issue when I use extension CharacterCount

1. When I press Enter, the function editor.getCharacterCount() count character is 2.
2. When I type and reach the limit, then I set the caret in the middle of the text. If I type, the new text will insert and remove the last text

### How can we reproduce the bug on our side?

Issue 1: 
1. Import extension CharacterCount
2. Use editor.getCharacterCount() below the editor to show the character have count like Usage in document https://tiptap.dev/api/extensions/character-count
3. Check charecter

Issue 2:
1. Import extension CharacterCount and set config limit
2. Type text reach to the limit
3. Set caret in the middle of the text
4. Type some text and watch the last text

### Can you provide a CodeSandbox?

https://codesandbox.io/s/character-count-error-qe7yz?file=/src/App.vue

### What did you expect to happen?

I expect in
Issue 1: When I press Enter then character just count 1 instead of count 2
Issue 2: Can not type in the middle of the text if reach the limit

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2021-12-07 11:54
For the future please create a separate issue for each bug.

First issue is a duplicate of https://github.com/ueberdosis/tiptap/issues/1839

**Comment by minhlt-fa** [comment] 2021-12-08 02:20
Yes, I will separate issue for each bug next time. Thank you so much.

**Closed** 2021-12-08 20:26 UTC
Labels: bug
