### ISSUE TITLE
Feature Request: Support for Vuex

### ISSUE THREAD

**Issue by rameezcubet** [ueberdosis/tiptap#216] opened 2019-02-28 14:58 UTC
Currently, it's not possible to plug a vuex store value to the plugin. is there any workaround for this?.

What I did is on "onUpdate" function updated store by a dispatch action. But it's calling too frequently and the other problem is it doesn't take the value automatically. problem is it doesn't have two-way binding. I cant set v-model to it. Please consider it as a feature request.

**Comment by andrew-mark** [comment] 2019-02-28 17:33
You could handle the current content in the component and only send to the store on save. You can also create local history object so if the user wants to cancel what they wrote, you don't have to remove that from the store.

**Comment by rameezcubet** [comment] 2019-03-01 05:09
@andrew-mark i am able to push values to store but how can i set the initial value to store

**Comment by rameezcubet** [comment] 2019-03-01 05:44
Please check this code iam using this in nuxt.js vue
```<script>
import MessageEditorIcon from './MessageEditorIcon'
import { Editor, EditorContent, EditorMenuBubble } from 'tiptap'
import {
  Blockquote,
  BulletList,
  CodeBlock,
  HardBreak,
  Heading,
  ListItem,
  OrderedList,
  TodoItem,
  TodoList,
  Bold,
  Code,
  Italic,
  Link,
  Strike,
  Underline,
  History
} from 'tiptap-extensions'

import { mapGetters } from 'vuex'

export default {
  name: 'message-editor',
  components: {
    EditorContent,
    EditorMenuBubble,
    'message-editor-icon': MessageEditorIcon
  },
  computed: {
    ...mapGetters({
      composeDataMessageContent:
        'message/GET_MESSAGE_CONTENT'
    })
  },
  watch: {
    composeDataMessageContent: function(content) {
//on a second thought i tried to watch to store change and update the editor content whenever the store value changes, but when i call "setContent" function it will trigger "onUpdate" function. so again the action dispatches.
        //this.editor.setContent(content)
    }
  },
  data() {
    return {
      editor: null,
    }
  },
  mounted() {
    this.editor = new Editor({
      extensions: [
        new Blockquote(),
        new BulletList(),
        new CodeBlock(),
        new HardBreak(),
        new Heading({ levels: [1, 2] }),
        new ListItem(),
        new OrderedList(),
        new TodoItem(),
        new TodoList(),
        new Bold(),
        new Code(),
        new Italic(),
        new Link(),
        new Strike(),
        new Underline(),
        new History()
      ],
      onUpdate: ({ getJSON, getHTML }) => {

        this.$store.commit('message/UPDATE_MESSAGE_COMPOSE_MESSAGE', {
          key: 'content',
          data: getHTML()
        })
      },
      content: ''
    })
  },
  beforeDestroy() {
    this.editor.destroy()
  }
}
</script>```

**Comment by andrew-mark** [comment] 2019-03-01 10:11
Loading content from the store into Tiptap is completely fine, im doing it in my app. I would think that if you are overwriting your store content after you've imported it and set the content then theres maybe a race condition that even though you set the content to the imported value the onUpdate function fires and returns the empty document. 

Try; instead of sending to the store onUpdate. Write to a local object instead. This makes better practical sense too, as you only write to the store once. You could do something like this

set up a save button (and cancel? what if the user doesn't want to send to the store what they wrote?)

```<button @click="saveContent">

onUpdate() {
//setup a local copy of the content
this.content = getHTML()
}

saveContent() {
//send to store on save
 this.$store.dispatch('setContentInStore', this.content)
}```

I think this way you won't run into the problem of overwriting what was already in the store.

**Comment by rameezcubet** [comment] 2019-03-01 10:42
@andrew-mark Save button is not in the same component. if it was there is no problem. save button is in my header component. Almost all the sections are break down into independent components and it's data is served from the store.
So if I follow your suggested method:- I have to trigger a "SAVE_BUTTON_CLICKED" event from header-component and intercept it in the editor-component. Then on editor component, I need to put to store and save, right?

**Comment by andrew-mark** [comment] 2019-03-01 11:12
@rameezcubet Yes that should do it.

**Comment by rameezcubet** [comment] 2019-03-01 11:29
Solution would work but is it a suggested way for large chat based application, where I dynamically need to use tiptap? I have to create lots of events right? please let me know your thoughts

**Comment by andrew-mark** [comment] 2019-03-01 13:18
I think more information would be needed to really get an understanding of what your app needs to handle. Im not exactly sure what you mean by dynamically use Tiptap. Will you have multiple instances of Tiptap simultaneously?

**Comment by rameezcubet** [comment] 2019-03-01 14:14
yes

**Comment by Alecyrus** [comment] 2019-03-17 04:29
@rameezcubet  Are you trying to debounce the UPDATE function ?

**Comment by Swalden** [comment] 2019-05-05 06:04
What @Alecyrus is saying is the current solution I have been using. I don't think Vuex should be directly supported inside Tiptap, but perhaps documentation added for the best way to support it.

In the below code note is the text rendered by the editor from Vuex and is passed in via a prop on the parent component. timeout is defined on the Editor component itself. The below means that a vuex dispatch won't be triggered until one second after typing.

onUpdate:
`  onUpdate: ({ getJSON, getHTML}) => {
        // Clear timeout each time a key is pressed
        clearTimeout(this.timeout)
        // Wait one second without input before running update
        this.timeout = setTimeout(() => {
          this.$store.dispatch('updateStoreContent', this.note)
        }, 1000)
      },`

For updating the Editor content whenever Vuex is updated you can watch variable that is assigned the content data from Vuex. I am storing an object in Vuex which is why I have to deep watch below.

`watch: {
    note: {
      handler: function (val) {
        // Compare raw html text to not re-render if already correct
        if (val.text !== this.editor.getHTML()) {
          // Sets editor content when store is updated, and is not already rendered. The above timeout is
          // Important to prevent anything being out of sync.
          this.editor.setContent(val.state)
        }
      },
      deep: true
    }
  },`

**Comment by Alecyrus** [comment] 2019-05-05 06:17
@Swalden I really do NOT recommend you  to call `getHTML`  function frequently (use `watch` etc), which is very expensive when the editor holds a relatively large document.  You should call it only you really need it.  If possible, webworker may be a good choice.

**Comment by Swalden** [comment] 2019-05-05 07:04
@Alecyrus my current use case needs only small documents fortunately.

**Comment by AlexSHoffman** [comment] 2019-09-15 12:08
Duplicate of https://github.com/scrumpy/tiptap/issues/133
OP is basically asking for `v-model` binding so that the editor could automatically change the specified `v-model` value in `data()` or `computed{ }` and set its own content when the the `v-model` changes:

```HTML
<editor v-model="text"/>
```

**Comment by rameezcubet** [comment] 2019-11-26 07:05
https://www.npmjs.com/package/tiptap-vuetify allows v-model so vuex can be used with it. 

can we expect similar implementation in future?

**Comment by hanspagel** [comment] 2020-09-22 18:00
Yes, we’ll try to add v-model support to tiptap 2.

Closing that here, it’s a duplicate of #133.

**Closed by hanspagel** 2020-09-22 18:00 UTC
Labels: feature request
