### ISSUE TITLE
Mention extension listen for keys even dropdown is hidden 

### ISSUE THREAD

**Issue by farin** [ueberdosis/tiptap#2453] opened 2022-01-28 08:34 UTC
### What’s the bug you are facing?

Demo implementation / example only hides dropdown but it still caches key events including submit

### How can we reproduce the bug on our side?

Open demo app https://tiptap.dev/api/nodes/mention

write @ - drop down appears 
(you can type one letter to filter some name or nothing, it deesn't matter)
press ESC - drop down hides
press Enter - mention is inserted

### Can you provide a CodeSandbox?

Example on https://tiptap.dev/api/nodes/mention is sufficient reproduce given scenario.

### What did you expect to happen?

instead inserting mention I would expect just new line to be type
(same as eg, Facebook mentions behave)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2022-01-28 08:36
Yeah, we still need a way to cancel suggestions at all. Duplicate of #214

**Closed by philippkuehn** 2022-01-28 08:36 UTC
Labels: bug
