### ISSUE TITLE
[Bug]: Links open twice when the config is `editable: false`

### ISSUE THREAD

**Issue by jaggy** [ueberdosis/tiptap#4877] opened 2024-02-11 11:51 UTC
### Which packages did you experience the bug in?

extension-link

### What Tiptap version are you using?

2.2.2

### What’s the bug you are facing?

The link opens twice when the clicking a link on an editor with `editable: false` as the Editor settings.

Tested on:
- macOS 14.2.1
- Chrome/Safari/Firefox

### What browser are you using?

Chrome

### Code example

https://github.com/jaggy/tiptap-link-opens-twice-reproduction

### What did you expect to happen?

It should only open one new tab.

### Anything to add? (optional)

When `openOnClick` is set to `false`:

`editable: true`
Doesn't open. Which is correct.

`editable: false`
It opens once.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by culli** [comment] 2024-02-20 17:41
I'm running into this exact case too  When editable == false, then links DO open.  I'm on 2.1.13 and will double check if an upgrade helps.

**Comment by Janus451** [comment] 2024-04-08 09:56
I'm noticing the same issue. Links open once when `editable=true` and twice when `editable=false`. On version 2.2.6.

**Comment by benkroeger** [comment] 2024-04-08 11:42
For some reason, Firefox doesn't 'prevent' the click event when editable (clicking on a link inside a `contenteditable=true` container is usually caught)
I assume that the `openOnClick` option only exists because one wanted to allow links to be clickable while editing - and not to make them clickable at all - which they usually are due to the nature of `<a>` tags.
When the editor is not `editable`, shouldn't click events on `<a>` tags naturally be handled by the browser instead of the editor?

Also, we're currently facing this issue in our codebase as well - only reproducible in Firefox. Works fine in Chrome and Safari

**Comment by benkroeger** [comment] 2024-04-08 12:39
Behaviour across browsers is kind of flaky (sometimes opens one tab, sometimes two).
Seems to be related to some browser security feature
![2024-04-08_14-37-36](https://github.com/ueberdosis/tiptap/assets/7782055/8aa323bc-c116-4cfa-82d0-f49296211a10)

**Comment by benkroeger** [comment] 2024-04-08 14:26
it seems that [prosemirror-view](https://github.com/ProseMirror/prosemirror-view/blob/312660cd965a9ad4e50d1d6d67eefe6a50bc7371/src/input.ts#L383) calls `event.preventDefault()` on the `mouseup` event (in this case because [extension-link](https://github.com/ueberdosis/tiptap/blob/0f41e389b3c7de693fb229550695a682b750d71e/packages/extension-link/src/helpers/clickHandler.ts#L43) returns `true` after opening the link).
Immediately after that, the browser emits a `click` event - which is not handled by `prosemirror-view` nor `extension-link` and thus (when the editor is **NOT** editable --> `contenteditable=false`) the default `click` handler for a `<a>` element in the browser kicks in (link is opened again).

My suggestion is to follow @jaggy 's observation and set `{ openOnClick: false }` so that [extension-link](https://github.com/ueberdosis/tiptap/blob/0f41e389b3c7de693fb229550695a682b750d71e/packages/extension-link/src/link.ts#L206) does not register the 'onMouseUp' handler (via `prosemirror-view` plugin).

Longterm, I think the `clickHandler` from [extension-link](https://github.com/ueberdosis/tiptap/blob/0f41e389b3c7de693fb229550695a682b750d71e/packages/extension-link/src/helpers/clickHandler.ts#L14) should return `false` early if `view.editable !== true`.

@bdbch  @svenadlung 

relates to: https://github.com/ueberdosis/tiptap/pull/5040

**Comment by nperez0111** [comment] 2024-05-24 14:14
Appreciate your feedback here.

@benkroeger to be clear, your suggestion means that we should apply your PR to revert `wheNotEditable` right?

**Comment by benkroeger** [comment] 2024-05-24 14:29
yes. I've created #5040 for that

**Comment by nperez0111** [comment] 2024-05-24 15:09
Should be resolved with: https://github.com/ueberdosis/tiptap/pull/5040

**Closed by nperez0111** 2024-05-24 15:09 UTC
Labels: Type: Bug, Category: Open Source

**Comment by rlatlswo135** [comment] 2024-07-23 01:07
It still seems to happen in @2.5.4 😢
