### ISSUE TITLE
Uncaught RangeError: Adding different instances of a keyed plugin - using CDN Starter Kit

### ISSUE THREAD

**Issue by akagomez** [ueberdosis/tiptap#1473] opened 2021-06-15 05:04 UTC
**Description**
When following the [CDN installation instructions](https://www.tiptap.dev/installation/cdn), I get the error `RangeError: Adding different instances of a keyed plugin` without making any modifications to the example code. 

**Steps to reproduce the bug**
1. Copy/paste the [CDN installation instructions](https://www.tiptap.dev/installation/cdn) into your local server
2. Open the developer tools
4. See the error message in the console

**Expected behavior**
The local implementation should match the [default example](https://www.tiptap.dev/examples/default) page. 

**Screenshot, video, or GIF**

**Environment?**
 - operating system: macOS Mojave 10.14.6
 - browser: Chrome Canary (93.0.4526.0)
 - mobile/desktop: Desktop
 - tiptap version: 2

**Additional context**
I'm new to tiptap and encountered this error using the [CDN installation instructions](https://www.tiptap.dev/installation/cdn) (as others have noted recently in https://github.com/ueberdosis/tiptap/issues/305).  

After poking around a bit in the developer tools I noticed that the `keys` map within `prosemirror-state.js` may not be maintaining state/preventing duplicate keys as intended - because the `starter-kit` is loading multiple versions of the same module. 

Here's a screencast demonstrating what I mean: 

![tiptap-duplicate-plugin-keys](https://user-images.githubusercontent.com/82166/121993772-1360aa00-cd72-11eb-93f6-46a51cd415ba.gif)

Since `createKey("plugin")` is called using both modules - and `keys` isn't shared between them - the incremented `keys[name]` counter is liable to recreate an _existing key_. 

Unfortunately, I'm not familiar with how tiptap gets built so I didn't investigate the module resolution much. But hopefully, this example turns out to be a good jumping-off point for others to troubleshoot.

**Comment by philippkuehn** [comment] 2021-06-15 06:12
duplicate of #1274 

details: https://github.com/ueberdosis/tiptap/issues/1274#issuecomment-833359353

**Closed by philippkuehn** 2021-06-15 06:12 UTC
Labels: bug, v2
