### ISSUE TITLE
Support for 2 Editor modes

### ISSUE THREAD

**Issue by connecteev** [ueberdosis/tiptap#558] opened 2019-12-27 01:55 UTC
Have Support for 2 Editor modes:
Markdown and HTML, similar to the Markdown / WYSIWYG modes seen [here](https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic). 

Btw please see https://github.com/showdownjs/showdown and https://markdown-it.github.io/

**Comment by hanspagel** [comment] 2020-10-19 14:31
Thanks! This is a duplicate of the well discussed #545.

**Closed by hanspagel** 2020-10-19 14:31 UTC
Labels: duplicate, feature request
