### ISSUE TITLE
Unset link doesn't work for links generated automatically

### ISSUE THREAD

**Issue by sviat0slav** [ueberdosis/tiptap#2286] opened 2021-12-16 15:34 UTC
### What’s the bug you are facing?

Method `unsetLink` doesn't remove link mark when creating a link with `autolink` or `linkOnPaste` property

### How can we reproduce the bug on our side?

1. Go to [https://embed.tiptap.dev/src/marks/link/vue/](https://embed.tiptap.dev/src/marks/link/vue/)
2. Paste any url ([https://embed.tiptap.dev/src/marks/link/vue/](https://embed.tiptap.dev/src/marks/link/vue/) for example) or type [https://tiptap.dev](https://tiptap.dev) url
3. Set cursor on pasted url
4. Click on `unsetLink` button

### What did you expect to happen?

Removes a link.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2021-12-16 16:17
duplicate of #2251

**Closed** 2021-12-16 16:18 UTC
Labels: bug
