### ISSUE TITLE
Can't enter if typing something that looks like a mention but isn't a mention

### ISSUE THREAD

**Issue by veesahni** [ueberdosis/tiptap#2417] opened 2022-01-21 20:41 UTC
### What’s the bug you are facing?

If you type something that looks like a mention, but isn't one, you can't click enter afterwards to go to the next line without first adding a space.

### How can we reproduce the bug on our side?

Go to the TipTap mention example: https://tiptap.dev/api/nodes/mention

Type @jem and click enter

### What did you expect to happen?

Enter should go to next line and mention dropdown should be hidden.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2022-01-21 20:51
Duplicate of #214

**Closed by philippkuehn** 2022-01-21 20:51 UTC
Labels: bug
