### ISSUE TITLE
Code Block syntax highlighting cursor issue

### ISSUE THREAD

**Issue by drenther** [ueberdosis/tiptap#375] opened 2019-07-03 21:42 UTC
**Description of the bug**

After adding a line in the Code Block which gets highlighted, if we enter a line break and add a character in the next line and then delete the character an extra `<br/>` seems to get added.

This causes visible layout issues and also messes with the way the cursor movement happens using arrow keys.

This is a very specific case and the GIF tried to explain the exact scenario. This happens in the example as well.

Any ideas as to how to solve this?

**Steps to Reproduce**

1. Go to the Syntax Highlighting example
2. Enter something like `const i = 0;` that can get auto highlighted
3. Enter a line break
4. Type in something in the new line like `f`
5. Now delete the character you just entered in the new line

These steps should reproduce the bug.

**Expected behavior**

The extra `<br/>` must not appear in this case and the cursor movement using arrow keys should work as normal.

**Screenshots**

- Demonstrating the steps to reproduce -
![2019-07-04 03 00 47](https://user-images.githubusercontent.com/12991390/60626387-3e14fa80-9e08-11e9-9c0b-09ad08ed079a.gif)

- The cursor issue caused by this - 
![2019-07-04 03 01 08](https://user-images.githubusercontent.com/12991390/60626381-3b1a0a00-9e08-11e9-8531-be9a20b39df7.gif)

**Environment**

 - OS: macOS
 - Browser: Chrome
 - Version: 75.0.3770.100 (Official Build) (64-bit)

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-21 20:37
![изображение](https://user-images.githubusercontent.com/9306996/61596775-d4bf2500-ac18-11e9-9fc3-fec4e7a27dad.png)
maybe this?

**Comment by drenther** [comment] 2019-08-16 19:56
Found the cause - 

![Tiptap](https://user-images.githubusercontent.com/12991390/63194504-d7812e80-c08d-11e9-876c-1b72908dd65d.gif)

There is an extra `<br>` tag that is being added inside the last `<span>` of the preceding line.

Any idea which piece of code is causing this? Or how to fix it?

**Comment by lpellis** [comment] 2019-08-26 22:42
I also ran into this, I think its a byproduct of how browsers implement trailing newlines in contentedible, it only happens when you add a newline at the end of the code block.  I havent found any workaround though, hope someone here has some ideas..

**Comment by taylormaguire** [comment] 2020-04-09 03:50
Having similar issues in multiple browsers. Curious if there is any progress on this or if anyone has any ideas?

**Comment by ajself** [comment] 2020-11-07 14:30
Same. Reproducible in mobile Safari with the TipTap demo.

**Comment by hanspagel** [comment] 2021-01-07 20:58
This (finally) seems to be fixed with tiptap v2. 👍  Thanks for reporting @drenther!

**Closed by hanspagel** 2021-01-07 20:58 UTC
Labels: bug

**Comment by drenther** [comment] 2021-01-12 10:42
Any idea what exactly fixed this? Or was it a browser bug that got resolved on its own?
