### ISSUE TITLE
[Bug]: Two bubble menus doesn't work as docs suggests

### ISSUE THREAD

**Issue by volnei** [ueberdosis/tiptap#4265] opened 2023-07-29 12:16 UTC
### Which packages did you experience the bug in?

@tiptap/extension-bubble-menu

### What Tiptap version are you using?

2.0.4

### What’s the bug you are facing?

When using two bubble menus I'm facing the follow error:

The code: 
```ts
  BubbleMenu.configure({
    pluginKey: 'floating',
  }),
  BubbleMenu.configure({
    pluginKey: 'floating2',
  }),
```

<img width="1287" alt="image" src="https://github.com/ueberdosis/tiptap/assets/619072/35f7abc2-5b8f-45d4-b941-16bfcc9b630f">

### What browser are you using?

Chrome

### What did you expect to happen?

Two menus works as documentation suggests:

https://tiptap.dev/api/extensions/bubble-menu#multiple-menus

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by RadekHavelka** [comment] 2023-08-03 08:08
same as this? https://github.com/ueberdosis/tiptap/issues/3621

**Comment by bdbch** [comment] 2023-08-03 10:20
Duplicate of #3621

**Closed by bdbch** 2023-08-03 10:20 UTC
Labels: Type: Bug, Status: New, Category: Open Source
