### ISSUE TITLE
addNodeView Doesn't work on link

### ISSUE THREAD

**Issue by castroCrea** [ueberdosis/tiptap#1669] opened 2021-08-01 16:45 UTC
**Description**
I followed the doc, but `addNodeView` doesn't work on Mark.
When we see the name of the props it make sense but in the doc it is not the case.
https://www.tiptap.dev/guide/custom-extensions/#node-views-advanced

I check inside the code 
![image](https://user-images.githubusercontent.com/20707343/127778779-2a47bd3a-c0b5-4b7e-9f45-e9cef2d34c86.png)
You can see that there is a folder on extensions that are node.

**Steps to reproduce the bug**
```
import Link from '@tiptap/extension-link';
import { markInputRule, ReactNodeViewRenderer } from '@tiptap/react';

import { LinkRender } from './LinkRender';


export const CustomLink = Link.extend({
  addNodeView() {
    return addNodeView(LinkRender);
  },
});
```

**Expected behavior**
What is the good props to extend marks ?

**Comment by philippkuehn** [comment] 2021-08-01 17:53
duplicate of #1152

**Comment by castroCrea** [comment] 2021-08-02 07:32
I copy past the wrong link to the doc sorry:
https://www.tiptap.dev/guide/custom-extensions/#node-views-advanced

So let's remove it from the doc no?

**Comment by hanspagel** [comment] 2021-08-03 21:01
I’ll do this

**Closed** 2021-09-16 20:12 UTC
Labels: v2, documentation
