### ISSUE TITLE
backspace on Android devices doesn't remove mention

### ISSUE THREAD

**Issue by ijcnvv** [ueberdosis/tiptap#2638] opened 2022-03-21 17:09 UTC
### How can we reproduce the bug on our side?

Android v11

- open [https://tiptap.dev/api/nodes/mention#usage](https://tiptap.dev/api/nodes/mention#usage)
- put caret to end of any mention
- try to remove any char

### What did you expect to happen?

mention is removed

### Did you update your dependencies?

- [x] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2022-03-25 09:30
Duplicate of #677

**Closed by philippkuehn** 2022-03-25 09:30 UTC
Labels: bug
