### ISSUE TITLE
[Bug]: Insert different nodes using customNode separately 

### ISSUE THREAD

**Issue by shilpa9608** [ueberdosis/tiptap#3920] opened 2023-03-31 07:10 UTC
### Which packages did you experience the bug in?

custom plugin

### What Tiptap version are you using?

2.0.0-beta.113

### What’s the bug you are facing?

How to set content for figcreadit node same as figcaption . Now it showing error multiple content hole

```
import {
  findChildrenInRange,
  mergeAttributes,
  Node,
  nodeInputRule,
  Tracker,
} from "@tiptap/core";

export interface FigureOptions {
  HTMLAttributes: Record<string, any>;
}

declare module "@tiptap/core" {
  interface Commands<ReturnType> {
    figure: {
      /**
       * Add a figure element
       */
      setFigure: (options: {
        src: string;
        alt?: string;
        title?: string;
        caption?: string;
      }) => ReturnType;

      /**
       * Converts an image to a figure
       */
      imageToFigure: () => ReturnType;

      /**
       * Converts a figure to an image
       */
      figureToImage: () => ReturnType;
    };
  }
}

export const inputRegex = /!\[(.+|:?)]\((\S+)(?:(?:\s+)["'](\S+)["'])?\)/;

export const Figure = Node.create<FigureOptions>({
  name: "figure",

  addOptions() {
    return {
      HTMLAttributes: {},
    };
  },

  group: "block",

  content: "inline*",

  draggable: true,

  isolating: true,

  addAttributes() {
    return {
      src: {
        default: null,
        parseHTML: (element) =>
          element.querySelector("img")?.getAttribute("src"),
      },

      alt: {
        default: null,
        parseHTML: (element) =>
          element.querySelector("img")?.getAttribute("alt"),
      },

      title: {
        default: null,
        parseHTML: (element) =>
          element.querySelector("img")?.getAttribute("title"),
      },
    };
  },

  parseHTML() {
    return [
      {
        tag: "figure",
        contentElement: "figcaption",
      },
    ];
  },

  renderHTML({ HTMLAttributes }) {
    return [
      "figure",
      this.options.HTMLAttributes,
      ["figcaption", 0][("figcredit", 0)][
        ("img",
        mergeAttributes(HTMLAttributes, {
          draggable: false,
          contenteditable: false,
        }))
      ],
      ["figcaption", 0],
    ];
  },

  addCommands() {
    return {
      setFigure:
        ({ caption, ...attrs }) =>
        ({ chain }) => {
          return (
            chain()
              .insertContent({
                type: this.name,
                attrs,
                content: caption ? [{ type: "text", text: caption }] : [],
              })
              // set cursor at end of caption field
              .command(({ tr, commands }) => {
                const { doc, selection } = tr;
                const position = doc.resolve(selection.to - 2).end();

                return commands.setTextSelection(position);
              })
              .run()
          );
        },
    };
  },

  addInputRules() {
    return [
      nodeInputRule({
        find: inputRegex,
        type: this.type,
        getAttributes: (match) => {
          const [, src, alt, title] = match;

          return { src, alt, title };
        },
      }),
    ];
  },
});

```

### What browser are you using?

Chrome

### What did you expect to happen?

Need to add separate for figcaption and figcredit . Also we need to edit above nodes content.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment] 2023-03-31 08:10
Hey @shilpa9608

could you format your issue correctly? It's not having a correct title right now and the formatting for the code is also off.

could you upgrade your tiptap version to at least 2.0.0 for now or would this lead to breaking changes on your end?

**Comment by shilpa9608** [comment] 2023-03-31 08:42
Actually I have a small doubt , ie how to insert content   to figcredit node in renderHTML like figcaption node

**Comment by shilpa9608** [comment] 2023-03-31 08:48
> Hey @shilpa9608
> 
> could you format your issue correctly? It's not having a correct title right now and the formatting for the code is also off.
> 
> could you upgrade your tiptap version to at least 2.0.0 for now or would this lead to breaking changes on your end?

**Comment by shilpa9608** [comment] 2023-03-31 08:49
> Hey @shilpa9608
> 
> could you format your issue correctly? It's not having a correct title right now and the formatting for the code is also off.
> 
> could you upgrade your tiptap version to at least 2.0.0 for now or would this lead to breaking changes on your end?

Actually I have a small doubt , ie how to insert content to figcredit node in renderHTML like figcaption node

**Comment by shilpa9608** [comment] 2023-03-31 09:41
Hello  Sir , I need your support for this

**Comment by bdbch** [comment] 2023-03-31 09:55
Hey @shilpa9608 I'm still not really sure what exactly is wrong. Could you create a codesandbox and copy your code in there to share your issue with us?

You can use one of our templates:

https://codesandbox.io/s/tiptap-js-fv1lyo

**Comment by shilpa9608** [comment] 2023-03-31 12:09
> Hey @shilpa9608 I'm still not really sure what exactly is wrong. Could you create a codesandbox and copy your code in there to share your issue with us?
> 
> You can use one of our templates:
> 
> https://codesandbox.io/s/tiptap-js-fv1lyo

sure

**Comment by shilpa9608** [comment] 2023-04-03 06:16
@bdbch I have a custom plugin which I am using to set an image using setImage plugin

on insert the content using this custom plugin inside the tiptap editor, the content structure looks like the below image
![Screenshot from 2023-04-03 11-41-47](https://user-images.githubusercontent.com/106958957/229425694-bb624591-faef-4081-8f3f-2ba511677b6b.png)

But when the content for figcredit and figcaption inside the renderHTML which is set above in the code block is empty in the initial case. I am getting an error as the below image
![Screenshot from 2023-04-03 11-34-29](https://user-images.githubusercontent.com/106958957/229426037-936d4131-c19f-4ac8-b379-e916b281ab7e.png)

My expectation is I must be able to insert figcredit and figcaption node with separate data using setImage

**Comment by shilpa9608** [comment] 2023-04-03 08:11
Hey @bdbch please respond..

**Comment by bdbch** [comment] 2023-04-03 10:06
I know bugs can be annoying - specially when they are introduced by third party code but I'd ask for some patience. Is #3931 also created by you? If so I'd like to close one of the issues (#3931 primarily).

Were you able to create a reproducable example via Codesandbox? 

I tried to create one with the extension you attached here, but it wouldn't work out of the box and I don't have the time to set it up on my own right now.

**Comment by bdbch** [comment] 2023-04-03 10:23
I created a Codesandbox with a working example here.
https://codesandbox.io/s/tiptap-js-fv1lyo?file=/src/index.js

The problem is that Prosemirror **only allows for 1 content hole** - that means you can't have multiple content holes in one node. To solve this, you can create nodes for each element on it's own and then require those nodes in the `Figure` schema.

I'll close this issue for now, let me know if it was helpful.

**Closed by bdbch** 2023-04-03 10:23 UTC
Labels: Status: Requires Feedback, Category: Open Source

**Comment by shilpa9608** [comment] 2023-04-04 10:29
Thank you so much sir @bdbch ..
