### ISSUE TITLE
Table extension: HTMLAttributes are ignored when resizable: true

### ISSUE THREAD

**Issue by cadars** [ueberdosis/tiptap#1766] opened 2021-08-20 13:56 UTC
**Description**

When using the `resizable: true` option, HTMLAttributes are ignored / aren't added.
It might be because a `style` attribute with a min-width is added to the table?

(Additionally, it would be nice if `div.tableWrapper` could get `tabindex="0"` and `role="region"` by default, to [allow for a keyboard accessible scrollable area](https://adrianroselli.com/2017/11/hey-its-still-ok-to-use-tables.html#ResponsiveScroll).)

**Comment by rezaffm** [comment] 2021-08-23 12:43
I can confirm, only a colwidth="213" is added, but no style attribute. While this is not a bug, it would be great if it could be possible to add percent instead of px for the "cellMinWidth" attribute.

**Comment by philippkuehn** [comment] 2021-08-24 15:27
When setting `resizable` to `true`, a node view is rendered. That’s why `HTMLAttributes` within `renderHTML` do not have any effect. But they are still available when exporting content with `editor.getHTML`. Not sure if we can add these attributes on this node view too.

**Comment by rezaffm** [comment] 2021-08-24 16:13
Hi,

Tables actually giving me a hard time (I am trying to migrate from tinymce at the moment).

With tinymce you can also resize the table, but it then adds style attributes to the table.

```html
<tbody>
<tr>
<td style="width: 19.085%;">Kreditbetrag (netto)</td> 
<td style="width: 18.1699%;">Laufzeit (Monaten)</td>
</tr> 
```

I have been playing around with tiptap, the idea would be to have a resizable table that is then "responsive" on the front end (by setting overflow-x to auto... nothing to fancy). However, if I add a table in the editor, in v-model I get the following code on init:

```html
<table class="table-responsive">
<tbody>
<tr>
<th colspan="1" rowspan="1"><p></p></th>
<th colspan="1" rowspan="1"><p></p></th>
<th colspan="1" rowspan="1"><p></p></th>
</tr>
<tr>
<td colspan="1" rowspan="1"><p></p></td>
<td colspan="1" rowspan="1"><p></p></td>
<td colspan="1" rowspan="1"><p></p></td>
</tr>
</tbody>
</table>
```

Once I reseized anything, it looks like this:

```html
<table class="table-responsive">
<tbody>
<tr><th colspan="1" rowspan="1" colwidth="212"><p></p></th>
<th colspan="1" rowspan="1"><p></p></th>
<th colspan="1" rowspan="1"><p></p></th>
</tr>
<tr>
<td colspan="1" rowspan="1" colwidth="212"><p></p></td>
<td colspan="1" rowspan="1"><p></p></td>
<td colspan="1" rowspan="1"><p></p></td>
</tr>
</tbody>
</table>
```

The colwidth attributes were added - I expected that the style attributes were rendered.

Actually, I don't care about tinymce, I would be more interested how to get this working with tiptap. So, is there a "tiptap" way of doing this, or how can we achieve resizable tables in tiptap (that are then made responsive with css styles) in the front end?

**Comment by rezaffm** [comment] 2021-09-21 12:58
Hi Philipp, maybe I am wrong but colwidth="X" is not a valid html element and typically the col width is added by a style attribute, like style="width: X;".

That's at least how tinymce (and the other typical editors) solve this issue.

**Comment by hanspagel** [comment] 2021-12-10 17:20
Thanks for reporting! Our extension basically just a wrapper around the unmaintained prosemirror-tables.

We plan to do a rewrite at some point, but for now this issue is out of scope for us. ✌️

**Closed by hanspagel** 2021-12-10 17:20 UTC
Labels: bug, sponsor 💖

**Comment by mario-donnarumma** [comment] 2023-03-13 10:12
Hello, any eta on this? We're facing this issue in our environment and would be great to have a workaround. In our case, we're trying to add the class attribute on the table by extending it and adding the `addAttributes` method, but it is removed when `resizable` is set to `true`

**Comment by daniel-rivera-captego** [comment] 2023-09-15 09:13
Hello everyone 

I am facing the same problems mentioned above, If there is no official solution, does anybody has a workaround? i really need to add some attributes to the table with `addAttributes` but at the same time i need to set resizable to `true`.

**Comment by arenk** [comment] 2024-02-21 11:30
Still experimenting, but the following seems to work:

**TableView**
- Use the [TableView in this repository](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-table/src/TableView.ts) to create a local copy named CustomTableView.ts
- Adjust the line `export class TableView implements NodeView` to `export class CustomTableView ...`
- Adjust the constructor like this (adding 3 lines that copy the class attribute of the node to the table element)

```
constructor(node: ProseMirrorNode, cellMinWidth: number) {
        this.node = node
        this.cellMinWidth = cellMinWidth
        this.dom = document.createElement('div')
        this.dom.className = 'tableWrapper'
        this.table = this.dom.appendChild(document.createElement('table'))
        this.colgroup = this.table.appendChild(document.createElement('colgroup'))
        updateColumns(node, this.colgroup, this.table, cellMinWidth)
        this.contentDOM = this.table.appendChild(document.createElement('tbody'))

        if (node.attrs.class) {
            this.table.className = node.attrs.class
        }
}
```

**Extend the Table node**
- Import the CustomTableView just created & set via addOptions() -> View  (see [table.ts in this repository ](**url**))
- Add 'class' as a supported attribute via addAttributes()

```
import Table from '@tiptap/extension-table'
import {CustomTableView} from './CustomTableView.ts'

export default Table.extend({

    // @ts-ignore
    addOptions() {
        return {
            HTMLAttributes: {},
            resizable: false,
            handleWidth: 5,
            cellMinWidth: 25,
            // TODO: fix
            View: CustomTableView, /* REPLACED BY CUSTOM_TABLE_VIEW */
            lastColumnResizable: true,
            allowTableNodeSelection: false,
        }
    },

    addAttributes() {
        return {
            ...this.parent?.(),
            class: {
                default: null,
                parseHTML: element => element.getAttribute('class'),
                renderHTML: attributes => attributes.class ? {class: attributes.class} : {},
            },
        }
    },
})
```

It should be straightforward to adjust wrapper attributes as well using `this.dom` in the constructor of the CustomTableView (e.g. tabindex)

**Note:** The TableView is not used in case of resizable: false. It might therefore be more stable to add class names to the table instead of the wrapper (in case of resizable: false, the addAttributes() in CustomTable is sufficient)
