### ISSUE TITLE
Pasting images (HTML parsing) has inconsistent behavior

### ISSUE THREAD

**Issue by kaspnilsson** [ueberdosis/tiptap#2432] opened 2022-01-25 00:39 UTC
### What’s the bug you are facing?

Was *thrilled* to notice that the image extension supports parsing & rendering pasted HTML (`<img src="foo.bar" />`)!

Unfortunately, the behavior seems to only work when you're _just_ pasting an image -- when pasting an entire HTML document that includes images, the images do not parse & render successfully.

### How can we reproduce the bug on our side?

Simple repro steps:

- go to http://docs.new
- Paste in an image ([like this one](https://images.unsplash.com/photo-1642952867267-533b87bea300?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1471&q=80))
- Add some text too, styling doesnt seem to matter
- Visit the live demo for the image extension in another tab: https://tiptap.dev/api/nodes/image#usage
- Copy & paste the image directly from the google doc to the #Usage section, and be impressed that it renders!
- Copy and paste the entire document including some text, and notice the image is now dropped

It seems like this is a supported usecase, as pasting other types of HTML works just fine and persists styling to the extensions (like headers and such)

### What did you expect to happen?

Was expecting to either have to implement this parsing functionality fully myself OR for it to work out of the box -- the fact that the behavior is different is why I think this must be a bug somewhere else.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2022-01-25 08:49
Duplicate of https://github.com/ueberdosis/tiptap/issues/1206

**Closed by philippkuehn** 2022-01-25 08:49 UTC
Labels: bug
