### ISSUE TITLE
Text serialization issue

### ISSUE THREAD

**Issue by hivokas** [ueberdosis/tiptap#2280] opened 2021-12-15 13:20 UTC
### What’s the bug you are facing?

I've noticed an issue with text serialization (specifically with new lines).

### How can we reproduce the bug on our side?

- open https://codesandbox.io/s/tiptap-vue-3-issue-template-tnlpv?file=/src/App.vue;
- check examples below.

### What did you expect to happen?

**Example 1**

If I add this to the editor:

```
Hello
World
```

And then select all content and copy it, I expect the same text to be copied (without empty lines), but here is what's copied instead:

```
Hello

World
```

**Example 2**

If I add this to the editor:

```
Hello



World
```

And then select all content and copy it, I expect the same text to be copied (with 3 empty lines), but here is what's copied instead:

```
Hello

World
```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2021-12-15 14:14
Seems like a duplicate of #775

**Closed by philippkuehn** 2021-12-15 14:14 UTC
Labels: bug
