### ISSUE TITLE
Error "Cannot read properties of null (reading 'matchesNode')" on hot-reload in @tiptap/react

### ISSUE THREAD

**Issue by dcastil** [ueberdosis/tiptap#2380] opened 2022-01-11 13:47 UTC
### What’s the bug you are facing?

I have the case that I want to update the content of the editor when the `content` prop changes. It looks somewhat like this:

```js
function Editor({ content }) {
    const editor = useEditor({
        extensions: [StarterKit],
        content
    })
    
    useEffect(() => {
        editor?.commands.setContent(content)
    }, [editor, content])
    
    return <EditorContent editor={editor} />
}
```

When I use that setup during development, Tiptap throws an error right after hot-reloading, crashing the app:

```
Uncaught TypeError: Cannot read properties of null (reading 'matchesNode')
    at EditorView.updateStateInner (index.es.js:4984:1)
    at EditorView.updateState (index.es.js:4955:1)
    at Editor.dispatchTransaction (tiptap-core.esm.js:3368:1)
    at EditorView.dispatch (index.es.js:5240:30)
    at Object.method [as setContent] (tiptap-core.esm.js:1926:1)
    at Editor.tsx:8:25
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
```

I'm wondering whether `setContent()` must not be used like that or whether this is a bug within Tiptap. 🤔 

### How can we reproduce the bug on our side?

1. Go to https://codesandbox.io/s/tiptap-react-reload-bug-7iqpc?file=/src/App.js
2. Wait until app renders
3. Change comment on line 11 to trigger a hot-reload
4. Error should appear instead of rendered app

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-react-reload-bug-7iqpc?file=/src/App.js

### What did you expect to happen?

No error when calling `setContent()`

### Anything to add? (optional)

I could observe that the component gets un- and re-mounted during a hot-reload. The only difference to a normal mount is that the editor is instantiated during the mounting render already. Probably React keeps that around to not lose its state as Tiptap code wasn't changed. Maybe swapping out the instance after mount causes the issue?

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by dcastil** [comment] 2022-01-11 14:19
Adding the code from the code sandbox here just in case I ever delete it.

<details>
<summary>App.js</summary>

```js
import React, { useEffect, useState } from 'react'
import { useEditor, EditorContent } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'

function Editor({ content }) {
    const editor = useEditor({
        extensions: [StarterKit],
        content,
    })

    // Change this comment to observe errors

    useEffect(() => {
        console.log('mounted', editor)
        return () => console.log('unmounted')
    }, [])

    /**
     * This effect is crucial. There are cases where I want to update the content
     * of the editor when `content` changes. In reality `setContent()` is called
     * only when editor is not focused.
     */
    useEffect(() => {
        if (editor) {
            console.log('updating content')
            editor.commands.setContent(content)
        } else {
            console.log('editor is null')
        }
    }, [editor, content])

    return <EditorContent editor={editor} />
}

function Wrapper() {
    // Simulating content coming from a mutable source.
    // Mutable: Meaning content can change in re-render.
    const [content] = useState('This is a test')

    return <Editor content={content} />
}

export default Wrapper
```

</details>

<details>
<summary>index.js</summary>

```js
import { StrictMode } from 'react'
import ReactDOM from 'react-dom'

import App from './App'

const rootElement = document.getElementById('root')
ReactDOM.render(
    <StrictMode>
        {/* Just to test hot-reloading */}
        <div>Last app reload: {new Date().toLocaleString()}</div>
        <App />
    </StrictMode>,
    rootElement
)
```

</details>

<details>
<summary>package.json</summary>

```js
{
    "name": "tiptap-react-reload-bug",
    "version": "1.0.0",
    "description": "",
    "keywords": [],
    "main": "src/index.js",
    "dependencies": {
        "@tiptap/core": "2.0.0-beta.162",
        "@tiptap/react": "2.0.0-beta.105",
        "@tiptap/starter-kit": "2.0.0-beta.170",
        "react": "17.0.2",
        "react-dom": "17.0.2",
        "react-scripts": "5.0.0"
    },
    "devDependencies": {
        "@babel/runtime": "7.13.8",
        "typescript": "4.1.3"
    },
    "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test --env=jsdom",
        "eject": "react-scripts eject"
    },
    "browserslist": ["defaults", "not IE 11"]
}

```

</details>

<details>
<summary>.env</summary>

```
FAST_REFRESH=true
```

</details>

**Comment by philippkuehn** [comment] 2022-01-12 09:09
Duplicate of https://github.com/ueberdosis/tiptap/issues/1451

I’m still not sure if tiptap can do anything here but there is [this little hack](https://github.com/ueberdosis/tiptap/issues/1451#issuecomment-953348865). Can you give this a try?

**Closed by philippkuehn** 2022-01-12 09:09 UTC
Labels: bug

**Comment by dcastil** [comment] 2022-01-12 10:02
Yes, that indeed fixed it. Thanks! 🙏

**Comment by duhaime** [comment] 2022-01-20 22:49
Any chance this can be patched internally @philippkuehn? I have a feeling others will end up on this thread and the linked issues...

**Comment by deadcoder0904** [comment] 2022-02-08 07:25
yes, same issue when i am trying to re-create a bug in codesandbox. the code is exactly similar to what works in my next.js app

**Comment by xlei1123** [comment] 2022-02-17 11:35
same issue

**Comment by deadcoder0904** [comment] 2022-02-17 13:46
@xlei1123 [this hack](https://github.com/ueberdosis/tiptap/issues/1451#issuecomment-953348865) worked for me too. eg → https://codesandbox.io/s/tiptap-newline-error-kpgm8?file=/src/App.tsx

**Comment by branlok** [comment] 2022-09-09 02:00
Also, got this error, the solution isn't working for me. Error seems to occur when i save resave my 'styled.tsx' related to this component.
```

function Index({ title = "Post Title" }: Props) {
  const editor = useEditor({
    extensions: [StarterKit],
    content: "<p>Leave a Mark!</p>",
  })

  const mutation = useMutation(async () => {
    console.log("ur data was sent")
  })

  return (
    <StyledEditor>
      <div className="wrapper">
        <h1 className="title">{title}</h1>
        <div className="editor-wrapper">
          <EditorContent editor={editor} />
        </div>
      </div>
      <div className="toolset-wrapper">
        <button className="submit-button" onClick={mutation.mutate}>
          Submit
        </button>
      </div>
    </StyledEditor>
  )
}
```

```
Uncaught TypeError: Cannot read properties of null (reading 'matchesNode')
    at EditorView.updateStateInner (index.js:4913:49)
    at EditorView.update (index.js:4868:14)
    at EditorView.setProps (index.js:4882:14)
    at Editor2.createNodeViews (Editor.ts:299:15)
    at PureEditorContent.init (EditorContent.tsx:67:14)
    at PureEditorContent.componentDidMount (EditorContent.tsx:42:10)
    at invokeLayoutEffectMountInDEV (react-dom.development.js:25133:22)
    at invokeEffectsInDev (react-dom.development.js:27351:11)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27327:5)
    at flushPassiveEffectsImpl (react-dom.development.js:27056:5)


The above error occurred in the <PureEditorContent> component:

    at PureEditorContent (https://staqpad.dev/node_modules/.vite/deps/@tiptap_react.js?v=ea150a46:3257:5)
    at div
    at div
    ...
```
