### ISSUE TITLE
Pasting a texte with multiple empty lines removes them

### ISSUE THREAD

**Issue by cnicodeme** [ueberdosis/tiptap#2516] opened 2022-02-10 08:35 UTC
### What’s the bug you are facing?

Hi,

I discovered that when pasting a text that contains multiple empty lines, such as : 
```
Hello



World
```

The resulting HTML in Tiptap is : 

```
<p>Hello</p>
<p>World</p>
```

I've tried looking into the Paragraph extension with no luck, tried to add a paste rule too, but it seems to be caught higher up in the chain.

For information, this happens with the basic set of extensions: Document, Paragraph, Text

And it can be checked on the example at https://tiptap.dev/api/nodes/paragraph

### How can we reproduce the bug on our side?

Paste the following at https://tiptap.dev/api/nodes/paragraph:

```
Hello



World
```

### What did you expect to happen?

The output should be

```
<p>Hello</p>
<p></p>
<p></p>
<p></p>
<p>World</p>
```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2022-02-10 08:42
This is how the ProseMirror parser works: https://discuss.prosemirror.net/t/new-lines-change-when-pasting-and-copying/2157
Duplicate of #775

**Closed by philippkuehn** 2022-02-10 08:42 UTC
Labels: bug
