### ISSUE TITLE
How to add width to Column Cells and Headers on init (Bug or Feature?)

### ISSUE THREAD

**Issue by rezaffm** [ueberdosis/tiptap#1789] opened 2021-08-24 17:41 UTC
I need on my tables the respective widths as "style: width: Xpx" - I have done the following to get it working:

```javascript
const CustomTableCell = TableCell.extend({
  addAttributes() {
    return {
      ...this.parent?.(),
      style: {
        default: null,
        parseHTML: element => {
          return {
            style: element.getAttribute('colwidth'),
          }
        },
        renderHTML: attributes => {
          console.log(attributes)
          return {
            colspan: attributes.colspan,
            rowspan: attributes.rowspan,
            colwidth: attributes.colwidth,
            style: attributes.style ? `width: ${attributes.colwidth}px` : null
          }
        }
      }
    }
  }
})

const CustomTableHeader = TableHeader.extend({
  addAttributes() {
    return {
      ...this.parent?.(),
      style: {
        default: null,
        parseHTML: element => {
          return {
            style: element.getAttribute('colwidth'),
          }
        },
        renderHTML: attributes => {
          return {
            colspan: attributes.colspan,
            rowspan: attributes.rowspan,
            colwidth: attributes.colwidth,
            style: attributes.style ? `width: ${attributes.colwidth}px` : null
          }
        }
      }
    }
  }
})

```

And ... it kind of works. If I add a new table and resize the table, however, only the col width is added to the table cells and heads, but not the style attribute.

For instance, when I first add the table and resize around, that's how the table looks like:

```html
<table class="table-responsive">
  <tbody>
    <tr>
      <th colspan="1" rowspan="1" colwidth="179"><p></p></th>
      <th colspan="1" rowspan="1" colwidth="288"><p></p></th>
      <th colspan="1" rowspan="1"><p></p></th>
    </tr>
    <tr>
      <td colspan="1" rowspan="1" colwidth="179"><p></p></td>
      <td colspan="1" rowspan="1" colwidth="288"><p></p></td>
      <td colspan="1" rowspan="1"><p></p></td>
    </tr>
    <tr>
      <td colspan="1" rowspan="1" colwidth="179"><p></p></td>
      <td colspan="1" rowspan="1" colwidth="288"><p></p></td>
      <td colspan="1" rowspan="1"><p></p></td>
    </tr>
  </tbody>
</table>
```
Great, if I then **reload the page (editor),** it is still the same **until I change any column size,** it then becomes (desired result):

```html
<table class="table-responsive">
  <tbody>
    <tr>
      <th colspan="1" rowspan="1" colwidth="179" style="width: 179px"><p></p></th>
      <th colspan="1" rowspan="1" colwidth="303" style="width: 303px"><p></p></th>
      <th colspan="1" rowspan="1"><p></p></th>
    </tr>
      <tr><td colspan="1" rowspan="1" colwidth="179" style="width: 179px"><p></p></td>
      <td colspan="1" rowspan="1" colwidth="303" style="width: 303px"><p></p></td>
      <td colspan="1" rowspan="1"><p></p></td>
    </tr>
      <tr><td colspan="1" rowspan="1" colwidth="179" style="width: 179px"><p></p></td>
      <td colspan="1" rowspan="1" colwidth="303" style="width: 303px"><p></p></td>
      <td colspan="1" rowspan="1"><p></p></td>
    </tr>
  </tbody>
</table>
```
So, either I chose a stupid way to get the style attribute added - or it is a bug? or am I missing something?

Thank You.

**Comment by philippkuehn** [comment] 2021-08-24 18:49
seems like a duplicate of #1766

**Closed** 2021-08-24 18:49 UTC
Labels: bug, v2

**Comment by rezaffm** [comment] 2021-08-25 05:43
I actually was not sure if it is related or not. Do you think that is something that could be changed? Also, other editors tend to use % instead of px which makes it more flexible. I looked at the code and I have to admit that this is far too complex for me (btw looks like you made a good job…).
