### ISSUE TITLE
Navigate to the start of the paragraph doesn't work if the first node is a mention

### ISSUE THREAD

**Issue by rfgamaral** [ueberdosis/tiptap#2050] opened 2021-10-17 11:55 UTC
### What’s the bug you are facing?

If a suggestion is the first thing on a document, it's impossible to use arrows keys (such as <kbd>Left</kbd>) to navigate to the start of the document (before the mention). Using <kbd>Home</kbd> instead of <kbd>Left</kbd> key works.

### How can we reproduce the bug on our side?

Using the [suggestions demo](https://tiptap.dev/examples/suggestions) on the official website:

* Delete all content
* Type `@ ` and pick the first suggestion
* Try to use the <kbd>Left</kbd> key to navigate to before the mention
   * Observe that you can't
* Try to use the <kbd>Home</kbd> key to navigate to before the mention
   * Observe that you can

### What did you expect to happen?

Both the <kbd>Left</kbd> key and the <kbd>Home</kbd> keys should allow you to navigate to before the mention if the mention is the first thing on the document.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2021-10-17 22:14
duplicate of #1778

**Closed by philippkuehn** 2021-10-17 22:14 UTC
Labels: bug
