### ISSUE TITLE
Cursor disappears in a task list

### ISSUE THREAD

**Issue by ocavue** [ueberdosis/tiptap#1222] opened 2021-04-25 18:26 UTC
**Description**

When a task list item is empty, the cursor in this item will not be shown.

**Steps to reproduce the bug**
1. Go to https://www.tiptap.dev/api/nodes/task-list/
2. Create a new empty task list item
3. Put the cursor at the new task list item 
4. Cursor disappears

https://user-images.githubusercontent.com/24715727/116004736-add82300-a636-11eb-911a-b2d275123721.mov

**Environment?**
 - operating system: macOS 10.15
 - browser: Chrome 90
 - mobile/desktop: desktop
 - tiptap version: if the shields badge in https://www.tiptap.dev/api/nodes/task-list/ is correct, I'm using `@tiptap/extension-task-item@v2.0.0-beta.8`

**Comment by philippkuehn** [comment] 2021-04-25 18:58
duplicate of #1198

**Closed** 2021-04-25 18:58 UTC
Labels: bug, v2
