### ISSUE TITLE
Allow v-model

### ISSUE THREAD

**Issue by 1dnmr** [ueberdosis/tiptap#133] opened 2018-12-13 14:18 UTC
Please allow using of v-model in editor

**Comment by holtwick** [comment] 2018-12-15 09:45
This is probably better done one level higher. Lets say you have a component setting up the TipTap editor. There in the `Editor` setup do:

    editor = new Editor({   
        onUpdate: ({getJSON}) => {
          const state = getJSON()
          this.$emit('input', state) // v-model
    editor.setContent(this.value)

More at https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

**Comment by 1dnmr** [comment] 2018-12-16 07:38
Hi Dirk,

Thank you for your answer. Anyway my idea was make the editor more user-friendly and following the best Vue component building practice. v-model is a one of these practices. Making component that not supported this out of the box is quite weird.

**Comment by holtwick** [comment] 2018-12-16 20:33
I see. This is certainly a good idea following the best practice. 

While working with TipTap I came to the point to decide in which format the editor state should be stored. Instead of serializing to HTML in my case it was better to wrap it into an object like this;

    { api: 1, state: {... } }

`api` would should be incremented in case I need to change the schema or other related stuff. Using a top level object is also good in case I also need to store selections or additional info like comments. All this is then serialized to JSON.

Therefore I would love to see a dual implementation:  1. The current `Editor` approach and 2. the `v-model` one. 

BTW, keep up the great work. This is an awesome project!

**Comment by motatoes** [comment] 2018-12-23 09:32
@holtwick's solution worked well for me. Ofcourse I had to create a prop called `value` inside the component. But I needed to add a watcher for the `value` prop in order to account for data changes in the parent component (for example, I was fetching data with Ajax and setting the parent value):

```
  props: ['value'],
  data: {
  },
  watch: {
    value (newValue) {
      this.editor.setContent(this.value)
    }
  }


```

**Comment by laurensiusadi** [comment] 2019-04-13 08:09
Here's how I did it.
This it my Editor component.
```
props: [ 'value' ],
data() {
  return {
    editor: null,
  }
},
mounted() {
  this.editor = new Editor({
    extensions: [],
    ],
    onUpdate: ({ getHTML }) => {
      this.$emit('input', getHTML())
    },
    onBlur: ({ event }) => {
      this.$emit('input', event.target.innerHTML)
    }
  })
  this.editor.setContent(this.value)
},
watch: {
  value (val) {
    // so cursor doesn't jump to start on typing
    if (val !== this.editor.getHTML()) {
      this.editor.setContent(val)
    }
  }
}
```
I use it on its parent like this
```
<editor v-model="note.content"/>
```

Works perfect for me.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-24 22:35
Bad solution. Double call when you gonna type something, watch gonna be triggered, your check's is terrible. `    if (val !== this.editor.getHTML()) {` try to itterate on 1 million symbols.

**Comment by laurensiusadi** [comment] 2019-07-25 00:50
> 
> 
> Bad solution. Double call when you gonna type something, watch gonna be triggered, your check's is terrible. ` if (val !== this.editor.getHTML()) {` try to itterate on 1 million symbols.

Any suggestions how I can improve that?

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-25 16:46
Idk anything 'bout your case.

But im using it like this. With vuex.
![изображение](https://user-images.githubusercontent.com/9306996/61892411-cb85cf00-af1c-11e9-86e7-10bf652043bc.png)
![изображение](https://user-images.githubusercontent.com/9306996/61892482-f40dc900-af1c-11e9-9086-6e4aa715dc2d.png)
![изображение](https://user-images.githubusercontent.com/9306996/61892573-28818500-af1d-11e9-849d-4bbcf95038a9.png)

https://github.com/scrumpy/tiptap/issues/155#issuecomment-514826957 - more about this.

**Comment by estani** [comment] 2019-08-26 08:35
@laurensiusadi 
That didn't work for me an makes little sense imo. The problem is that the editor changes the value too, via $emit, so you have just tell apart what was the source of the change, and not the change itself.
what I did was to mark the editor change:

```js
  props: ["value"],
  data() {
    return {
      editor: null,
      editorChange: false
    };
  },
  mounted() {
    this.editor = new Editor({
      onUpdate: ({ getHTML }) => {
        this.editorChange = true;
        this.$emit("input", getHTML());
      },
      content: this.value,
      extensions: [/* ... */]
    });
  },
  beforeDestroy() {
    if (this.editor) this.editor.destroy();
  },
  watch: {
    value(val) {
      if (this.editor && !this.editorChange) {
        this.editor.setContent(val, true);
      }
      this.editorChange = false;
    }
  }
```
Not sure if there's a better way, but this works with vuex

**Comment by BrianHung** [comment] 2019-10-13 07:27
Is there a way to use `v-model` on a custom Node instead of entire editor? For example, with [title.js](https://github.com/scrumpy/tiptap/blob/master/examples/Components/Routes/Title/Title.js), can I bind the content within `['h1', {id: 'title'}, 0]` with `document.title`? I'm a bit new to Vue and TipTap.

**Comment by Ravikc** [comment] 2019-10-28 16:58
I just came across this library and I must say that it's amazing. I was just going through all the issues to see if I can use it in my project and this issues seems very critical to me. I just wanted to confirm if there is anyone working on this issue. I could start looking into it if no one else is already working on it.

Once again, thanks for this awesome editor.

**Comment by laurensiusadi** [comment] 2019-10-29 04:29
@Ravikc I'm not sure if this is a big issue, since it works okay for me now. But if you want to start looking into it, that would be awesome!

**Comment by rameezcubet** [comment] 2019-11-26 07:04
https://www.npmjs.com/package/tiptap-vuetify worked this out

**Comment by laurensiusadi** [comment] 2019-11-27 09:53
I'm gonna rewrite the code from tiptap-vuetify here in JS (they're in TS)

```javascript
  props: ["value"],
  data() {
    return {
      editor: null,
      emitAfterOnUpdate: false
    };
  },
  mounted() {
    this.editor = new Editor({
      onUpdate: ({ getHTML }) => {
        this.emitAfterOnUpdate = true;
        this.$emit("input", getHTML());
      },
      content: this.value,
      extensions: [/* ... */]
    });
  },
  beforeDestroy() {
    if (this.editor) this.editor.destroy();
  },
  watch: {
    value(val) {
      if (this.emitAfterOnUpdate) {
        this.emitAfterOnUpdate = false
        return
      }
      if (this.editor) this.editor.setContent(val)
    }
  }
```
Pretty similar to @estani code
So I just copied that code above and replace the variables from https://github.com/iliyaZelenko/tiptap-vuetify/blob/master/src/components/TiptapVuetify.vue

Haven't test this yet

**Comment by A-d-o-n-i-s** [comment] 2020-04-13 22:07
> ```
> this.editor.setContent(val, true);
> ```

You must set `true` to `false` to avoid re-emitting editor.onUpdate()... and burning CPU cycles needlessly, just like the tiptap-vuteify code does. And thanks for posting that one! It works well.

**Comment by alloself** [comment] 2020-04-27 11:36
With that i get problem with carret position lag,anyone get same?

or how to resolve it better?

**Comment by igalil** [comment] 2020-06-08 13:33
Hi everyone,

**Super simple solution found ✌️ 😄** 

While I was applying a `v-model`, my side effect was the cursor that loses it's position because of the `setContent()`. But basically there is no need for `setContent` and `watch()`.

Assuming that the prop `value` and the event `input` are set properly, you only need to move the `new Editor({...})` in a `this.$nextTick()` (generally in the `mounted()` hook.

In my case:
```js
props: {
  value: { type: String, required: true },
},
data() {
  return {
    editor: null,
  }
},
mounted() {
  this.$nextTick(() => {
    this.editor = new Editor({
      extensions: [...],
      content: this.value,
      onUpdate: this.yourEventEmitFunctionHere,
    });
  });
}
methods: {
  yourEventEmitFunctionHere(updatedValue) {
    this.$emit('input', updatedValue.getHTML());
  },
},
```

I hope it works for you... 🤞

**Comment by hanspagel** [comment] 2020-08-11 12:41
Thanks for sharing the solutions! ❤️

I’m closing this here. I think we’ll provide support for it in tiptap 2 (or provide a wrapper component).

**Closed by hanspagel** 2020-08-11 12:41 UTC
Labels: feature request

**Comment by arifikhsan** [comment] 2020-09-24 12:05
to use custom editor wrapper like this, write this in the parent component

```vue
 <custom-editor :value="detail" v-on:input="detail = $event" />
```

*detail* as props in *value*

**Comment by laurensiusadi** [comment] 2020-11-23 07:07
@alloself 
Here's my final editor for now. By far the best implementation for my use case.

**Note**: This works with `v-model` but needs an `id` to be watched instead of `value` itself.
We need to add watch on `id` for `setContent`, or it won't change the editor's `value` when you load a different content without destroying the component, since the editor gets its `content` on `mounted`.

```javascript
  props: ["value", "id"],
  data() {
    return {
      editor: null
    };
  },
  mounted() {
    this.editor = new Editor({
      content: this.value,
      onUpdate: ({ getHTML }) => {
        this.$emit("input", getHTML());
      },
      extensions: [/* ... */]
    });
  },
  beforeDestroy() {
    if (this.editor) this.editor.destroy();
  },
  watch: {
    id() {
      if (this.editor) {
        this.editor.setContent(this.value, false)
      }
    }
  }
```

I removed `setContent` on watch `value`, so cursor doesn't jump when we're typing because of content change. There's no need to get update from `value`, since you already updating the editor content while typing.

The `onUpdate` function will keep firing while typing, then the parent component will keep saving the input to API with 500ms `debounce`. Note that I use real-time socket for this, haven't tested this with normal non real-time setup.

**Comment by bcorcoran** [comment] 2021-01-11 23:39
@laurensiusadi 

You can also just use the key attribute on your component, that way when the editor opens it will detect a different key and force an update.

**Comment by laurensiusadi** [comment] 2021-01-15 03:11
> 
> 
> @laurensiusadi
> 
> You can also just use the key attribute on your component, that way when the editor opens it will detect a different key and force an update.

I should've done that! Thanks!

**Comment by Niaz1374** [comment] 2021-05-11 09:47
I'm getting getHTML is not a function error constantly by this way

**Comment by Niaz1374** [comment] 2021-05-12 04:46
@hanspagel I'm using tiptap 2
Thank you

**Comment by Niaz1374** [comment] 2021-05-26 09:56
That worked for me like this
```
export default {
  name: "Editor",
 
components: {
   EditoerContent    
 },

mounted() {
    this.editor = new Editor({
        extensions: [
            Document,
            CustomParagraph,
            Text,
            Mention.configure({
                HTMLAttributes: {
                    class: "mention"
                },
                suggestion: {
                    items: query => {
                        query;
                        var self = this;
                        const search_user = new crud(
                            "/chat/mention/" + query
                        );
                        search_user.get_all_data(true, false, data => {
                            self.users = data.data;
                        });
                        return this.users.filter(item =>
                            item.name
                                .toLowerCase()
                                .startsWith(query.toLowerCase())
                        );
                    },
                    render: () => {
                        let component;
                        let popup;
  
                        return {
                            onStart: props => {
                                component = new VueRenderer(MentionList, {
                                    parent: this,
                                    propsData: props
                                });
  
                                popup = tippy("body", {
                                    getReferenceClientRect:
                                        props.clientRect,
                                    appendTo: () => document.body,
                                    content: component.element,
                                    showOnCreate: true,
                                    interactive: true,
                                    trigger: "manual",
                                    placement: "bottom-start"
                                });
                            },
                            onUpdate(props) {
                                component.updateProps(props);
  
                                popup[0].setProps({
                                    getReferenceClientRect: props.clientRect
                                });
                            },
                            onKeyDown(props) {
                                return component.ref?.onKeyDown(props);
                            },
                            onExit() {
                                popup[0].destroy();
                                component.destroy();
                            }
                        };
                    }
                }
            })
        ],
        onUpdate() {
            // send the content to an API here
            self.text = this.getJSON();
        }
    });
 }
}
```

**Comment by JahnoelRondon** [comment] 2023-06-26 23:56
ok now how do you do this in react...
