### ISSUE TITLE
[Bug]: editor.commands.setCustomNode({ color: 'blue' }) 

### ISSUE THREAD

**Issue by afan0228** [ueberdosis/tiptap#4070] opened 2023-05-24 08:38 UTC
### Which packages did you experience the bug in?

@tiptap/core

### What Tiptap version are you using?

@tiptap/vue-2

### What’s the bug you are facing?

this.editor.commands.setCustomNode({ color: 'blue' }) 

renderHTML({ HTMLAttributes,node }) {
    console.log(node.attrs.color); undefined？？？
    return ['custom-node', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), 0]
  },

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/busy-violet-lzjig7?file=/src/components/Editor.vue

### What did you expect to happen?

this.editor.commands.setCustomNode({ color: 'blue' }) 

<custom-node color="blue">Hello, World!</custom-node>

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by C-Hess** [comment] 2023-06-24 21:39
It's not very clear what your issue is. Is this an issue with `Node.create`?

**Comment by bdbch** [comment] 2023-06-25 00:32
@afan0228 Could you please describe your issue in words? It's hard to understand what you want or what the issue is.

**Comment by svenadlung** [comment] 2023-08-04 13:54
@afan0228 closing for now. Let us know if this issue still persists.

**Closed by svenadlung** 2023-08-04 13:55 UTC
Labels: Type: Bug, Status: New, Category: Open Source
