### ISSUE TITLE
Cannot select inline node at the end of a line or document

### ISSUE THREAD

**Issue by Billiam** [ueberdosis/tiptap#2690] opened 2022-04-07 21:54 UTC
### What’s the bug you are facing?

Tiptap does not support selecting inline nodes with the mouse when dragging from right to left, if the node occurs at the end of a line (or is the only element on the line).

Selecting from left-to-right works, as does right-to-left _if_ the node is not at the end of the line.

Oddly, if the cursor is very slightly inside the node on mouse down, selection works as expected (see gif), but only for non-draggable nodes.

![tiptap-selection](https://user-images.githubusercontent.com/242008/162326170-76818e92-8ff5-42c9-9fd0-e76e6e5e465a.gif)

### How can we reproduce the bug on our side?

1. Visit https://tiptap.dev/api/nodes/emoji
2. Insert an emoji at the end of a line
3. Try to select the emoji with the mouse, beginning at the right side of the emoji and dragging to the left.

### Can you provide a CodeSandbox?

https://tiptap.dev/api/nodes/emoji

### What did you expect to happen?

Element should be selected, the same way it is if element is not at the end of the line.

### Anything to add? (optional)

This issue _does not_ occur in Prosemirror:
 
https://prosemirror.net/examples/dino/

![prosemirror-selection](https://user-images.githubusercontent.com/242008/162326534-63108b58-c6a4-4bc9-81d4-e2030c00bd98.gif)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by scottsidwell** [comment] 2022-04-08 00:12
Having a look into this, it appears this behaviour is caused by the `ProseMirror-separator` node that is inserted by ProseMirror and custom styles Tiptap has applied to it. 

Specifically, setting `width: 1px` on `ProseMirror-separator` appears to trigger this behaviour in Chrome's content-editable (I couldn't reproduce the original bug on Safari or Firefox). This was introduced in https://github.com/ueberdosis/tiptap/commit/0e94afe42a5c15a47698152b3bc88e6bc4f8c01f. Demo of this being the culprit below:

https://user-images.githubusercontent.com/38820281/162338901-5170b9b2-68e1-450b-9305-ed88cb80b2da.mov

Perhaps @philippkuehn can weigh in with what styling the above commit was trying to solve; to work out if it's safe to revert - or to hunt around for CSS that won't cause this conflict :)

**Comment by Billiam** [comment] 2022-04-10 18:38
Thanks! I was able to work around it by overriding the width, and also removing any right-side margin from my nodes for the same reason.

**Comment by Billiam** [comment] 2022-04-11 06:00
I believe there's a related issue where the cursor will not appear after an inline node, at the end of a line, if the node has been wrapped in a mark like bold or italic, ex:

```html
<p>
  <bold><custom-inline-node></custom-inline-node></bold>
  <img class="ProseMirror-separator">
  <br class="ProseMirror-trailingBreak">
</p>
```

This also occurs in TipTap, but not in Prosemirror.

**Comment by rfgamaral** [comment] 2024-08-19 20:48
@nperez0111 This is marked as fixed on the release notes, but the still is still opened.

**Comment by nperez0111** [comment] 2024-08-19 21:11
Sorry yea need to be better on closing issues. It is resolved

**Closed by nperez0111** 2024-08-19 21:11 UTC
Labels: Type: Bug
