### ISSUE TITLE
"Can not convert <> to a Fragment" error happening in newest release

### ISSUE THREAD

**Issue by Alessio-17** [ueberdosis/tiptap#2347] opened 2022-01-04 15:09 UTC
### What’s the bug you are facing?

I've been using tiptap with Skypack CDN for a few days with no problems. A few hours ago, after the release of `core@2.0.0-beta.160` I started seeing the following error when pressing enter.

`Uncaught RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)`

I tried reverting to the previous version of the core package and the problem disappeared, so it's definitely a problem related to the latest upgrade.

### How can we reproduce the bug on our side?

1. Import the latest core package from skypack
2. Press enter when writing in the editor

### What did you expect to happen?

When pressing enter I expect no errors and the creation of a new paragraph, which is what used to happen before the latest upgrade

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2022-01-04 15:12
duplicate of #1537

**Closed** 2022-01-04 15:13 UTC
Labels: bug
