### ISSUE TITLE
Svelte REPL from docs does not load

### ISSUE THREAD

**Issue by nokola** [ueberdosis/tiptap#1450] opened 2021-06-10 15:08 UTC
**Description**
Opening the Svelte REPL from the official docs shows "process is not defined" error.

**Steps to reproduce the bug**
1. Go to https://www.tiptap.dev/installation/svelte/#take-a-shortcut-svelte-repl-with-tiptap
2. Click on [Svelte REPL with tiptap](https://svelte.dev/repl/798f1b81b9184780aca18d9a005487d2?version=3.31.2)

Expected: all OK
Actual: "process is not defined" error on bottom of screen

**Screenshot, video, or GIF**
![image](https://user-images.githubusercontent.com/6869225/121549679-ed7a8480-c9c2-11eb-892b-715a186e5905.png)

**Comment by philippkuehn** [comment] 2021-06-10 17:29
duplicate of #1333

**Closed** 2021-06-10 17:29 UTC
Labels: bug, v2
