### ISSUE TITLE
v2.0.0-beta.205 breaks strict package managers (monorepos)

### ISSUE THREAD

**Issue by myovchev** [ueberdosis/tiptap#3497] opened 2022-12-06 10:35 UTC
### What’s the bug you are facing?

Since v2.0.0-beta.205 (introduced day before this issue is posted) `prosemirror-*` packages are refactored as `peerDepdendencies` in all tiptap packages, while before that they are `dependecies`. This IMHO is a very bad move and relies on the default `npm` behavior to resolve peerDependencies, but it breaks the work of good folks like `pnpm`, `rush`, etc that are trying to bring package management to a better place. All those are not resolving auto-magically the peerDeps but are expecting the developer to reference them explicitly. 

To understand why this is bad, I was forced to add to my `rush` monorepo the following dependencies on an application level in order to resolve failing builds:
```json
    "prosemirror-commands": "^1.3.1",
    "prosemirror-keymap": "^1.2.0",
    "prosemirror-schema-list": "^1.2.2",
    "prosemirror-dropcursor": "1.5.0",
    "prosemirror-gapcursor": "^1.3.1",
    "prosemirror-history": "^1.3.0"
```
The actual dependency depth to `@tiptap/*` and related with the failing build packages:
```
app/
   apostrophe/
       @tiptap/vue-2
       @tiptap/extension-highlight"
       @tiptap/extension-link"
       @tiptap/extension-placeholder"
       @tiptap/extension-text-align"
       @tiptap/extension-text-style"
       @tiptap/extension-underline"
```
The ApostropheCMS is internally building (Admin UI) `@tiptap/vue-2` and extensions in their own build pipeline (webpack) totally independent from the application - you can think of the package `apostrophe` as a library (sort of). This change forces the ApostropheCMS team to introduce basically all `prosemirror-*` as direct dependencies in order to not break applications using different than `npm` (stricter) package manager. This being their responsibility (or any other library implementing tiptap) makes no sense to me.

### Which browser was this experienced in? Are any special extensions installed?

Any

### How can we reproduce the bug on our side?

Install an `apostrophe` application in a Rush monorepo. Generally the problem can be observed if `@tiptap/*` packages are dependencies of root application dependency and the packages are installed via pnpm or rush (I'm sure it breaks a lot more monorepo tools as well).

### What did you expect to happen?

Convert the unnecessary peerDependencies back to dependencies.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [x] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment] 2022-12-06 23:55
Hey, just a heads up on this.

We moved to `peerDependencies` because there were a lot of version issues in the past specially with the `prosemirror-state` package which would lead to duplicate plugin key errors and JSON id errors on runtime.

We tried to resolve this a few weeks ago by fixing prosemirror versions inside the packages as dependencies but the issue still popped up when users were also adding their own prosemirror versions into their projects.

We'll discuss in the team tomorrow what we're going to do with those issues. One thing would be to go back to prosemirror-deps in each extension where they're needed and keep the peerDependency for `@tiptap/core` only.

I'll update this issue when we talked about this. Thanks for your patience

**Comment by myovchev** [comment] 2022-12-07 10:11
@bdbch Thanks for the quick response and the additional info. We were able to temporary resolve the situation and our builds are working again.

One suggestion though - even if `@tiptap/core` only introduces peer dependencies (thus the same applies to `@tiptap/vue-2`) the app developers will end up with the same problem. I fully understand that you (and we all) fight a bad legacy design decisions of `npm`. A good compromise would be an official notifications for a breaking change from your side after your final decision about the peer deps and before the corresponding release implementing it. This would ensure all vendors implementing the library can react and adapt dependencies based on your recommendation beforehand. Breaking change on a beta channel is not exactly semver compliant but in this edge case and with the appropriate communication is an acceptable solution.

**Comment by bdbch** [comment] 2022-12-07 11:11
We had a quick talk this morning but were a bit time-capped. While we really don't like the experience right now (in terms installing all prosemirror-* deps on your own when using pnpm / yarn) we believe it's kind of the right move.

We'll have another talk later where we'll see we can improve this. What we can make sure for now is that we'll add better documentation for a change like this, for example inside our release note + add new installation instructions to our docs **if** the peerDependencies stay.

In the end we'll need to make a decision between:

A. Making sure the installation is easy and uncomplicated but could introduce version clashes with prosemirror as prosemirror is very sensitive with multiple prosemirror versions being loaded which would need some kind of info for Tiptap devs on how to resolve those issues somehow

or

B. Making sure Tiptap works on it's own and prosemirror needs to be provided by the devs themselves to make sure only one source of truth exists for prosemirror which would lead to a worse setup when it comes to installing and setting up Tiptap which we could and should cushion via better documentation and upgrade guides / notes.

---

I'll come back to the issue later with more info

**Comment by coader** [comment] 2022-12-09 11:09
so now we need to add those peer dependence manually?

![image](https://user-images.githubusercontent.com/3700498/206689283-e0746c1d-68fe-45ab-a73c-6f8f48fbd554.png)

**Comment by tmikaeld** [comment] 2022-12-09 11:32
> so now we need to add those peer dependence manually?
> 

Not if you install it with npm, since it takes care of peer dependencies

**Comment by coader** [comment] 2022-12-09 12:24
I downgrade to 205 or 2.04 it also throw error, because the starter-kit use the latest core:
![image](https://user-images.githubusercontent.com/3700498/206701948-be04cb26-f52e-4d28-a595-7eb328f3e29d.png)

**Comment by coader** [comment] 2022-12-09 12:40
I have to add those in packages and it can run
![image](https://user-images.githubusercontent.com/3700498/206704619-8b74e00f-ea13-426f-b7c1-90187a6f1ce5.png)

 but it still has error:
![image](https://user-images.githubusercontent.com/3700498/206704579-95f47a47-e5fd-4bb2-9a0d-c0eeca3059fd.png)

**Comment by myovchev** [comment] 2022-12-09 14:45
The peerDependencies should be auto-resolved when using npm v7+ and not providing the `--legacy-peer-deps` flag. The pnpm package manager has a dedicated option for auto resolving peer deps. I'm not aware what's the situation with yarn. RushJS configured with npm v7+ fails to resolve the newly introduced prosemirror-* peer deps but this seems to be a rush related problem. 

@bdbch node v14 comes with npm v6 by default. This results is peer deps not being resolved. The easy solution is to explicitly update npm to e.g. v8. This fact might generate a number of failed builds and increased support effort so clearly mentioning it in the docs sounds a wise move. Apostrophe CMS will add notes on that matter in the upcoming release.

**Comment by bdbch** [comment] 2022-12-10 19:37
We added information about the peerDeps in our installation guide in the docs:
https://tiptap.dev/installation#1-install-the-dependencies

But I'm also working on a better solution right now that should help out with those long install lines for Tiptap since our team also doesn't really like the current approach.

What we're working on is a meta package like `@tiptap/prosemirror` that you can install to automatically import all required prosemirror dependencies. in combination, you could also access prosemirror exports via `import { EditorState } from '@tiptap/prosemirror/state`.

I'm not 100% done as I have to do a bit of an overhaul on our build scripts to separate that build step from the other packages.

**Comment by bdbch** [comment] 2022-12-10 19:38
> so now we need to add those peer dependence manually?
> 
> ![image](https://user-images.githubusercontent.com/3700498/206689283-e0746c1d-68fe-45ab-a73c-6f8f48fbd554.png)

Yes for now. As @myovchev explained this is how for example yarn does package resolving for peer deps.

**Comment by softbeehive** [comment] 2022-12-10 21:42
First of all, 
I appreciate your hard work on the great open-source editor 🙏

Though I have to say in this situation DX is far from pleasant because folks on classic yarn 1.x including myself can't even downgrade back to pre `2.0.0-beta.205`

I was trying to understand why lock file contains references to 205 when I pin 202. Installing dependencies of tiptap explicitly is forcing people to maintain them.

#### This is sub-optimal because:
1. I don't know what version of prose-mirror packages each new release of tiptap is compatible with.
2. Eventually after upgrading packages I'm gonna end-up with spaghetti mix of versions and run into a conflict.
3. I don't use npm because it lacks features like **resolutions**

**Comment by markhughes** [comment] 2022-12-11 08:52
Could this be caused by the tiptap prosemirror tables extension?

my yarn.lock has it as this:
```
"@tiptap/prosemirror-tables@^1.1.3":
  version "1.1.3"
  resolved "https://registry.yarnpkg.com/@tiptap/prosemirror-tables/-/prosemirror-tables-1.1.3.tgz#cd812487fc103f921299a0cf899485f147b418b2"
  integrity sha512-Pp7Iyup+kxniDGEvFHX+BRw3et9vys83NVqk6B+PbVAztq64QyX/mY+vzcpFmOsF9/th+Po981igbGUG7C/8hw==
  dependencies:
    prosemirror-keymap "^1.1.2"
    prosemirror-model "^1.8.1"
    prosemirror-state "^1.3.1"
    prosemirror-transform "^1.2.1"
    prosemirror-view "^1.13.3"
```

**Comment by myovchev** [comment] 2022-12-11 10:00
> We added information about the peerDeps in our installation guide in the docs: https://tiptap.dev/installation#1-install-the-dependencies
> 
> But I'm also working on a better solution right now that should help out with those long install lines for Tiptap since our team also doesn't really like the current approach.
> 
> What we're working on is a meta package like `@tiptap/prosemirror` that you can install to automatically import all required prosemirror dependencies. in combination, you could also access prosemirror exports via `import { EditorState } from '@tiptap/prosemirror/state`.
> 
> I'm not 100% done as I have to do a bit of an overhaul on our build scripts to separate that build step from the other packages.

This indeed sounds like a much more elegant solution.
:100:

**Comment by SalahAdDin** [comment] 2022-12-21 23:21
We are getting this problem only with the `Garpcursor` extension.

**Comment by SamuelMS** [comment] 2023-01-18 00:19
@bdbch Love the idea of a `@tiptap/prosemirror` package – we'll likely hold off on upgrading until that gets set up since our team uses yarn extensively. Should we just keep an eye on #3556 for updates?

**Comment by bdbch** [comment] 2023-01-19 09:30
Hey @SamuelMS yes I'll keep you updated as soon as we have news on this. I'll focus on this issue for this and next week so we should have something up soon.

**Comment by bdbch** [comment] 2023-02-02 16:38
I just merged a PR for this which brings a few bigger breaking changes. Keep a look out for the release + new changelog.

**Comment by bdbch** [comment] 2023-02-02 17:24
@myovchev Our new version is released. Make sure to update to `2.0.0-beta.211`

You can read more here:
https://tiptap.dev/blog/new-pm-package-and-upgrade-guide-for-beta-210

**Closed by bdbch** 2023-02-02 17:24 UTC
Labels: bug

**Comment by tmikaeld** [comment] 2023-02-02 17:33
@bdbch Does it work with Yarn now?

**Comment by SalahAdDin** [comment] 2023-02-02 18:58
> @myovchev Our new version is released. Make sure to update to `2.0.0-beta.211`
> 
> You can read more here: https://tiptap.dev/blog/new-pm-package-and-upgrade-guide-for-beta-210

I will check it soon!
