### ISSUE TITLE
Menu bar buttons don't get their active state properly

### ISSUE THREAD

**Issue by twisted1919** [ueberdosis/tiptap#700] opened 2020-05-15 11:24 UTC
**Describe the bug**
We created a component which embeds the tiptap editor, something like:
```
<template>
    <div>
        <form method="post" class="form-grid">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="form-group">
                            <label>Editor</label>
                            <div class="sg-editor">
                                <editor-menu-bar :editor="descriptionEditor" v-slot="{ commands, isActive }">
                                    <div class="sg-editor-menubar">
                                        <a
                                                href="javascript:;"
                                                :class="{ 'sg-btn-bold ': true, 'is-active': isActive.bold() }"
                                                @click.prevent="commands.bold">
                                            <i class="fas fa-bold"></i>
                                        </a>

                                        <a
                                                href="javascript:;"
                                                :class="{ 'sg-btn-italic': true, 'is-active': isActive.italic() }"
                                                @click="commands.italic">
                                            <i class="fas fa-italic"></i>
                                        </a>
                                    </div>
                                </editor-menu-bar>
                                <editor-content
                                        :class="{ 'sg-editor-area': true}"
                                        :editor="descriptionEditor" />
                            </div>
                        </div>
                        <div class="spacer"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</template>

<script lang="ts">
    import Vue from "vue";
    import { Editor, EditorContent, EditorMenuBar } from "tiptap"
    import { Bold, Italic } from "tiptap-extensions"
    export default Vue.extend({
        props: {},
        data() {
            return <{
                descriptionEditor?: Editor;
            }>{
            }
        },
        components: {
            EditorContent,
            EditorMenuBar,
        },
        created(): void {
            this.descriptionEditor = new Editor({
                extensions: [
                    new Bold(),
                    new Italic(),
                ],
                onFocus: () => {},
                onUpdate: (state) => {
                    this.fields.description = state.getHTML();
                    if (this.fields.description === "<p></p>") {
                        this.fields.description = "";
                    }
                },
                content: ""
            });
        },
        beforeDestroy(): void {
            this.descriptionEditor.destroy();
        },
        methods: {},
        computed: {},
    });
</script>

<style lang="scss" scoped>

</style>

```

And we're observing a weird behavior.  
When we select text from the editor and then press the bold button for instance, the text is transformed in bold, as expected, but the bold button isn't getting it's active class.   
Then, if we click anywhere outside the editor, then the button will get it's active class. If we then click on an already bolded text, we expect the button to get the active class, instead it does not, but it does when we click outside the editor. Se below video which shows this behavior.

**Steps to Reproduce / Codesandbox Example**
We simply followed the examples from the examples page.

**Expected behavior**
We expect for the buttons to get the correct active class name when they are pressed or when a text is selected that matches the button functionality.

**Screenshots**
Here's a short video: https://www.dropbox.com/s/okzxiqkzuzl80da/vuejs-editor-bug.mov?dl=0 

**Environment**
 - OS: MacOS
 - Browser chrome
 - Version 81.0.4044.138 (Official Build) (64-bit)
 - Mobile / Desktop: Desktop

**Comment by cliftonscott** [comment] 2020-06-25 04:03
I'm having the same problem.

**Comment by madebycaliper** [comment] 2020-10-16 17:05
I'm having the same issue. There's a workaround presented by someone in [another duplicate thread](https://github.com/ueberdosis/tiptap/issues/738#issuecomment-682103716) that I can confirm works. Just replace `editor-menu-bar` with `editor-menu-bubble` and it should work.

**Comment by hanspagel** [comment] 2021-01-07 16:39
Thanks for reporting @twisted1919! And sorry for the trouble with the provided menu bar component. Luckily there is this workaround with the bubble menu. 

We’re about to completely rewrite the toolbar components, so I’m closing this for now, but it’s on my list to test that with the new components. ✌️

**Closed by hanspagel** 2021-01-07 16:39 UTC
Labels: bug, v2

**Comment by vincentdesmares** [comment] 2021-08-03 12:34
@hanspagel Hi, we had to drop our implementation of tiptap because of this bug. The workaround was not a solution for us.

Do you have an update on the toolbar refactoring?

Thanks for this amazing lib!

**Comment by philippkuehn** [comment] 2021-08-03 21:43
@vincentdesmares Are you using tiptap 1 or 2?

**Comment by vincentdesmares** [comment] 2021-09-13 12:09
Sorry @philippkuehn I missed your reply!

We are using Tiptap 2. As it is a new implementation we can upgrade to whatever is the last version.

**Comment by philippkuehn** [comment] 2021-09-13 12:22
@vincentdesmares could you create a reproducable codesandbox? If the issue still exists create a new issue please.

**Comment by vincentdesmares** [comment] 2021-09-13 12:42
@philippkuehn Sure! We will try that this week.

**Comment by dsubiros** [comment] 2022-09-19 16:42
Hello guys. I also experimented this issue, and I found a working solution:

I'm using Tiptap, with Vue + Vuetify (I attached the whole custom component I made in .tsx).
Versions in use are:
- _"@tiptap/vue-2": "^2.0.0-beta.195"_
- _"vue": "^2.6.14"_
- _"vuetify": "^2.5.9"_

I wanted to create the toolbar dynamically, by creating objects that represent groups of buttons, which then I render dynamically.

I realized that every time I click on any part inside the text box, the view is re-rendered, so the secret was to run the _needed_ function to get the value of the active status of every toolbar button. The secret dwells in the method **renderButton**, specifically in its first line: **const active = isActiveFn()**

```typescript
renderButton({runCommandFn, isActiveFn, icon, description}: IButton, key: number) {
        const active = isActiveFn();
        console.warn("description:", active);

        return <v-btn key={key} onClick={runCommandFn}
                      icon tile small rounded1 color={active ? "primary" : "default"}>
            <v-icon>{icon}</v-icon>
        </v-btn>
    }
    
    renderButtonGroup({name, buttons}: IButtonGroup, key?: number) {
        return <div>
            {buttons.map((y, index) => this.renderButton(y, index))}
        </div>
    }
```

To clarify a bit the code: 
- Interface IButton represents a button.
- IButtonGroup represents a group of buttons.
- IButton.runCommandFn and IButton.isActiveFn are the functions offered by Tiptap to run the command, and get isActive status.

When declaring an `IButtonGroup`, the **buttons** array might look like this:

```typescript
buttons: [{
                        description: "Italic",
                        runCommandFn: () => this.editor.chain().focus().toggleItalic().run(),
                        isActiveFn: () => this.editor.isActive("italic"),
                        icon: "mdi-format-italic"
                    }, {
                        description: "Bold",
                        runCommandFn: () => this.editor.chain().focus().toggleBold().run(),
                        isActiveFn: () => this.editor.isActive("bold"),
                        icon: "mdi-format-bold"
                    }]
```                    
                    
I hope this can help someone. I'm sorry if the format of this answer doesn't look the better possible. BTW: This custom component is a work-in-progress component in which I found this issue happening, so and I'm giving my working solution just after I found it and then, as result, this component might not be complete or have the best coding practices.

Dariel Subiros

[RichTextEditor.tsx.txt](https://github.com/ueberdosis/tiptap/files/9600649/RichTextEditor.tsx.txt)

**Comment by seeratawan01** [comment] 2024-07-04 15:38
I was facing the same issue while working with Tiptap, so to fix this with a quick workaround, I have created a custom hook that will check of active/inactive state on the update.

here is the example

```typescript

import { useEffect, useState } from 'react';
import useEditorStore from "@/stores/useEditorStore";

const useTiptapIsActive = (formatting: string): boolean => {
    // Your Editor instance
    const [activeEditorInstance]: any = useEditorStore((state) => [state.activeEditorInstance]);
    
    // State to store the active state
    const [isActive, setIsActive] = useState<boolean>(false);

    useEffect(() => {
        const onUpdate = (): void => {
            setIsActive(activeEditorInstance?.isActive(formatting) ?? false);
        };

        activeEditorInstance?.on('update', onUpdate);

        return (): void => {
            activeEditorInstance?.off('update', onUpdate);
        };
    }, [activeEditorInstance, formatting]);

    return isActive;
};

export default useTiptapIsActive;

```

and using it like this:

```typescript
const BoldButton = () => {
    const isActive = useTiptapIsActive('bold');

    return (
        <Group position={'center'} spacing={'xs'}
               style={{
                   backgroundColor: isActive ? '#f3f4f6' : 'transparent'
               }}
        >
            <LuBold size={'1rem'} strokeWidth={'2.5px'}/>
        </Group>
    )
}

const ItalicButton = () => {
    const isActive = useTiptapIsActive('italic');


    return (
        <Group position={'center'} spacing={'xs'}
               style={{
                   backgroundColor: isActive ? '#f3f4f6' : 'transparent'
               }}
        >
            <LuItalic size={'1rem'}/>
        </Group>
    )
}
```

I guess the issue is with the re-rendering and this workaround is doing fine with my case.
