### ISSUE TITLE
[Bug]: Usage of ReactNodeViewRender drastically reduces performance for large Text

### ISSUE THREAD

**Issue by wasular** [ueberdosis/tiptap#4492] opened 2023-09-30 12:17 UTC
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.6

### What’s the bug you are facing?

If I use this simple React Component as Wrapper for a Custom Paragraph the performance drastically reduces for large text. Luckily in my use case I don't need to use React Render for the Paragraph but there seems to be some performance bug which could be critical for other users.

```js
import { NodeViewWrapper, NodeViewContent } from '@tiptap/react';
import DragIndicatorIcon from '@mui/icons-material/DragIndicator';
import styles from './DraggableNodeView.module.scss';
import React from 'react';

const DraggableNodeView = ({ contentComponent: ContentComponent, ...props }) => {
  return (
    <NodeViewWrapper className={styles.node__wrapper}>
      <DragIndicatorIcon draggable="true" data-drag-handle className={styles.drag__icon} />
      {ContentComponent ? (
        <ContentComponent {...props} />
      ) : (
        <NodeViewContent className={styles.node__content} />
      )}
    </NodeViewWrapper>
  );
};

export default DraggableNodeView;
```

I now switched to vanilla html and js for this and it works

```js
import { Paragraph } from '@tiptap/extension-paragraph';

const CustomParagraph = Paragraph.extend({
  draggable: true,
  addNodeView() {
    return () => {
      const dom = document.createElement('div');
      dom.className = 'node__wrapper';

      const dragIcon = document.createElement('div');
      dragIcon.draggable = true;
      dragIcon.setAttribute('data-drag-handle', '');
      dragIcon.className = 'drag__icon';
      dragIcon.innerHTML =
        'svg';
      dom.appendChild(dragIcon);

      const content = document.createElement('div');
      content.className = 'node__content';
      dom.appendChild(content);

      return {
        dom: dom,
        contentDOM: content,
      };
    };
  },
});

export default CustomParagraph;
```

### What browser are you using?

Chrome

### What did you expect to happen?

Using a simple React render should not have this big of influence on the performance.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by jackbb147** [comment] 2023-10-02 21:24
I have the same issue. Terrible terrible performance with just a few react node views.

**Comment by Zloka** [comment] 2023-10-10 11:40
I noticed the same. In my case, it seems to be related to when the `selection` changes. `ReactNodeViewRenderer` has the following code:
```
handleSelectionUpdate() {
    const { from, to } = this.editor.state.selection

    if (from <= this.getPos() && to >= this.getPos() + this.node.nodeSize) {
      this.selectNode()
    } else {
      this.deselectNode()
    }
  }
  ```
  The problem is that `this.deselectNode()` is called for _all_ nodes, regardless of if they were selected or not, which causes a subsequent call to `this.updateProps({ selected: false })`, and that seems to cause a re-render of all nodes.

A better solution, assuming it is easy to track the currently select node, would be to only deselect relevant nodes, i.e. something like:
```
handleSelectionUpdate() {
    const { from, to } = this.editor.state.selection

    if (from <= this.getPos() && to >= this.getPos() + this.node.nodeSize) {
      this.selectNode()
    } else if (this.node.attrs.selected) {
      this.deselectNode();
    }
  }
  ```

From what I've tested, interestingly enough in my case, I could just remove the ` this.deselectNode();` entirely to both see a drastic improvement in performance, and the behavior remained as one would expect 🤔

**Comment by Zloka** [comment] 2023-10-11 05:46
> I noticed the same. In my case, it seems to be related to when the `selection` changes. `ReactNodeViewRenderer` has the following code:
> 
> ```
> handleSelectionUpdate() {
>     const { from, to } = this.editor.state.selection
> 
>     if (from <= this.getPos() && to >= this.getPos() + this.node.nodeSize) {
>       this.selectNode()
>     } else {
>       this.deselectNode()
>     }
> }
> ```
> 
> The problem is that `this.deselectNode()` is called for _all_ nodes, regardless of if they were selected or not, which causes a subsequent call to `this.updateProps({ selected: false })`, and that seems to cause a re-render of all nodes.
> 
> A better solution, assuming it is easy to track the currently selected node, would be to only deselect relevant nodes, i.e. something like:
> 
> ```
> handleSelectionUpdate() {
>     const { from, to } = this.editor.state.selection
> 
>     if (from <= this.getPos() && to >= this.getPos() + this.node.nodeSize) {
>       this.selectNode()
>     } else if (this.node.attrs.selected) {
>       this.deselectNode();
>     }
> }
> ```
> 
> From what I've tested, interestingly enough in my case, I could just remove the `this.deselectNode();` call entirely to both see a drastic improvement in performance, and the behavior remained as one would expect 🤔

To follow up a bit on my own reply: I did notice a change in behavior in some cases, as one would expect with the naive solution I suggested.

A more proper solution that, from what I can tell, keeps the behavior identical but also improves the performance, is essentially any solution that prevents the unnecessary `this.render();` calls in `updateProps`.

One temporary workaround could be to e.g. add a separate `updateSelectedProp` function:
```
updateSelectedProp(selected = false) {
    if (this.props.selected !== selected) {
      this.props.selected = selected;
      this.render();
    }
  }
  ```
...and change `deselectNode` to call it instead...
```
deselectNode() {
    this.renderer.updateSelectedProp(false);
    this.renderer.element.classList.remove('ProseMirror-selectednode');
  }
  ```
  Now, it seems that only the relevant nodes re-render, which in my cases of multiple thousands of nodes is very noticeable. A lot of unnecessary calls to `this.deselectNode` and `this.renderer.element.classList.remove('ProseMirror-selectednode');` still happen with the above approach, but those don't seem very costly.

**Comment by fdintino** [comment] 2023-10-19 13:28
I experienced a similar issue: text input in documents with many react node views was so slow as to make it unusable. There are probably a few performance optimizations to be had, but I found the performance issues to be related to #3580, which called out this method:

https://github.com/ueberdosis/tiptap/blob/42039c05f0894a2730a7b8f1b943ddb22d52a824/packages/react/src/EditorContent.tsx#L72-L82

. I fixed it by patching the function to just execute the function passed to it:

```tsx
import { PureEditorContent } from "@tiptap/react";

PureEditorContent.prototype.maybeFlushSync = (fn: () => void) => {
    fn();
  };
```

I'll keep taps on #3580 to see if there is a functional reason that it needs to call `flushSync` there, but I haven't noticed any issues so far.

**Comment by jaekunchoi** [comment] 2023-10-24 11:03
> I experienced a similar problem: text input in documents with many react node views was so slow as to make it unusable. There are probably a few performance optimizations to be had, but I found my issues to be related to #3580, which called out this method:
> 
> https://github.com/ueberdosis/tiptap/blob/42039c05f0894a2730a7b8f1b943ddb22d52a824/packages/react/src/EditorContent.tsx#L72-L82
> 
> I fixed it by patching the function to just execute the function passed to it:
> 
> ```tsx
> import { PureEditorContent } from "@tiptap/react";
> 
> PureEditorContent.prototype.maybeFlushSync = (fn: () => void) => {
>     fn();
>   };
> ```
> 
> I'll keep taps on #3580 to see if there is a functional reason that it needs to call `flushSync` there, but I haven't noticed any issues so far.

this fixed for me aswell

**Comment by frankdilo** [comment] 2023-10-26 09:29
I confirm this is an issue for my team too!

Removing the `flushSync(fn)` as the comments above suggest improves performance massively.

With unpatched TipTap I see my custom nodes re-render on every keystroke and it gets very problematic when the document has tens of them.

With the patch, I see only the custom node I am editing re-render.

**Comment by fdintino** [comment] 2023-10-27 03:38
Thanks for digging into that. I think you're right that flushSync is only meant to run once, after the component mounts. I've modified my patch and I believe it fixes some odd interactivity issues I had been experiencing, while also showing the performance improvement. For some reason I didn't think to attribute them to this change.

```tsx
PureEditorContent.prototype.maybeFlushSync = function maybeFlushSync(fn) {
  if (this.initialized) {
    flushSync(fn);
    this.initialized = false;
  } else {
    fn();
  }
};
```

**Comment by andrewlu0** [comment] 2023-10-27 19:25
We're experiencing similar issues as well, even after the patch above. I tried wrapping the NodeViewWrapper with a React Profiler https://react.dev/reference/react/Profiler and it looks like the nodes are constantly updating. Is this expected?

**Comment by fdintino** [comment] 2023-10-27 21:13
@andrewlu0 I can only speculate without seeing your code, but I would try to rule out something in your application. The flushSync bug is a problem in the framework, but it's fairly common to cause excessive renders in the course of development. I'd recommend profiling with the react chrome extension and judiciously applying debounced renders and memoization.

**Comment by andrewlu0** [comment] 2023-10-31 17:49
@fdintino I've tried a few attempts at memoization and debounced renders, but still experience significant lag when the number of React nodes reaches a few hundred, even with a very basic React node that is just a wrapper around a header. Is your application able to handle this well? Even trying the sample on their website here https://tiptap.dev/guide/node-views/react, if you copy/paste so there's around 300 copies of that yellow button node, the editor becomes very slow.

**Comment by fdintino** [comment] 2023-10-31 18:10
I do experience lag and performance issues, and with hundreds of nodes it becomes unusable. But those performance issues are fixed (for me) with the overridden definition of `PureEditorContent.prototype.maybeFlushSync` I posted earlier in the thread.

**Comment by dbousamra** [comment] 2023-11-01 23:54
Just adding another data point to the discussion. We have long documents (50+ A4 pages), with only ~ 100 React nodes in them. Performance is not yet at a standstill, but it's no longer "buttery" as we would like.

Adding the monkeypatch fix above fixes it for me. Thanks @fdintino

**Comment by kwarc-star** [comment] 2023-11-02 14:05
I am deploying to firebase and I cannot monkey patch because firebase rebuilds node_modules directory. Any way around this?

**Comment by zolero** [comment] 2023-11-07 11:04
Please can someone fix this at TipTap, because this makes TipTap with react components unusable... This should be fixed.

**Comment by AdventureBeard** [comment] 2023-11-09 22:03
Just to add another data point, the monkey-patch provided above does not improve performance for me, and changes the behavior of cursor placements after inserting nodes with React Node Views.

**Comment by fdintino** [comment] 2023-11-09 22:08
@AdventureBeard are you seeing the cursor behavior changes with the first or second patch that I posted?

**Comment by frankdilo** [comment] 2023-11-10 08:03
We had to revert the patch as well because of some weird cursor placement bugs that were introduced after applying it.

**Comment by fdintino** [comment] 2023-11-10 14:43
I wonder if there are other places where state dependencies aren't fully accounted for, but they hadn't caused bugs before because this bug was rerendering all components on every keystroke.

**Comment by fdintino** [comment] 2023-11-10 14:49
I am assuming your both referring to my patch and not @Zloka's, but it's probably worth clarifying that.

**Comment by AdventureBeard** [comment] 2023-11-10 15:53
@fdintino, this one:

```javascript
PureEditorContent.prototype.maybeFlushSync = function maybeFlushSync(fn) {
  if (this.initialized) {
    flushSync(fn);
    this.initialized = false;
  } else {
    fn();
  }
};
```

Specifically, whenever I inserted a node with a NodeView with a content hole, the cursor would be placed after the entire node, instead of within it. WIthout the monkey-patch, the cursor is placed inside the node view after insert as expected.

**Comment by fdintino** [comment] 2023-11-10 16:05
I'm not seeing that behavior. I was thinking of putting together a PR with this change, so if you could provide a minimal test case I could dig deeper and try to address it as part of that pull request.

**Comment by Slapbox** [comment] 2023-11-11 00:18
Can anyone tell me how exactly they're testing versus non-React rendering? So far I can't find any significant differences when rendering a codeblock in React versus pure JS.

**Comment by fdintino** [comment] 2023-11-11 23:47
Sure. [Here's a codesandbox](https://g6r9lh.csb.app/) demonstrating the problem, with a toggle between tiptap-react, a vanilla js nodeview, and a version with my patch and @Zloka's above. The number in the left margin is a count of the number of renders.

**Comment by Slapbox** [comment] 2023-11-12 00:14
Thanks @fdintino! That definitely makes React a lot more responsive in that example. 

Unfortunately it doesn't seem to bring Android speed up to vanilla JS speed as it seems to on PC, but that's understandable.

**Comment by fdintino** [comment] 2023-11-12 00:44
That can be achieved by wrapping the component in `React.memo`, since for this particular component it's not using any of the props. For me, this gives comparable performance:

```tsx
const ParagraphComponentPatched = React.memo(
  () => (
    <NodeViewWrapperPatched className="wrapper">
      <RenderCount />
      <NodeViewContentPatched as="p" />
    </NodeViewWrapperPatched>
  ),
  (prevProps, nextProps) => true
);
```

**Comment by KentoMoriwaki** [comment] 2023-11-24 01:56
I created a PR based on @fdintino 's monkey patch. Thanks.

**Comment by QuinnStraus** [comment] 2023-12-11 01:44
This seems to have been fixed in #4661 which is now released in 2.1.13

**Comment by janthurau** [comment] 2023-12-11 06:57
yes! Should be fixed by #4661. Let us know if the issue persists.

**Comment by Slapbox** [comment] 2023-12-17 00:24
This doesn't seem any better to me _at all_. 

Simply setting a selection leads to a 20 second wait on `flushSync` with a 300kb document if we use any React renderers in our editor. 

Removing the React renderer nodes and rendering them without React instead makes the page ultra-fast again.

**Comment by bdbch** [comment] 2023-12-17 12:26
We have the performance issues in our pipeline and we'll probably start working on all performance related issues with React after the holidays - just as a heads up.

**Comment by fdintino** [comment] 2023-12-17 15:00
The fix incorporated one of the fixes, but it didn't include my flushSync fix. I'll open that in a pull request.

**Comment by ArihantBapna** [comment] 2024-01-30 05:21
@fdintino was your flushSync fix added yet?

**Comment by Nantris** [comment] 2024-02-24 21:32
@bdbch is there any update on plans for this? Or has anything already been implemented?

I think it would be good to get this issue re-opened since it certainly does remain a problem (in `2.1.14` at least.)

We use a React renderer for only one node type, but it slows the editor down 10 fold in circumstances.

**Comment by Nantris** [comment] 2024-03-13 23:01
Could we please get this re-opened since the issue has been noted to not have really been addressed?

> We have the performance issues in our pipeline and we'll probably start working on all performance related issues with React after the holidays - just as a heads up.

**Comment by Nantris** [comment] 2024-05-12 00:03
Will there ever be follow-up on this? It's been nearly half a year.

**Comment by Nantris** [comment] 2024-05-19 02:06
Bump. The last time we heard from maintainers on this was six months ago and it's not even been re-opened, much less a single word of communication.

**Comment by svenadlung** [comment] 2024-05-22 15:10
Sorry for the silence. We will definitely take care of the issue.

**Comment by nperez0111** [comment] 2024-05-23 09:03
I have some ideas on how to improve this that I'll be implementing as a follow up to: https://github.com/ueberdosis/tiptap/pull/5161

Hopefully will get to it this week or beginning of next week

**Comment by ianrtracey** [comment] 2024-06-04 16:57
Running into performance issues as well

**Comment by nperez0111** [comment] 2024-07-04 11:55
This is fantastic @bartlomiej-korpus, I think your approach of avoiding re-rendering portals, and [my approach of avoiding flushSyncs](https://github.com/ueberdosis/tiptap/pull/5273) (instead using `useSyncExternalStore`) will definitely help performance of the integration. Sorry that I haven't gotten the time to get this completely done yet.

**Comment by bartlomiej-korpus** [comment] 2024-07-04 13:53
> This is fantastic @bartlomiej-korpus, I think your approach of avoiding re-rendering portals, and [my approach of avoiding flushSyncs](https://github.com/ueberdosis/tiptap/pull/5273) (instead using `useSyncExternalStore`) will definitely help performance of the integration. Sorry that I haven't gotten the time to get this completely done yet.

Nice! I definitely wanted to avoid `flushSync`, but I didn't feel confident enough in understanding its relationship to prosemirror-view to do it

**Comment by Nantris** [comment] 2024-07-11 03:33
Closeable now with the advent of `shouldRerenderOnTransaction`?

**Comment by nperez0111** [comment] 2024-07-11 08:02
There definitely still are some optimizations that I want to make for react node views specifically so happy to keep it open

**Comment by nperez0111** [comment] 2024-07-13 10:26
So I looked into the changes made with: https://github.com/ueberdosis/tiptap/issues/4492#issuecomment-2208731555

and it suffers from the same problem that I've been seeing (where on first render focus cannot be moved into the element). This issue happens because React renders in two passes and not synchronously. My patch [here](https://github.com/ueberdosis/tiptap/pull/5273) eeks out a bit more performance (by not using `flushSync` so often).


So I think for now we can probably just apply this, see if there are drawbacks I haven't accounted for and go from there.

**Comment by frankdilo** [comment] 2024-07-15 10:45
Just saw [the news](https://tiptap.dev/blog/release-notes/say-hello-to-tiptap-2-5-our-most-performant-editor-yet) for 2.5. Does it effectively close this issue?

**Comment by Nantris** [comment] 2024-07-16 20:47
@frankdilo

> There definitely still are some optimizations that I want to make for react node views specifically so happy to keep it open

**Comment by nperez0111** [comment] 2024-08-27 20:58
This is now resolved since 2.6

**Closed by nperez0111** 2024-08-27 20:58 UTC
Labels: Type: Bug, Category: Open Source

**Comment by jackIrvine97Baringa** [comment] 2025-03-11 19:30
This is a long thread. Summarising my experience for benefit of those coming in cold:

- i had this issue
- believe it was due to large (ish) custom react nodes re-rendering on every keystroke in editor
- setting `shouldRerenderOnTransaction: False` in `useEditor` resolved - some documentation in this would be good

**Comment by Nantris** [comment] 2025-03-11 20:55
@jackIrvine97Baringa it is mentioned [here](https://tiptap.dev/docs/guides/performance#gain-more-control-over-rendering), but I know that it's hard to find what you're looking for given the amount of documentation there is. 

@nperez0111 perhaps this should be mentioned on this page also: https://tiptap.dev/docs/editor/extensions/custom-extensions/node-views/react
