### ISSUE TITLE
SetContent removes styles

### ISSUE THREAD

**Issue by aolishevskaya** [ueberdosis/tiptap#495] opened 2019-10-17 06:14 UTC
Hi, can I do smt to not remove my inline styles, when I try to put it in editor?
I want to do something like this:
`this.editor.setContent('<p style="text-align: center">fffff</p>'), `but editor removes all my inline styles.

**Comment by brianchan661** [comment] 2019-11-07 06:46
I have the same question
I try to insert images to the editor and want to reduce the same, but the inline style and class was not working

> this.editor.setContent(`"<img src="https://images.pokemontcg.io/sm11/1.png" style="width:50px">  <img src="https://images.pokemontcg.io/sm11/3.png" class="cardIcon">"`);

The output 
![image](https://user-images.githubusercontent.com/14057272/68366101-c1a77500-0175-11ea-8a4c-ed39a2ca3093.png)

**Comment by aolishevskaya** [comment] 2019-11-11 11:57
> I have the same question
> I try to insert images to the editor and want to reduce the same, but the inline style and class was not working
> 
> > this.editor.setContent(`"<img src="https://images.pokemontcg.io/sm11/1.png" style="width:50px">  <img src="https://images.pokemontcg.io/sm11/3.png" class="cardIcon">"`);
> 
> The output
> ![image](https://user-images.githubusercontent.com/14057272/68366101-c1a77500-0175-11ea-8a4c-ed39a2ca3093.png)

yes, when I needed to do something like this, I did it like this:
I had an array with all my image which I insert into editor.
Then a founded them my they src like this: 
`const newImage = document.querySelector(`img[src=${CSS.escape(img.src)}]`);`
And then a did this:
`newImage.style.height = config.height + 'px';`

And config it's array where I had special size for my images.

**Comment by hanspagel** [comment] 2020-09-04 22:49
Unfortunately that’s a feature, not a bug.

Unlike many other editors, tiptap is based on a schema that defines how your content is structured. This enables you to define the kind of nodes that may occur in the document, its attributes and the way they can be nested.

This schema is very strict. You can’t use any HTML-element or attribute that is not defined in your schema.

For example if you paste something like `This is <strong>important</strong>` into tiptap and don’t have registered any extension that handles strong tags, you’ll only see `This is important`, same applies to inline styles.

Hope that helps! I’m closing this here.

**Closed** 2020-09-04 22:49 UTC
Labels: bug

**Comment by evgenyny** [comment] 2022-10-13 17:36
How to properly register extension that handles strong tags with classes or other inline style?

**Comment by Prabhat2373** [comment] 2024-11-28 05:44
Thanks @shafi-shaikat! 

struggling around it since 4 days, finally got the answer.
