### ISSUE TITLE
shouldShowBubble fire not correctly

### ISSUE THREAD

**Issue by FA-NhaLCT** [ueberdosis/tiptap#2130] opened 2021-11-04 11:05 UTC
### What’s the bug you are facing?

I want a bubble menu showing when caret reach the link, I use ShouldShow function combine with editor.isActive(''link") to track it.
The problem here is when caret reach the link, editor.isActive got false at the first time, and just correct at the second time. I figure out that it have been delay a step, becase the bubble position is showing at the pos before you reach the link.

### How can we reproduce the bug on our side?

1. Set caret out side the link
2. Move it to the link by keyword or mouse

### Can you provide a CodeSandbox?

https://codesandbox.io/s/flamboyant-flower-2b2nw?file=/src/App.vue

### What did you expect to happen?

editor.isActive() get true when caret reach the "link"

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2021-11-04 11:37
duplicate of #1986

**Closed by philippkuehn** 2021-11-04 11:37 UTC
Labels: bug

**Comment by FA-NhaLCT** [comment] 2021-11-05 10:31
It duplicate, but the problem i'm facing here is the bubble position, not the "activelink" methods. 
Please help me check it again.
Here is the video: https://watch.screencastify.com/v/d3if7WOY7JOGuE2tOYSu

Thank you in advance
