### ISSUE TITLE
Combining Floating and Bubble

### ISSUE THREAD

**Issue by Mr-Zer0** [ueberdosis/tiptap#451] opened 2019-09-08 07:43 UTC
### This is question (May be Featured Request)

I would like to use both ***Menu Bubble*** and ***Floating Menu*** in the same editor.
Please let me know if there is a way to combine them. If not please assume this issue as ***Feature Request***.

**Comment by philippkuehn** [comment] 2019-09-08 08:47
It should be possible already.

**Comment by Mr-Zer0** [comment] 2019-09-09 02:56
> It should be possible already.

Could you please show me how to do it. I am newbie for vue and frontend development.

**Comment by RomainLanz** [comment] 2019-10-30 11:37
Hey @philippkuehn! 👋 

In fact, when I'm using both I have an issue with the `Bubble` component.
When I click on a button it removes the focus and therefor close it without applying the command.

I'll try to troubleshoot a bit more this issue and see if the issue is on my side or if it's a bug on the package itself.

**Comment by RomainLanz** [comment] 2019-10-30 13:31
Seems that the issue is coming from the library itself.

I made an example on CodeSandbox to understand what I'm talking about.
https://codesandbox.io/s/tiptap-two-menu-issue-9wuct

When we select the text and click on the `Bubble` Menu it disappears. If we remove the `Floating` Menu the `Bubble` Menu works without any issue.

**Comment by RomainLanz** [comment] 2019-10-30 13:42
After more troubleshooting it seems that the issue only occurs when you are on macOS with Firefox or Safari (working on Chrome or any browser on Windows). 😄

**Comment by Neophen** [comment] 2020-01-21 11:16
it's happening in Chrome too.

**Comment by MazterQyou** [comment] 2020-02-07 04:48
I have this issue as well, took a long time to figure out the problem. Please fix this 🙏
Thanks in advance!

**Comment by danderozier** [comment] 2020-04-01 19:35
I'm also experiencing this issue, but I may have found a temporary fix — swapping the order of the two components:

```vue
// Issue occurs
<template>
  <editor-floating-menu ... />
  <editor-menu-bubble ... />

  <editor-content .../>
</template>

// After swapping order of components, issue does not occur:
<template>
  <editor-menu-bubble ... />
  <editor-floating-menu ... />

  <editor-content .../>
</template>
```

After a little digging, I think it might have something to do with the menus registering competing focus/blur handlers on the Editor instance, but I haven't had time to explore further.

**Comment by danderozier** [comment] 2020-04-02 00:30
Ok, I spoke a little too soon on the above being a "fix", but I think I figured out what's going on.

The unexpected behavior when using more than one menu is related to focus/blur event handlers being called more than once for the same event.

This is due to how ProseMirror registers plugins — each time a new plugin is registered, PM completely replaces its internal list of plugins by destroying the existing set and re-registering everything again: https://github.com/ProseMirror/prosemirror-view/blob/4623fa01fa44c9e853e47888486250b5e31bb6df/src/index.js#L191

When each menu plugin is created, it sets focus and blur handlers on the Editor instance, but those handlers aren't removed when the plugin is destroyed. When a menu plugin is registered, any existing menu plugins define another set of event handlers on the Editor (this is why the component order affects the behavior — depending on the order of registration, different menus will have different numbers of duplicate handlers).

Anyhow, I put together a PR that resolves this, and will post it shortly.

**Closed** 2021-01-07 21:02 UTC
Labels: feature request
