### ISSUE TITLE
Inline code escaping [shift+enter] doesn't work

### ISSUE THREAD

**Issue by aleksey-hoffman** [ueberdosis/tiptap#660] opened 2020-04-10 15:26 UTC
**Describe the bug**
You cannot escape from an inline code block with `shift+enter`

**Steps to Reproduce / Codesandbox Example**
1. Go to https://tiptap.scrumpy.io/
2. Create an inline code block
3. Try to escape it with `shift+enter`

**Expected behavior**
Cursor to move outside of the inline code block to the right and continue in the `paragpraph` mode.

**Screenshots**

![1](https://user-images.githubusercontent.com/61761672/79002176-94158c00-7b58-11ea-9e37-c3f0810c4d1b.gif)

**Environment**
 - OS: Windows 10
 - Browser: Chrome 81

**Comment by aleksey-hoffman** [comment] 2020-04-10 15:49
Also, I just noticed, you cannot escape from the table with `shift+enter` either

**Comment by philippkuehn** [comment] 2020-04-10 18:16
Oh no, that worked once.

**Comment by hanspagel** [comment] 2021-01-12 19:49
That seems to be a duplicate of #514. We’re trying to fix that one!

**Closed by hanspagel** 2021-01-12 19:49 UTC
Labels: bug, should have a test in v2
