### ISSUE TITLE
TypeError: Cannot read property 'nodeType' of undefined" 

### ISSUE THREAD

**Issue by WolfForest** [ueberdosis/tiptap#1001] opened 2021-03-16 22:30 UTC
https://github.com/ueberdosis/tiptap/blob/fffdb358a97ca2b79b51d72036576a158c28799b/examples/Components/Routes/Suggestions/index.vue#L78

If you specify one word an error appears
![image](https://user-images.githubusercontent.com/4728356/111388239-fad3eb80-86bf-11eb-9636-17ff77003cfe.png)

I can't understand why this problem is only if there is one word there

**Comment by Jordan-T** [comment] 2021-03-22 10:44
I have the same issue!

**Comment by leobia** [comment] 2021-03-25 11:36
Same issue

**Comment by hanspagel** [comment] 2021-03-29 18:41
Thanks for reporting! Seems to be a duplicate of #932 so I’m closing this here. ✌️

**Closed by hanspagel** 2021-03-29 18:41 UTC
