### ISSUE TITLE
Disable / prevent drop image on editor

### ISSUE THREAD

**Issue by mattiaerli97** [ueberdosis/tiptap#706] opened 2020-05-22 10:50 UTC
Goodmorning,
in my application I would like to use a custom drop handler for the textbox in the component. However I can't disable the default behaviour for the drop event.
I simply would like to disable it to personalize it with my custom handler.

I already know that there's an onDrop event, but that event deals with drag and drop when image is ALREADY in the textbox. Obviously my request is to implement something that prevent the image to be added to the textbox.

I hope my explanation is clear and I'm here to clarify any doubt. Thanks in advance.
Best regards,
Mattia

**Comment by pshah123** [comment] 2020-06-17 22:45
You should be able to prevent DOM events by just removing the handler from the class. The easiest way to go about this is to extend or make a duplicate of the existing Image plugin [which can be found here](https://raw.githubusercontent.com/scrumpy/tiptap/master/packages/tiptap-extensions/src/nodes/Image.js).

All you have to do is remove the DOM event handler prop in the above linked component for dropping -- it's called `drop` in the `get plugins` method and you can get rid of it like so:
``` diff
	get plugins() {
		return [
			new Plugin({
				props: {
					handleDOMEvents: {
-                                           drop(view, event) { ... },
					},
				},
			}),
		]
	}
```

You could also just write your custom handler there by changing the content of the `drop` function.

FWIW there's also support for different DOM events in there (e.g. `paste`).

**Comment by hanspagel** [comment] 2021-01-07 16:33
Thanks for helping out @pshah123! 💖

**Closed by hanspagel** 2021-01-07 16:33 UTC
Labels: feature request

**Comment by duhaime** [comment] 2022-01-21 13:53
@hanspagel @cuuupid It looks like the [extensions-image source](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-image/src/image.ts) no longer contains a `plugins()` method.

Do either of you have any advice on how to prevent the drop listener in tiptap v2?

**Comment by david-hass** [comment] 2024-03-07 14:43
if you want to prevent dropping content from outside the editor, but allow in-editor drag and drop you can do so via a prosemirror plugin:

```
export const pluginKey = new PluginKey('prevent-drop-from-outside');

export const preventDropFromOutsidePlugin = new Plugin({
    key: pluginKey,
    state: {
        init: () => false,
        apply: (tr, prev) =>
        {
            const action = tr.getMeta(pluginKey);
            if (!action)
            {
                return prev;
            }

            switch (action)
            {
            case 'drag':
                return true;
            case 'drop':
            default:
                return false;
            }
        },
    },
    props: {
        handleDOMEvents: {
            dragstart(view)
            {
                const dragFromInsideActive = pluginKey.getState(view.state);
                if (!dragFromInsideActive)
                {
                    view.dispatch(view.state.tr.setMeta(pluginKey, 'drag'));
                }
            },
            drop(view, event)
            {
                const dragFromInsideActive = pluginKey.getState(view.state);
                if (dragFromInsideActive)
                {
                    view.dispatch(view.state.tr.setMeta(pluginKey, 'drop'));
                    return false;
                }
                event.preventDefault();
                return true;
            },
        },
    },
});

```
