### ISSUE TITLE
multiple mentions are not working in suggestions

### ISSUE THREAD

**Issue by DebaPrasad14** [ueberdosis/tiptap#896] opened 2020-11-13 15:32 UTC
**Describe the bug**
when trying to mention multiple users in the same line it's not working.

**Example**
Can check here in example site: https://tiptap.dev/suggestions

**Expected behavior**
we should able to mention multiple users in one line.

**Comment by ironshu** [comment] 2020-11-14 17:53
On a related note (I hope this is from the same cause) inserting a mention in an empty editor does not work. **However** it does work if the editor loads with content, and you then delete all the content before inserting a mention.

**Comment by jonathanmach** [comment] 2020-11-15 17:57
Duplicate of #874

**Comment by hanspagel** [comment] 2020-11-16 10:45
Thanks for reporting @DebaPrasad14! As Jonathan said, there is already an issue to follow, so I’m closing this here for now.

**Closed by hanspagel** 2020-11-16 10:45 UTC
Labels: bug
