### ISSUE TITLE
[Bug]: Floating Menu interferes with clicks that would show Floating Menu

### ISSUE THREAD

**Issue by markdon** [ueberdosis/tiptap#5857] opened 2024-11-21 23:07 UTC
### Affected Packages

core, floating-menu, react

### Version(s)

2.9.1

### Bug Description

When clicking at a location within the editor that would trigger the Floating Menu to appear and the click location is also where the Floating Menu will appear, the Floating Menu interferes with the click, changing selection and closing the Floating Menu. 

Reproducable in extension demo:
![fU0Nhavydw](https://github.com/user-attachments/assets/6fae9933-f8e2-48b0-8c62-b663bef3113a)

### Browser Used

Chrome

### Code Example URL

https://tiptap.dev/docs/editor/extensions/functionality/floatingmenu

### Expected Behavior

Cursor selection appears at beginning of line, floating menu appears in expected place underneath mouse cursor.

### Additional Context (Optional)

I've been working for a couple hours on different methods that try to delay the showing/clickability of the Floating Menu for a moment. Managed to delay the initial show but haven't figured out how to handle the Floating Menu moving between lines.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment] 2024-11-22 08:10
Try 2.10.1 please to see if it resolves your issue?

**Comment by markdon** [comment] 2024-11-24 23:16
Updated to latest/2.10.2.

<details><summary>Package List</summary>
<pre>
    "@tiptap/core": "^2.10.2",
    "@tiptap/extension-blockquote": "^2.10.2",
    "@tiptap/extension-bold": "^2.10.2",
    "@tiptap/extension-bullet-list": "^2.10.2",
    "@tiptap/extension-code": "^2.10.2",
    "@tiptap/extension-code-block": "^2.10.2",
    "@tiptap/extension-collaboration": "^2.10.2",
    "@tiptap/extension-collaboration-cursor": "^2.10.2",
    "@tiptap/extension-color": "^2.10.2",
    "@tiptap/extension-document": "^2.10.2",
    "@tiptap/extension-dropcursor": "^2.10.2",
    "@tiptap/extension-floating-menu": "^2.10.2",
    "@tiptap/extension-font-family": "^2.10.2",
    "@tiptap/extension-gapcursor": "^2.10.2",
    "@tiptap/extension-hard-break": "^2.10.2",
    "@tiptap/extension-heading": "^2.10.2",
    "@tiptap/extension-highlight": "^2.10.2",
    "@tiptap/extension-history": "^2.10.2",
    "@tiptap/extension-horizontal-rule": "^2.10.2",
    "@tiptap/extension-image": "^2.10.2",
    "@tiptap/extension-italic": "^2.10.2",
    "@tiptap/extension-link": "^2.10.2",
    "@tiptap/extension-list-item": "^2.10.2",
    "@tiptap/extension-mention": "^2.10.2",
    "@tiptap/extension-ordered-list": "^2.10.2",
    "@tiptap/extension-paragraph": "^2.10.2",
    "@tiptap/extension-placeholder": "^2.10.2",
    "@tiptap/extension-strike": "^2.10.2",
    "@tiptap/extension-subscript": "^2.10.2",
    "@tiptap/extension-superscript": "^2.10.2",
    "@tiptap/extension-table": "^2.10.2",
    "@tiptap/extension-table-cell": "^2.10.2",
    "@tiptap/extension-table-header": "^2.10.2",
    "@tiptap/extension-table-row": "^2.10.2",
    "@tiptap/extension-task-item": "^2.10.2",
    "@tiptap/extension-task-list": "^2.10.2",
    "@tiptap/extension-text": "^2.10.2",
    "@tiptap/extension-text-align": "^2.10.2",
    "@tiptap/extension-text-style": "^2.10.2",
    "@tiptap/extension-underline": "^2.10.2",
    "@tiptap/html": "^2.10.2",
    "@tiptap/pm": "^2.10.2",
    "@tiptap/react": "^2.10.2",
    "@tiptap/suggestion": "^2.10.2",
</pre>
</details> 

Reproduced in my own project:
![NAvtah7UdU](https://github.com/user-attachments/assets/926891f0-a806-4b75-87ca-40ccabbc2ec7)

Still reproducible in the demo, which I imagine is automatically up to date: https://tiptap.dev/docs/editor/extensions/functionality/floatingmenu

**Comment by Cirr0e** [comment] 2024-11-25 05:35
Hi there! I understand you're experiencing issues with the floating menu interfering with clicks. Based on my analysis of similar issues and the current codebase, I can suggest a proven solution.

The problem occurs due to event handling conflicts between the click that triggers the menu and the menu's own interaction with that click. Here's how we can fix this:

1. First, add focus management to your floating menu:
```javascript
<floating-menu @click.native='editor.commands.focus()'>
  {/* your menu content */}
</floating-menu>
```

2. To prevent click interference during transitions, add these CSS properties to your floating menu:
```css
.floating-menu {
  pointer-events: none;
}
.floating-menu.is-active {
  pointer-events: auto;
}
```

3. If you need more control over menu visibility, you can also implement a visibility state:
```javascript
const editor = new Editor({
  onBlur: ({ event }) => {
    this.isMenuActive = false;
  },
  onFocus: () => {
    this.isMenuActive = true;
  }
})
```

This solution is based on successful implementations from other users, particularly from issue #256 where similar focus/visibility issues were resolved.

Key benefits of this approach:
- Ensures proper focus management
- Prevents click interference
- Maintains expected editor behavior

Please note that if you're using the menu in combination with placeholder text, you'll want to ensure proper z-index management to prevent overlapping issues.

Let me know if you need any clarification or run into any issues implementing this solution!

References:
- Issue #256: Successful implementation of menu visibility control
- Issue #1433: Related floating menu focus management discussion
- Issue #470: Menu interaction improvements

**Comment by nperez0111** [comment] 2024-11-25 09:25
Ugh this bot is spamming the repo, @Cirr0e can we opt out of you?

@markdon, sorry it is a bit unclear what is happening here because when I try to reproduce that with our demo I don't see an issue. Also around your cursor there is like a top and bottom indicator, is that an accessibility thing? Maybe this is browser or configuration related?

**Comment by markdon** [comment] 2024-11-25 23:56
Wow. I really should have asked one of my collegues to check if this was a me-problem. You're actually right, the issue only occurs when I have this _Text cursor indicator_ enabled. It's a feature in Windows 11. [See this help doc.](https://support.microsoft.com/en-au/windows/make-your-mouse-keyboard-and-other-input-devices-easier-to-use-10733da7-fa82-88be-0672-f123d4b3dcfe#:~:text=Use%20the%20text%20cursor%20indicator)

I read tippy.js is replaced in v3. It there an easy way for me to run v3 and test if this still exists? 

I don't mind if this goes unfixed/Windows _Text cursor indicator_ is not supported, but I have no idea how common it is.

**Comment by nperez0111** [comment] 2024-11-26 08:57
Well that is interesting. Can't speak to how common it is, I don't even run windows.

Tippy is removed in the `next` version of tiptap currently released in a pre-release: https://github.com/ueberdosis/tiptap/releases/tag/v3.0.0-next.1

It has not been released in a while as we've been trying to go for stability on the v2 version, but it should totally be usable

**Comment by nperez0111** [comment] 2024-11-26 08:58
I'm going to close this, considering we probably don't have to the APIs that would even help with this. But, if more people need it we can consider it in the future. Probably would have to be fixed at the Prosemirror level though

**Closed by nperez0111** 2024-11-26 08:58 UTC
Labels: Type: Bug, Category: Open Source
