### ISSUE TITLE
TaskItem raises an exception when checkbox clicked

### ISSUE THREAD

**Issue by clibu** [ueberdosis/tiptap#2590] opened 2022-02-28 22:08 UTC
### What’s the bug you are facing?

When you click on a TaskItem checkbox you get ```fragment.js:159 Uncaught RangeError: Index 1 out of range for <taskList(taskItem(paragraph))>```

### How can we reproduce the bug on our side?

See above.

You can replicate this issue on the sample app at https://tiptap.dev/ and on https://tiptap.dev/api/nodes/task-list

### Can you provide a CodeSandbox?

The issue is on line 123 in task-item.ts ```const position = getPos()```  getPos() is returning ```undefined```  which causes ```tr.doc.nodeAt(position)``` to raise the exception.

You can replicate this issue on the sample app at https://tiptap.dev/ and on https://tiptap.dev/api/nodes/task-list

### What did you expect to happen?

The checkbox state to toggle.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2022-03-31 16:05
Sounds like duplicate of #2372

**Closed by philippkuehn** 2022-03-31 16:05 UTC
Labels: bug
