### ISSUE TITLE
`generateHTML` does not create line break `<br />` for empty paragraphs

### ISSUE THREAD

**Issue by cusxio** [ueberdosis/tiptap#2318] opened 2021-12-27 07:14 UTC
### What’s the bug you are facing?

`generateHTML` does not create line break `<br/>` for empty paragraphs.

i.e.

`generateHTML` renders `<p></p>` for empty paragraphs rather than `<p><br/></p>`

### How can we reproduce the bug on our side?

Run `generateHTML` with a  json that contains an empty paragraph 

```ts
const json = {
  type: "doc",
  content: [
    {
      type: "paragraph" // Empty paragraph, should be rendered with `<br/>`
    },
    {
      type: "paragraph",
      content: [
        {
          type: "text",
          text: "Some textt"
        }
      ]
    }
  ]
};
```

Output:

```ts
const output = generateHTML(json, [StarterKit]);
// <p></p><p>Some text</p>
```

Notice the missing `<br />` tag in the first paragraph.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-test-f005w

### What did you expect to happen?

For empty paragraphs, `generateHTML` should generate `<p><br/></p>`

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2021-12-27 07:33
duplicate of #412

**Closed** 2021-12-27 07:33 UTC
Labels: bug
