### ISSUE TITLE
Problem with Multiple Editors and v-for when deleting/splice an element in the array

### ISSUE THREAD

**Issue by nadar** [ueberdosis/tiptap#3067] opened 2022-08-09 07:18 UTC
### What’s the bug you are facing?

We know its always hard to understand others projects setup as maintainer, so i try to explain this quickly:

We use tiptap as a very versatile place to map data and mixed content, like a very smart input text field :-)

![image](https://user-images.githubusercontent.com/3417221/183584534-bff2a95c-4f74-4593-8b4e-a8cc539c7341.png)

Now we have a very strange behavior of that "multiple tiptap editor" setup (they do not sharing anything to each other), when we remove an element in that array (this is what the iteration looks like and `integration-map-field` holds the tiptap editor instance):

```
<template v-for="(field,index) in item.config_json.fields">
    <integration-map-field
      :key="index"
      v-model="item.config_json.fieldMap[field.identifier]"
      :editable="true"
      :label="field.label"
      :type="field.type"
      :required="field.required"
      :fields-collection="item.pool.typeEntity.fieldsCollection"
      @remove="removeField(item, index, field.identifier)"
    />
  </template>
```

then it removes the element, but at the absolute wrong position, its no matter what, always removes the latest tiptap editor. For example we remove this one (array.splice(....)):

![image](https://user-images.githubusercontent.com/3417221/183585050-2fbfeb99-8d00-47a4-84be-5765ff85cbbd.png)

It removes the wrong editor, it always removes the last tiptap editor, but as you can see the array iteration has been correctly adjusted, the field `title` has been removed from the array:

![image](https://user-images.githubusercontent.com/3417221/183585411-cdf900f1-9adc-41d2-9c62-1c8d9d97fc03.png)

This is so strange, i could not find anything regarding this. So i was looking for "uniqueids" or whatever. Maybe there is global instanced variable i need to consider?

+ i played around with `this.editor.destroy()` without any luck
+ i tested with vue's $forceUpdate() 
+ i tested without tiptap (just added a textarea) and everything works expected.
+ my environment is nuxt 2 with vuetify

### Which browser was this experienced in? Are any special extensions installed?

Chrome, Firefox. It happens on all browsers

### How can we reproduce the bug on our side?

Take a look here: https://codesandbox.io/s/tiptap-vue-multiple-editor-issue-oxr1lo?file=/src/App.vue

### Can you provide a CodeSandbox?

**Update: Yes, its easy to reproduce, just add 3 or more items and remove an item in the middle: https://codesandbox.io/s/tiptap-vue-multiple-editor-issue-oxr1lo?file=/src/App.vue**

### What did you expect to happen?

It should removed the editor in the row, not the last one. it always removes the last one no matter what we do :-) 

### Anything to add? (optional)

This is what the component looks like ... i have removed unnecessary logic and markup for better readability:

<details><summary>The Component</summary>

```vue
<template>
  <div>
      <editor-content
        :editor="editor"
      />
      <v-btn
          icon
          @click="removeItem"
        >
          <v-icon small>icon icon-remove</v-icon>
      </v-btn>
  </div>
</template>

<script>
// https://stackoverflow.com/questions/48145727/insert-character-at-cursor-position-in-vue-js
import IntegrationMapFieldMapperInputSpan from './IntegrationMapFieldMapperInputSpan.vue'
import { Editor, EditorContent, Node, VueNodeViewRenderer, mergeAttributes} from '@tiptap/vue-2'
import Document from '@tiptap/extension-document'
import Text from '@tiptap/extension-text'

const Div = Node.create({
  name: 'div',
  group: 'block',
  content: 'inline*',
  parseHTML() {
    return [
      { tag: 'div'},
    ]
  },
  renderHTML({ HTMLAttributes }) {
    return ['div', mergeAttributes(HTMLAttributes, {style:"vertical-align: text-top; line-height:30px"}), 0]
  },
})

const Variable = Node.create({
  name: 'variable',
  group: 'inline',
  inline: true,
  atom: true,
  selectable: false,
   addAttributes() {
   // removed the attributes
  },
  parseHTML() {
    return [
      { tag: 'span' },
    ]
  },
  renderText({ node }) {
    return `${node.attrs.label}`
  },
  renderHTML({ node, HTMLAttributes }) {
    return ['span', mergeAttributes(HTMLAttributes), node.attrs.label]
  },
  addNodeView() {
    return VueNodeViewRenderer(IntegrationMapFieldMapperInputSpan)
  }
})

export default {
  components: { EditorContent },
  props: {
    // removed the props
  },
  data:() => ({
    editor: null
  }),
  computed: {
    parsedValue: function() {
     // we do more things here, fulfill the array
      return {
        "type": "doc",
        "content": contentArrays
      }
    }
  },
  mounted() {
    this.editor = new Editor({
      extensions: [
        Document,
        Div,
        Text,
        Variable
      ],
      autofocus: 'end',
      content: this.parsedValue,
      onUpdate: () => {
        const values = []
        const content = this.editor.getJSON().content
        // we do more things here
        this.$emit('input', values)
      },
    })
  },
  beforeDestroy() {
    this.editor.destroy()
  },
  methods: {
    removeItem() {
      this.$emit('removeItem')
    }
  }
}
</script>
```

</details>

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by nadar** [comment] 2022-08-09 17:52
I made a codesandbox, its very easy to reproduce. https://codesandbox.io/s/tiptap-issue-template-forked-3075gh?file=/src/App.vue

add 3 are more items, delete the one in the middel and magically the last editor is always deleted. :sob:

**Comment by bdbch** [comment] 2022-08-22 08:57
Hey @nadar.

I'm going to take a look into this issue to find out what exactly is happening here. Thanks for reporting!

**Comment by nadar** [comment] 2022-08-22 09:12
@bdbch thank you for taking care of this. Let me know if i can help or test something.

**Comment by bdbch** [comment] 2022-08-22 10:30
Hey @nadar I'm a bit capped on time right now so I won't be able to fix this today since it looks like it's a bit deeper as it's also happening with React and Vue 3. Somehow on unmount/destroy, the last editor created gets destroyed instead of the one that should actually be deleted.

When I find time I will come back to this issue to see what exactly is happening and how we can fix this.

**Comment by nadar** [comment] 2022-08-22 10:47
:disappointed: ok, thanks. Any idea for a workaround? refs with an array and a random identifiert? sth likes this?

**Comment by bdbch** [comment] 2022-08-22 13:04
Not for now as this issue is quite weird. I'll look into it as soon as I find a solution!
I marked it as high priority in our tracker.

**Comment by oferitz** [comment] 2022-10-03 14:22
We are seeing very similar issue with React, when you have multiple instances of the editor on the same page you get inconsistent mount/unmount behavior. it seems like change in one instance is affecting other instances.

**Comment by nadar** [comment] 2023-01-14 14:04
No don't close, its a bug, which received the 2.0.0 milestone (and suddenly was removed again)

**Comment by subssn21** [comment] 2023-02-22 17:34
Are there any workarounds for this issue? I am seeing it as well, and it is breaking things in a way that makes our app unusable.

**Comment by nadar** [comment] 2023-02-22 17:36
Sadly they don't care :-) We have generated super random `;key=''` value which seems to work.

**Comment by subssn21** [comment] 2023-02-22 21:57
So I think this is not a bug (At least in Vue 3)

If you provide a key in your for loop the problem goes away
Reading the documentation in Vue 3 seems to define the exact behavior being shown, adding the key seems to solve it.
https://vuejs.org/guide/essentials/list.html#maintaining-state-with-key

**Comment by nadar** [comment] 2023-02-22 22:10
we always used keys, but they might not been unique enough, the example uses the index as key. works everywhere, expect with tiptap.

**Comment by bdbch** [comment] 2023-02-24 14:00
We care, but we weren't able to find a good solution yet and have a few other things on our table so I wasn't able to work on this specific issue again.

If someone wants to investigate this feel free. I also think this is not related to Vue but how Editor instances are stored and rendered via the Renderer?

**Comment by nadar** [comment] 2023-02-24 14:03
@bdbch i am sorry, it was a inappropriate choice of words, it's still an opensource project. I am going to close this issue, since using f.e using uuidv4() keys as index works.

**Comment by bdbch** [comment] 2023-02-24 14:11
No worries, didn't pick it up as an insult or something. Feel free to keep it open. I think it's a valid issue, but it's nice to keep information about your temporary solution in here so others can fix it on their end while we dig out a fix! :)

**Comment by bdbch** [comment] 2023-03-02 15:35
Hey @nadar I checked this issue again. I don't think there is anything wrong with Tiptap or ProseMirror on this one. As others pointed out using a unique value in this rendering loop other than the array index will fix this issue.

The explanation for that is that you need to destroy the editor object at some point of you remove the renderer around it. You can try it on your own if you do something like this:

```js
beforeUnmount() {
  console.log('destroy', this.id)
  this.editor.destroy()
},
```

If you do this even without using Tiptap, the `this.id` will be mapped completely wrong from Vue as vue can't really resolve the correct "id" to the index.

Lets say you have an array of 6 items so you'd have the indexes `[0, 1, 2, 3, 4, 5]` which would resolve in something like this:

```vue
<my-component :key="0" />
<my-component :key="1" />
<my-component :key="2" />
<my-component :key="3" />
<my-component :key="4" />
<my-component :key="5" />
```

Now if you remove the third element `key 2`, the following index array will be returned:<br />
`[0, 1, 2, 3, 4]`

This would still resolve into

```vue
<my-component :key="0" />
<my-component :key="1" />
<my-component :key="2" />
<my-component :key="3" />
<my-component :key="4" />
```

As you can see, the item you actually wanted to remove still exists (`key 2`) but the last element in the array got removed. I think the Vue renderer for example still manages to render this correctly, but the props onDestroy will use the wrong values.

We could now somehow implement some way to adjust to key changes inside the Vue renderer but I believe the index should not be used as an key to begin with, the same with React (the React docs even warn you to do so).

https://stackoverflow.com/a/44531545

I'd close this issue for now as this is expected behavior.

**Closed by bdbch** 2023-03-02 15:35 UTC
Labels: bug
