### ISSUE TITLE
[Bug]: Wrong link on paste with hard break

### ISSUE THREAD

**Issue by Ste35** [ueberdosis/tiptap#5679] opened 2024-09-29 07:46 UTC
### Affected Packages

extension-link

### Version(s)

2.6.6

### Bug Description

Hi, I'd like to report a possibile bug that occurs when pasting a link with a new line separated by an hard break (I hope it's not a duplicate!).

When coping and pasting together:
- a line with a link and 
- a following line separated by an hard break (that is a `br`)

the pasted link "extends" to the first word of the following line and the link pasted is incorrect:
![tiptap-issue-1](https://github.com/user-attachments/assets/33196922-f365-4f85-aa1a-80bfa2422000)
(in this case, the pasted link will be `https://google.com￼This`)

The problem doesn't show up if the two lines are in different paragraphs:
![tiptap-issue-2](https://github.com/user-attachments/assets/5e5169b4-2c16-491f-a777-09456eb8f33d)

You can also see the same issue in the Tiptap public demo: https://templates.tiptap.dev/
![tiptap-issue-3](https://github.com/user-attachments/assets/568a0cd0-d64e-4bbd-bdc2-d0d63ae5cd20)

Is this an actual issue or am I missing something?
Thank you for your work!

### Browser Used

Chrome

### Code Example URL

https://stackblitz.com/edit/react-xqt1gu?file=src%2FApp.js

### Expected Behavior

The copied link and the following line should be kept as in the original source.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by iropolo** [comment] 2024-11-19 19:50
Same issue.
Probably related to #5335 

Video:

https://github.com/user-attachments/assets/f670a46d-a097-4435-bca1-5e349d9d3cd8

**Comment by nperez0111** [comment] 2024-11-20 13:38
It's likely this bit of code here which is trying to get all of the pasted content as a string to see what can be linked: https://github.com/ueberdosis/tiptap/blob/ff6e00a35664db0d8709fd2f31b400db7a10ea74/packages/extension-link/src/helpers/pasteHandler.ts#L24-L29

I would be happy to accept a contribution here. I think that all that needs to be done is to append a newline to each node.textContent added, so that when we look for links, it will not try to include the next word as the link.

I just don't have time to work on this at the moment & validate it. Would appreciate your help here @iropolo & @Ste35

**Comment by iropolo** [comment] 2024-11-25 14:48
Huh I spend some time

I take a look into these files

->
https://github.com/ueberdosis/tiptap/blob/86250c6e9e760d7af9780cf3ab276b1ec5fedb75/packages/extension-link/src/link.ts#L346-L349

-> https://github.com/ueberdosis/tiptap/blob/86250c6e9e760d7af9780cf3ab276b1ec5fedb75/packages/core/src/PasteRule.ts#L180

->
https://github.com/ueberdosis/tiptap/blob/f8961a984f0e89d5e20e3414b048660eab600b39/packages/core/src/pasteRules/markPasteRule.ts#L22-L26

Somewhere in `markPasteRule` seems like is messing with the nodes.

------
Process:
1. PasteRule
2. MarkPasteRule
3. PasteRule


At the beginning, the node looks like: (in `pasteRule`)

<img width="1461" alt="Screenshot 2024-11-25 at 11 18 35" src="https://github.com/user-attachments/assets/0d338a9f-fe05-4d8d-854b-15911fa6d3ec">
2 nodes.
Second node with 2 content, link+text, separated.


Then, it starts the process of: 
https://github.com/ueberdosis/tiptap/blob/86250c6e9e760d7af9780cf3ab276b1ec5fedb75/packages/core/src/PasteRule.ts#L122-L124

This will be run twice, 1 for each node:

These are the console.logs of `text` param: 
https://github.com/ueberdosis/tiptap/blob/86250c6e9e760d7af9780cf3ab276b1ec5fedb75/packages/extension-link/src/link.ts#L346-L349

First return:

<img width="1442" alt="image" src="https://github.com/user-attachments/assets/9a4ea1da-a8fa-45b6-bdd6-b5721df5d32f">

-> `form:`


Second return:

<img width="1442" alt="image" src="https://github.com/user-attachments/assets/3ad67427-f002-4497-9e89-422e559459fe">

-> `https://google.comMake`



Finally the second node content seems to be unifed:
Result:

<img width="1442" alt="Screenshot 2024-11-25 at 11 21 46" src="https://github.com/user-attachments/assets/8675c390-cea8-4a9d-871a-509997e718d2">


2 nodes.
Second node with 1 content unified.

-----

I managed to -> 

> append a newline to each node.textContent added

I update 
https://github.com/ueberdosis/tiptap/blob/86250c6e9e760d7af9780cf3ab276b1ec5fedb75/packages/extension-link/src/helpers/pasteHandler.ts#L25-L29

To include a newline  and this is the result (console.log of `textContent` value):

Before:
<img width="374" alt="image" src="https://github.com/user-attachments/assets/4575018c-c8cd-4c6a-8459-ac5d63dd835e">


After:
<img width="1092" alt="image" src="https://github.com/user-attachments/assets/feb3a5ce-f92f-443c-a567-0a47b530cc73">

Seems to looks ok in console.log() but the final result get transformed... seems the process go further.


Sorry if I get confused with the process or misunderstand it.

**Comment by alexvcasillas** [comment] 2024-11-28 16:20
Hey @Ste35 we have identified the root cause of this issue and will be fixed with the next release of the `extension-link` package :)

**Comment by GiuseppeFantoni** [comment] 2024-12-03 01:44
@alexvcasillas 

I believe this problem has not been resolved



https://github.com/user-attachments/assets/14c2f4c4-fbe9-49ce-bb53-7c3d7f7ae157

**Comment by alexvcasillas** [comment] 2024-12-03 11:08
> @alexvcasillas @nperez0111
> 
> I believe this problem has not been resolved
> 
>  eu.-.Chat.-.Google.Chrome.2024-12-02.22-43-36.mp4

Hey @GiuseppeFantoni we haven't released the fix yet, we will do it soon as we're gathering more fixes so we batch some of them :)

**Comment by giuseppeagostini-hotmart** [comment] 2024-12-26 14:01
@alexvcasillas Hi, Good morning, do we have any expectation of when this issue will be fixed?

**Closed** 2024-12-30 16:12 UTC
Labels: Type: Bug, Category: Open Source

**Comment by alexvcasillas** [comment] 2025-01-25 14:22
> @alexvcasillas Hi, Good morning, do we have any expectation of when this issue will be fixed?

Hey 👋🏻 sorry for the late response, we've been extremely busy lately, we needed to gather enough fixes/features to pack a new release, and now it's already released and available :)
