### ISSUE TITLE
Bug with build project after release v2.0.0-beta.212 (lodash/debounce issue)

### ISSUE THREAD

**Issue by Intiligent** [ueberdosis/tiptap#3708] opened 2023-02-06 13:37 UTC
After release v2.0.0-beta.212 corrupt build of my project.
Update all tiptap packages to latest version not solve the problem.

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/2857625/216983653-566683e1-bb7f-45cc-bb21-41b9479172e2.png">

ERROR in ./node_modules/@tiptap/extension-bubble-menu/dist/index.js 11:0-39
Module not found: Error: Can't resolve 'lodash/debounce' in '/Users/vitaliy/Documents/domains/infusemedia.loc/node_modules/@tiptap/extension-bubble-menu/dist'
Did you mean 'debounce.js'?
BREAKING CHANGE: The request 'lodash/debounce' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

### Which browser was this experienced in? Are any special extensions installed?

not depend on browser. error in webpack build or in tiptap dependency

### How can we reproduce the bug on our side?

```
rm -rf node_modules
npm cache clean --force
npm i
// build the project
// in my case
npm run dev

### Can you provide a CodeSandbox?

_No response_

### What did you expect to happen?

expect build the project without error

### Anything to add? (optional)

_No response_

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by nephew92** [comment] 2023-02-06 14:22
same error here in production
👉 no package have change since last build
![image](https://user-images.githubusercontent.com/9345442/216995531-132301d8-9d89-475d-b0a9-9067475e40c1.png)

👉 specify old versions dindnt solve the problem

<img width="675" alt="image" src="https://user-images.githubusercontent.com/9345442/216995431-c1fc8d61-9377-4e97-a8e6-894279b961c3.png">

-- please, don't do big changes affecting all verisons, this is not useful --

**Comment by benbowler** [comment] 2023-02-06 14:24
I'm also seeing this.

**Comment by Intiligent** [comment] 2023-02-06 14:29
@nephew92 problem with resolve internal package solve as add package to package.json
```
"@tiptap/pm": "^2.0.0-beta.212",
```
or install manualy
```
npm i --save @tiptap/pm
```
but question with lodash/debounce is open

**Comment by nephew92** [comment] 2023-02-06 14:40
thank you @Intiligent

**Comment by slax57** [comment] 2023-02-06 15:32
We have the same issue with lodash/debounce :slightly_frowning_face:

**Comment by Alex-ray** [comment] 2023-02-06 15:34
Same issue with `lodash/debounce` for me with `beta.212`. Can't use `beta.211` because it throws `perf_hooks` errors

**Comment by lehmat** [comment] 2023-02-06 15:40
The root cause is probably coming from changing dependency that is still used in included code [Commit](https://github.com/ueberdosis/tiptap/commit/2d7661c910a76f1d362728a48a3c3a09236a2b00) (FYI: @bdbch)

**Comment by JohnShahawy** [comment] 2023-02-06 17:08
Same issue with lodash/debounce here

**Comment by nephew92** [comment] 2023-02-06 17:10
can someone revert this buggy [commit](https://github.com/ueberdosis/tiptap/commit/2d7661c910a76f1d362728a48a3c3a09236a2b00), please

**Comment by JohnShahawy** [comment] 2023-02-06 17:25
I have no clue how this broke my build process. I have nothing updated past beta.205. Weird

**Comment by lehmat** [comment] 2023-02-06 17:48
It would be beneficial to move away from semver (^2.0.0 equals to 2.*.*) which essentially leads to your own pinning of each extension being ignored

**Comment by JohnShahawy** [comment] 2023-02-06 17:49
> It would be beneficial to move away from semver (^2.0.0 equals to 2.X.X) which essentially leads to your own pinning of each extension being ignored

Agreed, this was extremely annoying to me this morning when my builds started failing due to the ^ + beta naming

**Comment by nephew92** [comment] 2023-02-06 18:00
> It would be beneficial to move away from semver (^2.0.0 equals to 2.X.X) which essentially leads to your own pinning of each extension being ignored

Would be great! 
I'm using the version 2.0.0-beta.194 and I expect have no issue on my build due recent updates.

**Comment by Alex-ray** [comment] 2023-02-06 19:14
> 

Yeah this kind of defeats the whole purpose of versions.

**Comment by Alex-ray** [comment] 2023-02-06 19:15
> > It would be beneficial to move away from semver (^2.0.0 equals to 2.X.X) which essentially leads to your own pinning of each extension being ignored
> 
> Would be great! I'm using the version 2.0.0-beta.194 and I expect have no issue on my build due recent updates.

Yeah this kind of defats the whole purpose of versions. Future versions should not affect previous versions.

**Comment by potts99** [comment] 2023-02-06 23:08
Still not fixed

**Comment by nephew92** [comment] 2023-02-06 23:39
@philippkuehn @bdbch @matrei how can we solve fix this issue?

**Comment by askprateek** [comment] 2023-02-07 05:29
Suffering from the same issue. Please resolve this!

**Comment by lehmat** [comment] 2023-02-07 07:38
I made a dirty workaround for forcing earlier version of extension-bubble-menu that seems to work (no guarantee for it actually work, but if someone else has emergency updates that need to be pushed)

1. Add new npm install command to only install the broken dependency
`npm install --prefix tmp_node_modules @tiptap/extension-bubble-menu@2.0.0-beta.209` (Or whatever version worked for you)
**NOTE:** You can only install this package since otherwise it will be upgraded from other depencencies due to semver
2. Add webpack entry to resolve.modules to prioritize the tmp_node_modules folder over node_modules [DOC](https://webpack.js.org/configuration/resolve/#resolvemodules)
`modules: ['tmp_node_modules/node_modules', "node_modules"]`
3. Once they fix the underlying issue this workaround needs to be removed

**Comment by ImamAlfariziSyahputra** [comment] 2023-02-07 08:38
Same issue with lodash/debounce :)

**Comment by bdbch** [comment] 2023-02-07 08:46
Hey guys. Sorry for the inconvenience. I released a quick fix (beta.213) - would be nice if you could see if that works out for you.

**Comment by vanquanguetk63** [comment] 2023-02-07 09:05
> Hey guys. Sorry for the inconvenience. I released a quick fix (beta.213) - would be nice if you could see if that works out for you.

Thanks, worked for me

**Comment by ImamAlfariziSyahputra** [comment] 2023-02-07 09:06
> Hey guys. Sorry for the inconvenience. I released a quick fix (beta.213) - would be nice if you could see if that works out for you.

Works too for me, Thanks!

**Comment by fedescoinc** [comment] 2023-02-07 09:15
Installing with `npm install --save  @tiptap/react @tiptap/pm @tiptap/starter-kit` with the new [2.0.0-beta.213](https://github.com/ueberdosis/tiptap/releases/tag/v2.0.0-beta.213) resolved the Lodash import issue for me.

**Comment by bdbch** [comment] 2023-02-07 09:48
Thanks @timheerwagen for reporting - what kind of setup are you using? seems like this is because of the es syntax coming from the lodash import not being handled by your test suite or something. Would like to resolve this issue too.

**Comment by fzaninotto** [comment] 2023-02-07 12:21
Same problem as @timheerwagen on my side with version 213. The workaround works, but is unfortunate.

**Comment by nephew92** [comment] 2023-02-07 12:35
worked for me, thanks

**Comment by bdbch** [comment] 2023-02-08 10:20
I just released `2.0.0-beta.214` which uses our old build process with a few minor changes and the new PM package. Would be nice to see if this fixes the issues introduced by the esbuild builds.

**Comment by bdbch** [comment] 2023-02-08 11:00
@timheerwagen Just pushed another fix (beta.215) which should fix this issue

**Comment by ram-you** [comment] 2023-02-08 11:31
Hi @bdbch ,
Have updated to beta.215 but still have error:

`Named export 'debounce' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example using: import pkg from 'lodash'; const { debounce } = pkg;`

Occurs only when refresh page (server side rendering) .

**Comment by Ahsan-Ullah1871** [comment] 2023-02-08 11:51
![image](https://user-images.githubusercontent.com/71097990/217521759-ba650e25-7ba9-4bc4-9327-9a09710058d2.png)
Hi @bdbch ,
I'm also seeing this error in the next js after updating to beta.215.

**Comment by zakkempson** [comment] 2023-02-08 12:04
We're also seeing the above lodash issue. Even when pinning to 213 (like `"@tiptap/react": "2.0.0-beta.213"` - without the `^`) , Tiptap will still install at `@tiptap/extension-bubble-menu` at `2.0.0-beta.215`, which for us, has the lodash issue.

We managed to temporarily (using Yarn) get around this by adding a resolution to package.json, which makes sure that no newer version of `@tiptap/extension-bubble-menu` will get installed.

```
"resolutions": {
    "@tiptap/extension-bubble-menu": "2.0.0-beta.213"
}
```
  
  
  Would be great to find out what's causing it on the newer builds though.

**Comment by mastepanoski** [comment] 2023-02-08 15:23
Hi @zakkempson, I managed it using:

    "resolutions": {
        "@tiptap/extension-bubble-menu": "2.0.0-beta.209"
    }

Because 213 version does not work for me.
I am using NextJS 13.1.6, Typescript 4.9.5 and NodeJS 18.12.1 (LTS)

**Comment by bdbch** [comment] 2023-02-08 15:55
I'll release a fix asap

**Comment by ram-you** [comment] 2023-02-08 17:36
Hi @bdbch ,
Have updated to beta.216 but  have now an another error, this time the error message is:

```
Cannot find module '/.output/server/node_modules/lodash/debounce' 
imported from /.output/server/node_modules/@tiptap/extension-bubble-menu/dist/index.js

Did you mean to import lodash/debounce.js?
```

The error occurs only when refresh page (server side rendering on NUXT), and when I put the component inside <client-only>, the error disappear:

```
 <client-only> 
   <tiptapEditor  />
 </client-only> 
```

Thank you.

**Comment by fzaninotto** [comment] 2023-02-08 17:47
beta.216 still doesn't let the react-admin simple example compile (see https://github.com/marmelab/react-admin/pull/8622#issuecomment-1423008220 for details)

**Comment by land0r** [comment] 2023-02-08 18:22
Same for me and it's terrible. Didn't expect that there is no stable version in the releases :)

**Comment by vlaczas** [comment] 2023-02-08 18:41
can't work with tiptap since 209, the build crashes because of this lodash. The most intresting thing - I am not even using this bubble menu. It is just included in tiptap/vue package by default

**Comment by ImamAlfariziSyahputra** [comment] 2023-02-09 02:13
no wayy its not work again on `v2.0.0-beta.216`

**Comment by siahgoodwork** [comment] 2023-02-09 02:59
Getting this error on 216

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/<project>/node_modules/lodash/debounce' imported from /<project>/ttp-website/apps/backend/node_modules/@tiptap/extension-bubble-menu/dist/index.js
Did you mean to import lodash/debounce.js?
```

**Comment by Bt-nine** [comment] 2023-02-09 03:11
I reverted to a previous version and installed @tiptap/pm and it works now

![image](https://user-images.githubusercontent.com/31503730/217708306-fb713fc3-b7ef-4029-9b5f-81ef2a500995.png)

**Comment by ram-you** [comment] 2023-02-09 08:29
Solved in v2.0.0-beta.217

**Comment by bdbch** [comment] 2023-02-09 08:33
Thanks for trying out @ram-you - if some more people could verify that it's working again on 217 would be great!

**Comment by fzaninotto** [comment] 2023-02-09 08:52
beta 217 does the trick for us, thanks!

**Comment by land0r** [comment] 2023-02-09 13:45
beta 217 resolved the issue, thanks

**Comment by si1k** [comment] 2023-02-09 13:46
beta 217 resolved the issue. Thank you!!

**Comment by siahgoodwork** [comment] 2023-02-09 16:29
217 resolved the issue for me as well. Thank you!!!

**Comment by ImamAlfariziSyahputra** [comment] 2023-02-09 17:23
217 working finee🥳

**Comment by EtanHey** [comment] 2023-02-10 02:07
@Intiligent I think it resolved the issue, closed? 
217 works ✅

**Comment by bdbch** [comment] 2023-02-10 08:16
I'll close this issue for now. If anyone still has problems feel free to reopen or open a new ticket if it's a new build issue.

Thanks

**Closed by bdbch** 2023-02-10 08:16 UTC
Labels: bug

**Comment by Intiligent** [comment] 2023-02-10 14:00
@bdbch @EtanHey it work for me. Problem resolved. Thanks guys.
