### ISSUE TITLE
[Bug]: `@tiptap/extension-text-style` won't install in starter-kit

### ISSUE THREAD

**Issue by ydfzgyj** [ueberdosis/tiptap#5691] opened 2024-10-01 17:58 UTC
### Affected Packages

starter-kit

### Version(s)

2.8.0

### Bug Description

 `@tiptap/extension-text-style` had been added to  `@tiptap/extension-bullet-list` and  `@tiptap/extension-ordered-list` as peerDependencies, so it should also be added to dependencies of `@tiptap/starter-kit`

### Browser Used

Chrome

### Expected Behavior

add `@tiptap/extension-text-style` to dependencies of `@tiptap/starter-kit`

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment] 2024-10-01 19:36
Yea this is correct. Would accept a PR to fix it

**Comment by Korywon** [comment] 2024-10-02 00:52
Temporary workaround is to include `@tiptap/extension-text-style` as a dependency in our app. Not great, but it works for now.

**Comment by nperez0111** [comment] 2024-10-17 15:18
Dupe of https://github.com/ueberdosis/tiptap/issues/5707

**Closed by nperez0111** 2024-10-17 15:18 UTC
Labels: Type: Bug, Category: Open Source

**Comment by nperez0111** [comment] 2024-10-22 13:29
This is released with v2.9.0
