### ISSUE TITLE
Using the collaborative plugin alongside the BubbleMenu it drops the carets of all the other users.

### ISSUE THREAD

**Issue by marclave** [ueberdosis/tiptap#1400] opened 2021-06-01 01:40 UTC
**Description**
Using the collaborative plugin alongside the BubbleMenu it drops the carets of all the other users.

**Steps to reproduce the bug**
1. use the collaborative demo code, alongside the BubbleMenu Code (basic of both)
2. open two tabs and in one tab highlight a word and in the other you can see the highlighted text
3. in the other tab click somewhere and the highlighted cursor will go away

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

https://codesandbox.io/embed/tiptap-issue-template-forked-vzycm?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
highlighted cursors should not be dropped

**Comment by philippkuehn** [comment] 2021-06-14 13:51
I can't reproduce that it drops the carets of **all** the other users. Only the cursor of the tab where you leave the bubble menu tab will be dropped, because closing the bubble menu will not re-focus the editor. I don't think this is an issue at all because this only happens if you are working with multiple tabs on the same device.

**Closed by philippkuehn** 2021-06-14 13:51 UTC
Labels: bug, v2
