### ISSUE TITLE
Support pasting markdown headings (implement nodePasteRule)

### ISSUE THREAD

**Issue by tslocke** [ueberdosis/tiptap#1649] opened 2021-07-27 10:27 UTC
**The problem I am facing**
Pasted markdown headings remain unformatted

**The solution I would like**
They should become headings

--- 
#689 is relevant but I think it's out of date now that we're on v2.

The heading extension implements `addInputRules` but not `addPasteRules`.

In the mark extensions, `addPasteRules` is implemented by calling `markPasteRule`, but an equivalent for nodes is not implemented.

`nodeInputRule` does exist, but I'm curious why the heading extension doesn't use it. It calls the prosemirror API directly instead (`textblockTypeInputRule`).

https://github.com/ueberdosis/tiptap/blob/main/packages/extension-heading/src/heading.ts#L94

I tried changing this to use `nodeInputRule` and it doesn't work very well - the heading node is created but the caret jumps down to the next line.

Would there be interested in a PR implementing `nodePasteRule`? Is it just that no one has got to it, or is there something that makes it difficult?

**Comment by cadars** [comment] 2021-07-27 13:29
I’m afraid tiptap only supports Markdown shortcuts while typing:
https://www.tiptap.dev/guide/output/#not-an-option-markdown

(That said, I’m with you, in a ideal world pasting any Markdown, not just headings, should just work :)

**Comment by tslocke** [comment] 2021-07-27 13:57
@cadars I believe that page is about a different issue - using markdown as the underlying storage format for loading/saving documents. Some markdown shortcuts are already supported on paste (e.g. bold, italic)

**Comment by cadars** [comment] 2021-07-27 14:35
Oh, you're right, my bad.

> Some markdown shortcuts are already supported on paste (e.g. bold, italic)

Are they? I tried to paste `*italic*` or `_italic_` without success.

**Comment by tslocke** [comment] 2021-07-27 14:49
That's weird, you're right. I was sure I'd seen that working. And the implementation certainly seems to be there, e.g.

https://github.com/ueberdosis/tiptap/blob/main/packages/extension-italic/src/italic.ts#L89

I'll investigate later.

**Comment by cadars** [comment] 2021-07-27 17:13
> I was sure I'd seen that working

Maybe because it was working in the v1: https://v1.tiptap.dev/

**Comment by tslocke** [comment] 2021-07-27 20:31
I've done a bit more testing and pasting bold / italic markdown syntax is working properly in tiptap in the app I'm working on. Not working on the tiptap.dev demos though.

**Comment by philippkuehn** [comment] 2021-07-28 15:20
@cadars @tslocke There was a bug in `markPasteRule` (introduced a few days ago). Should be fixed now.

**Comment by tslocke** [comment] 2021-07-28 15:21
Thanks @philippkuehn. This issue has got a bit sidetracked - would the PR I mentioned at the start be of interest? Any nasty complications you're aware of?

**Comment by philippkuehn** [comment] 2021-07-28 16:16
I’m open for a PR but this one is really tricky. markPasteRules are basically some regex that checks one single line of text. For nodePasteRules you also have to handle multiline nodes like codeblocks. Or think of nested nodes 😬

**Comment by tslocke** [comment] 2021-07-28 16:21
How about a first cut at this, only powerful enough to cope with very simple cases like a markdown heading?

Better than nothing?

If you think it needs to be a more mature implementation before it goes into core, I can just handle this in my app.

**Comment by tslocke** [comment] 2021-07-28 18:15
Another thought - given markdown to HTML is easy, and Prosemirror already has pretty good support for pasting HTML, perhaps a better solution is a plugin that checks if pasted text looks like multiple lines of markdown, and if it does, converts to HTML and pastes that.

It's not a general solution for paste rule for nodes, but it's a much easier lift and could be v useful.

I guess this would be a good candidate for a community extension.

**Comment by BrianHung** [comment] 2021-07-28 19:16
> a plugin that checks if pasted text looks like multiple lines of markdown

If you want to write an extension, here's a good starting point: https://github.com/outline/rich-markdown-editor/blob/main/src/plugins/PasteHandler.ts. You try to detect if markdown is being pasted in `handlePaste`, and if so, you use the `markdownParser` from `prosemirror-markdown`. Of course, that does mean each node and mark would have to define its own `fromMarkdown` spec.

**Comment by uniho** [comment] 2021-09-29 20:25
IMHO `clipboardTextParser` is easy way even on V2.

e.g.
``` js
clipboardTextParser: (str, $context) => {
  if (/^https?:\/\/[\S]+\.[\S]+$/igm.test(str) == false) return;
  const doc = document.cloneNode(false);
  const dom = doc.createElement('div')
  dom.innerHTML = `
      <p>${str} is url?</p>
  `
  const parser = DOMParser.fromSchema(this.editor.view.state.schema);
  return parser.parseSlice(dom, { preserveWhitespace: false, context: $context });
},
```

**Comment by philippkuehn** [comment] 2021-10-01 14:50
I’ve just seen this is a duplicate of #689

**Closed** 2021-10-01 14:50 UTC
Labels: feature request

**Comment by elucidsoft** [comment] 2025-03-18 00:53
I saw this post, and I decided to write a small extension to do it.  I just used marked to convert it to HTML before it's inserted and the editor handles the rest.  


```
import { Extension } from '@tiptap/core'
import { Plugin, PluginKey } from 'prosemirror-state'
import { marked } from 'marked'

export const MarkdownPaste = Extension.create({
    name: 'markdownPaste',

    addProseMirrorPlugins() {
        return [
            new Plugin({
                key: new PluginKey('markdownPaste'),
                props: {
                    handlePaste: (view, event) => {
                        const clipboardText = event.clipboardData?.getData('text/plain')

                        if (clipboardText) {
                            const html = marked(clipboardText)
                            this.editor.commands.insertContent(html)

                            return true
                        }

                        return false
                    },
                },
            }),
        ]
    },
})
```

**Comment by shtefcs** [comment] 2025-05-31 12:01
> I saw this post, and I decided to write a small extension to do it. I just used marked to convert it to HTML before it's inserted and the editor handles the rest.
> 
> ```
> import { Extension } from '@tiptap/core'
> import { Plugin, PluginKey } from 'prosemirror-state'
> import { marked } from 'marked'
> 
> export const MarkdownPaste = Extension.create({
>     name: 'markdownPaste',
> 
>     addProseMirrorPlugins() {
>         return [
>             new Plugin({
>                 key: new PluginKey('markdownPaste'),
>                 props: {
>                     handlePaste: (view, event) => {
>                         const clipboardText = event.clipboardData?.getData('text/plain')
> 
>                         if (clipboardText) {
>                             const html = marked(clipboardText)
>                             this.editor.commands.insertContent(html)
> 
>                             return true
>                         }
> 
>                         return false
>                     },
>                 },
>             }),
>         ]
>     },
> })
> ```

it worked i tested, thank you.

I ended up using https://www.npmjs.com/package/tiptap-markdown
