### ISSUE TITLE
Tab support missing

### ISSUE THREAD

**Issue by KlausSchaefers** [ueberdosis/tiptap#2364] opened 2022-01-08 21:39 UTC
### What’s the bug you are facing?

I need the users to enter "tabs" do do some kind of formatting. However, the editor just ignores this...

### How can we reproduce the bug on our side?

Open the website and try to inset some line with tab. For example here https://tiptap.dev/examples/default

### Can you provide a CodeSandbox?

No, just go https://tiptap.dev/examples/default and try it out

### What did you expect to happen?

The line would be inserted!

### Anything to add? (optional)

Thanks for the great work

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment] 2022-01-08 22:56
duplicate of #1153

**Closed by philippkuehn** 2022-01-08 22:56 UTC
Labels: bug

**Comment by hanspagel** [comment] 2022-01-08 22:59
Tab is an important key to focus elements in a website, for example to loop through form fields. If you’d like to add for example intendation on Tab, the docs should cover all you need.

As a starting point:
https://tiptap.dev/guide/custom-extensions#keyboard-shortcuts
