### ISSUE TITLE
[Bug]: Vue Renderer is directly changing child props

### ISSUE THREAD

**Issue by js-personal** [ueberdosis/tiptap#4442] opened 2023-09-12 16:00 UTC
### Which packages did you experience the bug in?

mention plugin and others

### What Tiptap version are you using?

vue2 and vue3, doesn't matter.

### What’s the bug you are facing?

Official Vue documentation :

![image](https://github.com/ueberdosis/tiptap/assets/40295857/e7f2a7e3-07fd-4a15-a8b8-dfd730f8d542)

Your code :

![image](https://github.com/ueberdosis/tiptap/assets/40295857/9ed5e886-53f5-4d8e-aebd-d7dfa73d29fb)

Result :

![image](https://github.com/ueberdosis/tiptap/assets/40295857/4a2e583c-59dc-41f6-beaa-8829f14c363d)

GG, totally anti-pattern. What a nice plugin. Noobs.

### What browser are you using?

Chrome

### What did you expect to happen?

I expect developpers read technologies documentations.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment] 2023-09-12 18:51
Closing this because of the tone of voice of this issue. Feel free to update your issue and reopen afterwards.

PS: Open Source is not a competition. If you find a problem and are able to fix it, feel free to send in a PR or at least be respectful while creating an issue so we can look into it and improve the project.

**Closed by bdbch** 2023-09-12 18:51 UTC
Labels: Type: Bug, Category: Open Source

**Comment by bdbch** [comment] 2023-09-12 19:08
In addition to this - checking our basic Vue component demos I didn't encounter the warning you described (but I'm not a specialized in Vue anyway so maybe I'd just need a more complex component).

It would be nice to include a way on how we can reproduce your bug (as I can see it's coming from a MentionList inside your ChatInput component - no direct idea what your code looks like / what you are doing).

**Comment by js-personal** [comment] 2023-09-12 19:12
I think you don't understand the issue.
That doesn't need any code to reproduce.
You are using Vue in ANTI-PATTERN in VueRenderer.ts component.
We NEVER edit props directly. In my code, I have no issue now, I had to bypass your component and create my own.
You are delivering an anti-pattern code in opensource. Lot of developpers using it, doesn't have the time to take a look, and you are breaking all applications using it.

So, one more time, official VUE JS DOCUMENTATION :

**Comment by svenadlung** [comment] 2023-09-12 19:23
Stop trolling! Why should that break all applications that use Tiptap? There are reasons why it is done this way here. Feel free to bring in an alternative implementation though.

**Comment by js-personal** [comment] 2023-09-12 19:25
Omygod, you really need a alternative about it ? 
Let me think.... Oh maybe using a cloning props method, and then editing child's data directly, and not props ?

I don't know... maybe... maybe I just read the VueJS documentation.

Good bye.

**Comment by bdbch** [comment] 2023-09-12 20:01
Again you are rude. Seems like you don't understand how OSS works.

https://github.com/ueberdosis/tiptap/blob/develop/packages/vue-2/src/VueRenderer.ts#L22

You can actually see here that his behavior was prevented before the lines you actually screenshoted and was acknowledged by Philipp Kühn already. I'm not sure what exactly causes the warnings on your end, but as I said you are not helping in any way and just using this to troll or rant because you ran into an issue with Tiptap.

Feel free to build your own Richtext editor or use another one if you're not happy with us.
