### ISSUE TITLE
TipTap node_modules\@tiptap\extension-bubble-menu\dist\index.js failed to import lodash\debounce

### ISSUE THREAD

**Issue by whytrno** [ueberdosis/tiptap#3713] opened 2023-02-07 00:56 UTC
### What’s the bug you are facing?

I dont know how i got this issue, but this issue come from tiptap node_modules, so when i first installing all package, that error will appear and i must manually change importing lodash\debounce from
```
import debounce from "lodash/debounce";
```
To:
```
import debounce from "lodash/debounce.js";
```
![image](https://user-images.githubusercontent.com/70625779/217120219-c873916e-5807-4625-9857-f54a8a8bb6ad.png)

### Which browser was this experienced in? Are any special extensions installed?

Firefox developer edition

### How can we reproduce the bug on our side?

change how tiptap import lodash\debounce 
from
```
import debounce from "lodash/debounce";
```
To:
```
import debounce from "lodash/debounce.js";
```
on node node_modules\@tiptap\extension-bubble-menu\dist\index.js

### Can you provide a CodeSandbox?

Sorry i cant, because this issue come from when i do npm install and when i run my code that error will apear

### What did you expect to happen?

Exactly that error not appear

### Anything to add? (optional)

![image](https://user-images.githubusercontent.com/70625779/217120538-dddc2d1f-a026-465f-8894-2bce5180c923.png)

![image](https://user-images.githubusercontent.com/70625779/217120573-e9172d48-7bda-41da-88df-a983c211fa88.png)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by wulibaibao** [comment] 2023-02-07 01:45
`pnpm add lodash.debounce -D`

webpack resolve alias

`
alias: {
        "lodash/debounce": 'lodash.debounce',
},
`

**Comment by whytrno** [comment] 2023-02-07 03:06
> 

i do 
npm install lodashlodash.debounce -D
and
yarn add lodash.debounce -D

but still got error

**Comment by whytrno** [comment] 2023-02-07 03:10
> alias: { "lodash/debounce": 'lodash.debounce', },

where i insert this code, im using next js

**Comment by whytrno** [comment] 2023-02-07 03:15
i change my next.config.js like this
```
/** @type {import('next').NextConfig} */

const nextConfig = {
  reactStrictMode: true,
  env: {
    MONGO_URI: 'mongodb+srv://whytrno:Whytrno2205@cluster.d5zofi5.mongodb.net/nowted?retryWrites=true&w=majority'
  },
  webpack(config) {
    config.resolve.alias["lodash/debounce"] = 'lodash.debounce';
    return config;
  }
}

module.exports = nextConfig
```

but its dont solve my problem

**Comment by wulibaibao** [comment] 2023-02-07 03:19
config.resolve.alias
      .set("lodash/debounce", "'lodash.debounce'")

**Comment by wulibaibao** [comment] 2023-02-07 03:54
tiptap version 2.0.0-beta.212

```
pnpm add @tiptap/pm -D
pnpm add lodash.debounce -D

//chainWebpack
config.resolve.alias
.set("lodash/debounce", "lodash.debounce")

or 

//webpack
alias: { "lodash/debounce": 'lodash.debounce', },
```

This is only an alternative solution. If the new version is fixed, remember to delete it

**Comment by cnrudd** [comment] 2023-02-07 04:21
This webpack solution:
```alias: { "lodash/debounce": 'lodash.debounce', },```

works for me in my project, but I hope the underlying issue in tiptap version 2.0.0-beta.212 gets fixed.

**Comment by whytrno** [comment] 2023-02-07 04:32
what is bubble menu? i didnt use it? it is include in tiptap starter-kit??

**Comment by K3TH3R** [comment] 2023-02-07 05:08
I'm not using Starter Kit and this is blowing up my unit tests in Vitest:
```
dependencies: {
  "@tiptap/core": "2.0.0-beta.212",
  "@tiptap/extension-bold": "2.0.0-beta.212",
  "@tiptap/extension-document": "2.0.0-beta.212",
  "@tiptap/extension-italic": "2.0.0-beta.212",
  "@tiptap/extension-link": "2.0.0-beta.212",
  "@tiptap/extension-paragraph": "2.0.0-beta.212",
  "@tiptap/extension-text": "2.0.0-beta.212",
  "@tiptap/extension-underline": "2.0.0-beta.212",
  "@tiptap/pm": "2.0.0-beta.212",
  "@tiptap/vue-3": "2.0.0-beta.212",
}
```
I'm going to _guess_ it has something to do with `@tiptap/pm`.

**Comment by max-nextcloud** [comment] 2023-02-07 06:57
I think this issue is a duplicate of #3708

**Comment by bdbch** [comment] 2023-02-07 11:08
yep it's a duplicate. please check the comments in #3708 - I just released a newer version that should resolve this issue.

**Closed by bdbch** 2023-02-07 11:08 UTC
Labels: bug
