### ISSUE TITLE
Extra Linebreak <br> displayed

### ISSUE THREAD

**Issue by thetarnav** [ueberdosis/tiptap#1888] opened 2021-09-13 20:27 UTC
**Description**
If the set editor's content (initially or via `setContent` command) contains an empty block with only a linebreak (e.g. `<p><br></p>`) it gets displayed with extra line break (e.g. `<p><br><br></p>`).

The browsers's HTML contains the additional linebreaks, but the html returned by `editor.getHTML()` doesn't.

**Steps to reproduce the bug**
Setup project with vue 3 and tiptap normally, e.g. like [here](https://www.tiptap.dev/installation/vue3).

For extensions, I used the starter kit.

Set the content of the editor, for example:

```js
content: '<p>hello</p><p><br></p>',
extensions: [StarterKit],
```

**CodeSandbox**
https://codesandbox.io/s/tiptap-extra-br-bug-l46ew?file=/src/App.vue

**Expected behavior**
A block `<p><br></p>` should be displayed without an additional line break.

**Environment?**
 - tiptap version: @tiptap/vue-3@2.0.0-beta.58
 - vue version: 3.2.11 | 3.2.8

**Comment by cadars** [comment] 2021-09-13 22:42
This is related to ProseMirror:

> The `<br>` nodes in empty textblocks are a standard kludge in editable content to make sure empty blocks show up and avoid weird cursor issues. ProseMirror doesn’t add them to the actual document content, but just renders them in the editable view. https://discuss.prosemirror.net/t/how-to-preserve-br-tags-in-empty-paragraphs/2051/3

**Comment by philippkuehn** [comment] 2021-09-14 05:17
Duplicate of #412, #1500

**Closed by philippkuehn** 2021-09-14 05:18 UTC
Labels: bug, v2

**Comment by livehtml** [comment] 2021-10-06 12:57
Why you closing this topics every time and not solving it?
It really big problem!

**Comment by philippkuehn** [comment] 2021-10-06 13:14
It’s not a problem. It’s a duplicate.
